### ISSUE TITLE
adminclaim not protecting pvp

### ISSUE THREAD

**Issue by varnithian97** [bloodmc/GriefDefender#100]
I have installed Grief Defender for the sponge version
Luckperms 5
Spongeforge 1.2.5

Admin claim used, flag override set to on, pvp off, flags for everything except enter and exit off, and people can still hit each other

Not sure why this is.

**Comment by bloodmc** [comment]
Provide the following logs

LP verbose log https://github.com/lucko/LuckPerms/wiki/Verbose
GD debug log  https://github.com/bloodmc/GriefDefender/wiki/Debugging

**Comment by bloodmc** [comment]
Closing as no response in 20 days.
