### ISSUE TITLE
Its not Creating Config Files

### ISSUE THREAD

**Issue by HybridAvenger69** [bloodmc/GriefDefender#102]
I dont know whats wrong but i tried 2 different versions and its not creating config files or properly loading up, cant do commands or anything , 

1.12.2-2838-7.1.7 spongeforge 
griefdefender-sponge-1.2.4-B14.jar
any known issues why its not creating config files or allowing my to do commands

**Comment by bloodmc** [comment]
You are using an outdated build. Issues are meant for bugs in GD. It is not meant to be used for support. If you require support, you can purchase it on https://www.spigotmc.org/resources/griefdefender.68900/

**Comment by HybridAvenger69** [comment]
i used b15 also still didnt work
