### ISSUE TITLE
[Suggestion] Ability to disable Dynmap provider and other providers

### ISSUE THREAD

**Issue by Lemmmy** [bloodmc/GriefDefender#103]
It's really awesome that GD ships with a Dynmap provider (saves having to install  [Dynmap-GriefPrevention](https://www.curseforge.com/minecraft/mc-mods/dynmap-grief-prevention-addon)). 

Our server has a custom implementation of this plugin with a lot of extra features bespoke to our setup. We're looking to migrate to GriefDefender soon, however, other than hiding the `griefprevention.markerset` marker set, there seems to be no way to disable the provider. The same seems to be true for the other non-essential providers, [WorldEdit, WorldGuard, Essentials, Dynmap, and PlaceholderAPI (Bukkit)](https://github.com/bloodmc/GriefDefender/blob/23e7daab72cfee4878cb479e013781d8608af776/bukkit/src/main/java/com/griefdefender/GriefDefenderPlugin.java#L454-L475) and [Dynmap, MCClans, Nucleus and WorldEdit (Sponge)](https://github.com/bloodmc/GriefDefender/blob/23e7daab72cfee4878cb479e013781d8608af776/bukkit/src/main/java/com/griefdefender/GriefDefenderPlugin.java#L454-L475).

I definitely agree that these should be enabled by default if the plugins are present, however the ability to disable them, even with ` dynmap.disabled` config entry would be nice.

**Comment by bloodmc** [comment]
Added in commit https://github.com/bloodmc/GriefDefender/commit/189187fd25776fd22da4bf3e47d1741b004161b2
