### ISSUE TITLE
Format Request

### ISSUE THREAD

**Issue by SirLeezus** [bloodmc/GriefDefender#105]
Hello, I messaged you on Spigot and was told to open a ticket here so my request was not forgotten. 

My request was adding a format filter for {reason} or all errors so they would look something like this: "Below Min Size X" vs "BELOW_MIN_SIZE_X" as shown here as well: https://gyazo.com/0d71c5db6cf62d537612270c9fa2868a

Putting all the errors in the lang would also work fine as well.

Thanks a bunch! :)

**Comment by kencinder** [comment]
Closing this because these things are in lang now and have been for awhile.
