### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by 89009332** [bloodmc/GriefDefender#108]
Sorry, my English is not good, I hope you can understand.

Support to record the total number of claim blocks used by players on all servers on bungeecord

emm...

Example: The player has 150 claim blocks globally, the player claim 30 blocks on server A, and the remaining 120 claim blocks. There are no claimed blocks on server B, but there are also 120 claim blocks left.

Chinese

支持在BC上记录玩家在所有服务器上已经占领的方块总量

例子：玩家一共可以占领150个方块，在A服务器占领了30个方块，剩余120个可用方块。在B服务器没有占领方块，但也剩余120个可用方块。

**Comment by 89009332** [comment]
My English is very poor. I'm not sure if you understand what I mean.
Now GD sets playerdata to global mode. The situation is as follows: If I open 3 sub-servers and the player has 10,000 blocks, they are 10,000 blocks on each server, so they actually have a total of 30,000 blocks. What I hope is that if the player has 10,000 cubes, the player can only use 10,000 cubes in all sub-servers.

**Comment by bloodmc** [comment]
If the playerdata is set to global mode (the default) and the player has 10,000 blocks then they could only spend 10,000 for all 3 servers. The player would NOT have 30,000 blocks. Make sure you are using a shared LP database with playerdata set to global mode.
