### ISSUE TITLE
Featherboard Integration

### ISSUE THREAD

**Issue by Cosido** [bloodmc/GriefDefender#11]
Featherboard
https://www.spigotmc.org/resources/featherboard.2691/

Current Featherboard Placeholders for GriefPrevention
https://i.imgur.com/fphbk0d.png

Featherboard is a fully customizedable scoreboard, which support placeholders for many, many plugins. Symbols, Colors, Scrolling Colors, Text, Animation, and Idk probably more, mine Isn't great, still working on it.

There are "event-trggers" which is a action performed by a player that triggers a change in scoreboard.
You can have a default board, with server information display naturally, but lets say the player hits a creature, he has entered combat. There is a "event-trigger" for combat, if its set to true and a player enters combat, it triggers the combat scoreboard, which can display information relevant only to combat, as well as cosmetic headers/footers/etc.

There is integration with Spigots GriefPrevention, but I was wondering if sometime down the line you could communicate with the author of FB and integrate GriefDefender. Im not sure on what end (yours or his) this would need done.
My Scoreboard:
The default one has scrolling text i can alter, changing colors, a placeholder for the users name and prefix, and balance.
The combat one has a placeholder for the users health, his targets name and its health.
https://i.imgur.com/804SIN4.gifv

As an example for what it could be with GD, if you entered a claim, it could say the claim owners name, your claimblocks you have left, your number of claims, etc.

This would be a easily visible and customizable scoreboard specific to only being in claims

**Comment by runescapejon** [comment]
GriefDefender has api. This allow featherboard to make placeholder. Just like GriefPrevention I personally believe that you should contact Maximvdw on spigot for requesting like thing like this.

**Comment by bloodmc** [comment]
Featherboard works fine. See Featherboard docs on how to use placeholders for plugins that us Placeholder API.
