### ISSUE TITLE
Players can't abandon claims

### ISSUE THREAD

**Issue by VOrlando520** [bloodmc/GriefDefender#111]
Issues on 1.2.5-b16 for sponge 
Player makes a claim, goes through the abandon process and then hits accept. Does not get a removed claim confirmation and the claim still happens to be there until next server reboot. 

This is the error from logs when player goes to abandon claim https://pastebin.com/wxJykwBL

Even though the claim still registers as being active

**Comment by bloodmc** [comment]
Dupe #96
