### ISSUE TITLE
Creating basic claim via GD API not functioning

### ISSUE THREAD

**Issue by Brend-Smits** [bloodmc/GriefDefender#112]
GD Version: 1.2.6
GD API Version: 1.0.0-SNAPSHOT
LuckPerms Version: v5.0.39
Sponge version: spongeforge-1.12.2-2838-7.1.10-RC3994, also tested with: 1.12.2-2838-7.1.9

Hey there,
When using the GD API to create a claim automatically with a particular size, it seems to not be functioning. No claim is being created.
See the following code snippet.
`ClaimResult result =  Claim.builder().world(getWorld().getUniqueId()).bounds(new Vector3i(regionLesserCornerX, 0, regionLesserCornerZ), new Vector3i(regionLesserCornerX + 511, 255, regionLesserCornerZ + 511)).owner(player.getUniqueId()).requireClaimBlocks(false).sizeRestrictions(false).resizable(false).type(ClaimTypes.BASIC).build();`
Our scenario is like this: Player creates and island, plugin generates the island, Grief Defender protects it by claiming the whole region file from bedrock to sky limit. This worked fine on Grief Prevention. 
We're updating the plugin to work on GD after moving from Grief Prevention. 
There are no errors in the console.

**Comment by bloodmc** [comment]
What is the result type being returned?

https://github.com/bloodmc/GriefDefenderAPI/blob/master/src/main/java/com/griefdefender/api/claim/ClaimResult.java#L41

**Comment by Brend-Smits** [comment]
> What is the result type being returned?
> 
> https://github.com/bloodmc/GriefDefenderAPI/blob/master/src/main/java/com/griefdefender/api/claim/ClaimResult.java#L41

ClaimResultType.SUCCESS is being returned.

**Comment by bloodmc** [comment]
Should work fine with latest API update.
