### ISSUE TITLE
Can't change economy buy price

### ISSUE THREAD

**Issue by timr2000** [bloodmc/GriefDefender#113]
The block price is locked at $70, when i try to change to economy-block-cost="10.0" it doesnt do anything and keeps the price on $70

Griefdefender 1.2.5c
Paper-105 (MC: 1.15.2)

**Comment by bloodmc** [comment]
https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/java/com/griefdefender/configuration/category/DefaultPermissionCategory.java#L86

The default price is 0. If it is reporting 70 then you have it set in LP meta which is overriding the config value. Keep in mind the config values are transient meta meaning they merely act as defaults and will be overridden when a new value is set in LP.

To debug this issue further, use LP's verbose command

See https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by timr2000** [comment]
oh didn't noticed that.. it works now thanks for the help!
