### ISSUE TITLE
Admin/User Toggle

### ISSUE THREAD

**Issue by Phamous1** [bloodmc/GriefDefender#114]
admin/user mode Toggle for Admins/Mods

 to avoid unintended changes to the defaults and such while they are playing.  So we can avoid accidental changes to things while they themselves are actually playing the game and not performing duties. A way to kind of separate them from accidentally making large changes and having to pay extra close attention to what they are changing and rather be able to just change their own options like a normal user would.  As most of my staff are actual players and just help out with staff duties.

**Comment by bloodmc** [comment]
This was resolved in GD 1.4.0+ with ADMIN tab only applying to claim you are in. Defaults are now only controlled via config.
