### ISSUE TITLE
[Suggestion] Add a display setting to flags

### ISSUE THREAD

**Issue by IzzelAliz** [bloodmc/GriefDefender#116]
Currently flags uses its flag name as display name in chat gui, which is inconvenient for players in other country. Add a `display` setting node to custom-flags will certainly improve this.

```hocon
definitions {
  block-break {
    contexts=[
      "gd_claim_default=global"
    ]
    description="Controls whether blocks can be broken."
    display="Block Break" # or in another language
    enabled=true
    permissions=[
      "flag=block-break"
    ]
  }
}
```

**Comment by DrWurzeli** [comment]
You can change the second line.
Here is an example of my custom user flags for german people:
`
                definitions {
                    Benutzen {
                        contexts=[
                            "server=global"
                        ]
                        description="Können Spieler Nicht-Kisten Blöcke benutzen?"
                        enabled=true
                        permissions=[
                            "flag=interact-block-secondary",
                            "flag=interact-entity-secondary"`
screnshot ingame:
![javaw_ZYCuPwtqkh](https://user-images.githubusercontent.com/54333442/74862107-d2a67b80-534b-11ea-8b04-6abbf4d4fbb2.png)

**Comment by bloodmc** [comment]
As @DrWurzeli  stated, simply rename the flag names to your liking.
