### ISSUE TITLE
Enhancement | PlayerTakeLecternBookEvent

### ISSUE THREAD

**Issue by DrWurzeli** [bloodmc/GriefDefender#117]
Suggestion:
Add [PlayerTakeLecternBookEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerTakeLecternBookEvent.html) listener to the "interact-inventory" flag.

log of me opening and taking the book right now (with trust, just for the events):
[Log](https://griefdefender.github.io/debug/?eEMF74Pj4p)

I'd love to use a flag like:
`/cf interact-inventory lectern_book false` or `/cf interact-inventory lectern:take_lectern_book false`
that still allows users to open the book placed on the lectern and read all the pages, but cancels the PlayerTakeLecternBookEvent when they click on "Take Book":
![javaw_Ad4JCZAeoE](https://user-images.githubusercontent.com/54333442/74863751-afc99680-534e-11ea-9ec5-c86dbe89570c.png) but for that, the event needs to be present and denied.

Thanks for considering the suggestion. much love from germany

**Comment by bloodmc** [comment]
This was fixed in earlier releases.
