### ISSUE TITLE
Broken flags and teleport issue

### ISSUE THREAD

**Issue by blurdesign** [bloodmc/GriefDefender#119]
The flags associated with snowfall and ice formation do not work as intended. Ice forms and snow falls even when they're disabled inside an admin claim. Players are also able to place water in admin claims where the block-place flag is disabled.

When using /claiminfo in certain claims and then clicking on the claim corners to teleport the player gets teleported above the nether at bedrock.

**Comment by bloodmc** [comment]
Please provide your server version, GD version, and LP version.

**Comment by Brycey92** [comment]
@blurdesign did you close this because you fixed the issues?
