### ISSUE TITLE
Add a submenu in /claiminfo to manage trust in the chat directly instead of using a command

### ISSUE THREAD

**Issue by Kazer67** [bloodmc/GriefDefender#12]
The goal is to manage the trusted player directly in the chat in a submenu (like it work with [children] subclaim in the chat).

I see two way I can think of to help manage :
1) You do /claimlist and you click on the player nickname. There you can either switch the type of trust (Accessor, Container etc) or you can remove from the current trust.

2) You do /claimlist and you click on the "type" (Builder, Manager etc) of trust, and there you have a list in the chat where you can remove player from it like:

Nickname1 [x]
Nickname2 [x]
Nickname3 [x]

**Comment by bloodmc** [comment]
Added in commit https://github.com/bloodmc/GriefDefender/commit/ab6db04328d72d14f633913e79bc5b66c080e09b
