### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by HeberonYT** [bloodmc/GriefDefender#120]
Hi, I am trying to create the GriefDefender jar file but an error always occurs.
I have already downloaded the API project but that does not solve it.
![Screenshot_7](https://user-images.githubusercontent.com/13698597/74971039-0a153680-53e5-11ea-9167-ad04258227df.png)

**Comment by bloodmc** [comment]
It cannot find the spigot jar. GD issue tracker is not meant for helping you build spigot.
