### ISSUE TITLE
Where can i download sponge version?

### ISSUE THREAD

**Issue by Explosivee** [bloodmc/GriefDefender#122]
In old GP discord it says `GriefDefender is free to use but If you require support, purchase it on https://www.spigotmc.org/resources/griefdefender.68900/ to get access to the private discord.` i saw a channel called as `Updates` and there is Sponge GD files however you told me that `griefdefender-sponge-1.2.4-B15.jar` is a very old build and it's the last one you shared in that discord channel

**Comment by bloodmc** [comment]
Build it on github.
