### ISSUE TITLE
Could not find org.spigotmc:spigot:1.15.2-R0.1-SNAPSHOT when compiling for bukkit

### ISSUE THREAD

**Issue by Brycey92** [bloodmc/GriefDefender#125]
When compiling the plugin for bukkit, none of the repositories in the build.gradle are found to contain the spigot snapshot:
```
> Could not resolve all files for configuration ':bukkit:compileClasspath'.
   > Could not find org.spigotmc:spigot:1.15.2-R0.1-SNAPSHOT.
```

The files gradle searches for in the relevant repository are:
```
- https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.15.2-R0.1-SNAPSHOT/maven-metadata.xml
- https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.15.2-R0.1-SNAPSHOT/spigot-1.15.2-R0.1-SNAPSHOT.pom
- https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.15.2-R0.1-SNAPSHOT/spigot-1.15.2-R0.1-SNAPSHOT.jar
```

I browsed to `https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/` but was only able to find `spigot-api` and `plugin-annotations`, not `spigot`.

**Comment by bloodmc** [comment]
Because spigot cannot be posted publicly due to licensing reasons. You have to build it yourself.
