### ISSUE TITLE
GriefDefender doesn't migrate claims from GriefPrevention on Sponge

### ISSUE THREAD

**Issue by Brycey92** [bloodmc/GriefDefender#128]
When `griefprevention-sponge` is set to true in the `migrator` section of global.conf for GriefDefender, and the server is loaded with claims in the griefprevention directory within the plugins config directory, the migrator doesn't import them, and doesn't issue any warnings, errors, or exceptions.

It imports claim flag defaults just fine, so the setting is being seen by the plugin and acted upon.

I think GriefDefender may be written to only check the default shared mods/plugins config directory, and not to get the current plugin config directory from Sponge. This would cause this observed behavior for non-default locations of the config directory, like mine, but would work via coincidence for most server owners.

[logs.zip](https://github.com/bloodmc/GriefDefender/files/4290521/logs.zip)

**Comment by bloodmc** [comment]
All GD does is copy the GriefPrevention claims folder to GD's. Just copy it manually or copy it to the standard config folder and it will migrate fine on startup.

**Comment by Brycey92** [comment]
I fixed the migrator (see PR #130), and it copies the files now, but the claims aren't present in-game. Any ideas?

**Comment by kencinder** [comment]
Check that your world UUID(s) haven't changed, the migrator does work perfectly fine.

**Comment by Brycey92** [comment]
I combined my changes in #130 with a regenerated global.conf file, and it works now! The claims show up in-world, and the stick works to find them again.

**Comment by Brycey92** [comment]
The issue I was seeing where GD didn't migrate claims was due to hardcoded config paths fixed in my PR, and the issue where the copied claim files still didn't appear in the world was due to #132.

**Comment by bloodmc** [comment]
Marking this as resolved since PR's were merged.
