### ISSUE TITLE
The expiration-cleanup-interval setting breaks the plugin, and is not used correctly

### ISSUE THREAD

**Issue by Brycey92** [bloodmc/GriefDefender#132]
If you set `expiration-cleanup-interval` to a value > 0 in the config, when the plugin loads, claims that should exist don't, and inspection/claiming tools such as the stick and gold shovel don't print messages to chat.

Additionally, the setting is never used, and instead a hardcoded interval of 10 seconds is passed to the scheduler:
```
Sponge.getScheduler().createTaskBuilder()
        .interval(10, TimeUnit.SECONDS)
        .execute(cleanupTask)
        .submit(GDBootstrap.getInstance());
```

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/c1e5843482c00a9b09d9539713c8781ff71658a2
