### ISSUE TITLE
Greetings and Farewells behave inconsistently when formated in colors.

### ISSUE THREAD

**Issue by color-space** [bloodmc/GriefDefender#135]
Reproduce:

be in Wilderness 
and have an Admin claim infront of you
(Wilderness has some overrides)

/gd claim greeting &eUnprotected
/gd claim farewell &2Protected

Either only one works, or both don't work.
If before "&" there is another character it seems to work.

Spongeforge 7.1.8 RC3964

**Comment by bloodmc** [comment]
I cannot reproduce this on Bukkit side. Can you confirm it is still an issue with latest SF/GD.

**Comment by kencinder** [comment]
Just tested this on latest Spongeforge, GD and Luckperms and it's working fine. Greeting shows up in green, farewell in yellow.

Closing
