### ISSUE TITLE
Tinkers Construct BUG

### ISSUE THREAD

**Issue by bigenergy** [bloodmc/GriefDefender#138]
I found a bug, any player can pump tools from tinkers construct destroying blocks on another's claim. The block is not destroyed, but the pumping is in progress. Used spongeforge.

griefdefender-sponge-1.2.6-B1
spongeforge-1.12.2-2838-7.1.11-RC4007

**Comment by pinkpig3777** [comment]
I would like to see this bug fixed as well before I buy the plugin, assuming it can be reproduced.

**Comment by LemADEC** [comment]
What do you mean by "pump tools"? can you be more specific?

**Comment by kencinder** [comment]
GD build in original post is very old at this point, if this is still an issue on 1.5.10+ please make a new ticket with relevant information and steps to reproduce.
