### ISSUE TITLE
IC2 meta read bug

### ISSUE THREAD

**Issue by bigenergy** [bloodmc/GriefDefender#139]
I use sponge.
I am trying to create a flag to access only one block (ic2:te.67), Fill in everything as indicated on the wiki. But it does not work

https://griefdefender.github.io/debug/?rkTHtTeXXO

![image](https://user-images.githubusercontent.com/17977139/76689685-73394400-6649-11ea-8937-1a5fd752043f.png)

Probably GD can't read meta IC2 tiles.

**Comment by bigenergy** [comment]
You can also read this. https://discordapp.com/channels/594941472621723716/594944709387091998/688461656816222466

**Comment by TheKlimoT** [comment]
> 
> 
> You can also read this. https://discordapp.com/channels/594941472621723716/594944709387091998/688461656816222466

Мне кажется это не совсем баг плагина кстати, ибо он же другие меты считывает.

**Comment by bloodmc** [comment]
You are not supposed to be using meta anymore. GriefDefender supports blockstates so you need to pass that as a context like so

```
/cf block-break ic2:te true context[state=type:ore_washing_plant]
```

I'll add a new column in debug for showing blockstate.

**Comment by TheKlimoT** [comment]
> 
> 
> You are not supposed to be using meta anymore. GriefDefender supports blockstates so you need to pass that as a context like so
> 
> ```
> /cf block-break ic2:te true context[state=type:ore_washing_plant]
> ```
> 
> I'll add a new column in debug for showing blockstate.

not working

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/81021912-f8d0b780-8e74-11ea-8ec6-e4880c79c18e.png)
Not work :( don't open

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/81022212-b9ef3180-8e75-11ea-86fe-599d6254fa40.png)
Generator opening, trade_o_mat nothing.
/cf interact-block-secondary ic2:te true context[state=type:generator] -work
/cf interact-block-primary ic2:te true context[state=type:trade_o_mat] - don't work

**Comment by bloodmc** [comment]
Next release will contain context column that will show state context.
