### ISSUE TITLE
Automatically replace the player UUID with the nickname / groupname in /claiminfo

### ISSUE THREAD

**Issue by Kazer67** [bloodmc/GriefDefender#14]
Context:

Migrating data from GriefPrevention for Sponge to GriefDefender for Spigot/Paper.

Until the player connect, /claiminfo will show the UUID instead of the nickname. The goal is to do the same work as website such as mcuuid to convert directly to the nickname and "fix" what claiminfo display.

Group name is also a GUUID instead of the name of the group or public.

![2019-07-28_13 49 03](https://user-images.githubusercontent.com/45577220/62006265-d8c5d800-b12d-11e9-975d-21cf6cbd04e7.png)

**Comment by bloodmc** [comment]
Group names were fixed in commit https://github.com/bloodmc/GriefDefender/commit/347419a7fd5edd8ed469981d396d1d9992a2f2ee

As for player UUID to name, copy LP's uuidcache. If using json-storage, this would be found under `./LuckPerms/json-storage/uuidcache.txt`
