### ISSUE TITLE
Changing block data not prevented by block-place or block-modify

### ISSUE THREAD

**Issue by Flarkinater** [bloodmc/GriefDefender#142]
[Here's my debug where I demonstrate this issue](https://griefdefender.github.io/debug/?24cbOpFZ27).
I was standing on a block of Purple Concrete, and used the command `/setblock ~ ~-1 ~ concrete 1`, which successfully turned it into Orange Concrete. I then did `/setblock ~ ~-1 ~ dirt`, which did _not_ turn the block into dirt. The "block-place" permission was not checked for the first command, but it was for the second. This seems like unintended behavior.
Obviously I demonstrated this issue with admin-commands, but it could be relevant to regular players on servers with mods or plugins that include blocks that can be dyed, or wrenches that can rotate blocks.
My suggestion would be that "modifying block data" should be something that's prevented by block-modify.

**Comment by bloodmc** [comment]
Thanks for the report. Can you please provide your server version, GD version, etc.. as the link you provided is expired.

Thanks!

**Comment by Flarkinater** [comment]
At the time, it was:
Forge version: 2838
Spongeforge version: 7.1.8
GD version: Griefdefender-sponge-1.2.2-TEST9

I haven't tested with the newest versions since then, but I'll do so when I can.

**Comment by kencinder** [comment]
GD build in original post is very old at this point, if this is still an issue on 1.5.10+ please make a new ticket with relevant information and steps to reproduce.
