### ISSUE TITLE
Can't exit the trust list

### ISSUE THREAD

**Issue by lauju71** [bloodmc/GriefDefender#145]
I can't exit the trust list on my claim after trying to add someone without doing the command, by click [+]. There is no cancel button, and whenever I type something in chat, it brings up the trust list.

**Comment by lauju71** [comment]
Server restarts fixes it, but even if you leave the server and log back, the problem still occurs.

**Comment by hutchy50** [comment]
Make sure you have the perm griefdefender.user.chat.capture and disable the record chat option at the bottom of the GUI
