### ISSUE TITLE
Players unable to create Claims

### ISSUE THREAD

**Issue by Darkstar2508** [bloodmc/GriefDefender#146]
In our default world that we use for claiming, players are unable to create claims unless they have access to WorldGuard bypass. We've tested this in other worlds with players in default rank and they're able to create claims however after speaking to the WorldGuard support they said it's not related to their plugin as to why claims don't work in normal world.

When players try to create claims in the main world this is the message shown : https://cdn.discordapp.com/attachments/684182576520364038/688819781646024716/unknown.png

We've had the issue for a few weeks now and are looking to get it sorted ASAP.

**Comment by bloodmc** [comment]
Please provide the exact steps to reproduce this on a clean server with only GD/LP/WorldGuard

**Comment by bloodmc** [comment]
Closing due to no response.
