### ISSUE TITLE
snow_layer

### ISSUE THREAD

**Issue by Ahmadh26** [bloodmc/GriefDefender#151]
"snow_layer" flag should be changed to "snow", Minecraft changed it's name from 1.13.x 
it causes flags to misbehave.

**Comment by bloodmc** [comment]
Flag definitions are not `Flags`. They are simply a way for admins to create custom permissions using GD flags and contexts. As for `snow_layer`, you can simply change it in GD's global.conf to reflect the minecraft version you are using. Flag definitions delivered with GD are provided as a basic template and are meant to be changed/altered to fit your server needs.

With that said, I'll look at moving the flag definition generation to version lib.

**Comment by Ahmadh26** [comment]
Thanks.
