### ISSUE TITLE
Enter/Exit claim message does not show in action bar

### ISSUE THREAD

**Issue by SnowBlitzz** [bloodmc/GriefDefender#155]
> message {
        # The default chat type to use when sending enter/claim messages to a player.
        # (0 = Chat, 1 = ActionBar, 2 = Title)/nNote: ActionBar is only available in MC 1.11+
        enter-exit-chat-type=1
        # Whether GD prefix should be shown in enter/exit claim messages. (Default: true)
        enter-exit-show-gd-prefix=true
        # Set the locale to use for GD messages. (Default: en_US)
        # Available languages: de_DE, en_US, es_ES, fr_FR, ru_RU. The data is stored under assets in jar.
        # Note: The language code must be lowercase and the country code must be uppercase.
        locale="en_US"
    }

The message still appears in chat, not the action bar.

**Comment by kencinder** [comment]
Title does not work either, I believe it was explained that KyoriText has not implemented this yet.

**Comment by bloodmc** [comment]
This was a bug in kyori and should work in GD 1.4.4 as kyori was updated to latest.
