### ISSUE TITLE
Support eating food whilst staring at blocks

### ISSUE THREAD

**Issue by DrZoddiak** [bloodmc/GriefDefender#157]
**GD**: 1.2.6
**SF**: 1.12.2-2838-7.2.0
**LP**: 5.0.116

Currently if I were to have `interact-block-secondary` false in claims then a user looking at a block and attempting to eat food would not be able to do so [as shown in the two calls in this debug](https://griefdefender.github.io/debug/?kiUjocb6JI):

I would suggest a few methods in ensuring this works.

1. Allowing the `#food` context key to be used in the `context[used_item=]`

2. Checking either the `item-use` or `interact-item-secondary` flags if `interact-block-secondary` fails

My secondary concern with allowing this however would be allowing users to use chests/tile-entities if they are allowed to eat food, so if there's a way to ensure that doesn't happen if this is implemented that'd be fantastic!

**Comment by Brycey92** [comment]
I would also love to use this for things like splash and normal potions, bows, mod backpacks, etc!

**Comment by bloodmc** [comment]
This was resolved in 1.4.0+
