### ISSUE TITLE
Add method to remove claimname

### ISSUE THREAD

**Issue by DrZoddiak** [bloodmc/GriefDefender#158]
**GD**: 1.2.6
**SF**: 1.12.2-2838-7.2.0
**LP**: 5.0.116

Currently there isn't any _at least documented_ method of clearing a claim name.

I would request following the way `/gd claim greeting clear` and simply allow `/gd claim name clear`

**Comment by kencinder** [comment]
I do believe using the following works

`/gd claim greeting ""` `/gd claim name ""`

**Comment by bloodmc** [comment]
https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/java/com/griefdefender/command/CommandClaimGreeting.java#L65

Just pass `clear`
