### ISSUE TITLE
Claimflag command should accept block ids with dot character '.' in them

### ISSUE THREAD

**Issue by LemADEC** [bloodmc/GriefDefender#159]
As of griefdefender-sponge-1.2.6-B4 + spongeforge-1.12.2-2838-7.2.1-RC4010, claimflag command doesn't accept block ids which have a . in them.
For example:
`/cf interact-block-secondary warpdrive:air_generator.superior 0 context[source=minecraft:player,override=global]`
=> this is rejected saying "Invalid target 'warpdrive:air_generator.superior' entered for base flag interact-block-secondary"

`/cf interact-block-secondary warpdrive:particles_collider 0 context[source=minecraft:player,override=global]`
=> this is accepted

There was no specific logs in console when using both commands.

Here's a screenshot of the related error messages
![image](https://user-images.githubusercontent.com/4776032/78415034-81162f80-761f-11ea-9c70-67c4509f7a96.png)

**Comment by bloodmc** [comment]
Working as designed. The mod is not registering block with name `warpdrive:air_generator.superior` in block registry. The error message you posted only occurs when it cannot perform a lookup in registry.

**Comment by LemADEC** [comment]
The mod does register all its blocks in the blocks registry through the Forge event RegistryEvent.Register<Block> as seen in debugger here:
![image](https://user-images.githubusercontent.com/4776032/80870179-16e7bd80-8ca5-11ea-9a25-8df376cba890.png)
Other blocks without . in their name are properly accepted by the GriefDefender command.

When setting the flag through LuckPerms online editor, without using GriefDefender command, then it works. I didn't try with LuckPerms command.

I couldn't find any documentation pointing to a constrains to have no . in the registry name.

**Comment by bloodmc** [comment]
Are you testing this in SpongeForge environment? The lookup GD performs is against SF block registry. Do a test and show me it exists in SF's registry then I'll take a deeper look.

**Comment by bloodmc** [comment]
Nevermind, I confirmed it does indeed register it properly. Let me fix =)

```
[13:04:40] [Server thread/INFO] [STDOUT]: [com.griefdefender.internal.registry.BlockTypeRegistryModule:registerDefaults:62]: Registering block type warpdrive:air_generator.superior
```

**Comment by bloodmc** [comment]
All fixed! Thanks for the report. It turns out your original assumption was correct. There was old meta check that was stripping anything after `.`
