### ISSUE TITLE
Creepers ignoring explosion-entity and entity-damage flags when explosion-block FALSE is set

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#161]
Spongeforge 1.12.2-2838-7.2.1-RC4011
Luckperms 5.0.125
griefdefender-sponge-1.2.6-B4

`/cf explosion-block any false context[source=creeper,override=global]`
or
`/cf explosion-block any false context[source=creeper]`
All other flags at their defaults.

Creeper no longer destroys blocks, but will not cause damage to entities(Particularly the player, the goal of this is to still damage at least players). A gddebug shows explosion-entity and entity-damage TRUE, but they do not actually occur and removal of the flag set reverts creeper behavior to normal.

Also of note is that `/cf explosion-block any false context[source=creeper,default=global]` does not work at all. Creepers still break blocks AND damage entities.

@DrWurzeli tested on bukkit side and found that the first 2 flags work, but that use of `default=global` also does not work on bukkit.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
