### ISSUE TITLE
Subdividing an admin claim

### ISSUE THREAD

**Issue by SnowBlitzz** [bloodmc/GriefDefender#165]
When subdividing an admin claim, the subdivision will have the claim flag defaults and overrides of a basic claim instead of an admin claim. I've tested multiple times and can 100% confirm and reproduce this.

**Comment by kencinder** [comment]
Fully intended, subs do not have their own flag set.

**Comment by SnowBlitzz** [comment]
From a user's standpoint, subdividing is dividing the claim you're in into smaller sections. So if I subdivide a basic claim then it should inherit basic, and if I subdivide an admin claim it should inherit admin. Does that make sense lol

**Comment by Vercci** [comment]
This was a little confusing when I was doing some admin subdividing, but after setting it to admin claim it does properly work as admin within admin claim.

**Comment by kencinder** [comment]
Precisely, there is no reason for subs to use admin flags, create an Admin within an Admin claim if you want that.
Subs are intended to behave like basic claims, and thus use the basic claim defaults.
