### ISSUE TITLE
[Request] CFG/CFP GUI like flags GUI, or show entries set for player/group in the flags GUI

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#166]
Would be nice if these either showed in the flags GUI via context hover, or had their own GUI entirely.

Currently the wiki states `Gets/Sets flag permission for a group in claim you are standing in.` but passing only `/gd flag group [group]` or `/cfg [group]` only shows usage.

Sure you can check it in Luckperms, but it would be nicer to see things in-game in the context of GD usage.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
