### ISSUE TITLE
Effortless Building completely ignores claim protections

### ISSUE THREAD

**Issue by Vercci** [bloodmc/GriefDefender#168]
GriefDefender 1.2.4
SpongeForge 1.12.2-2838-7.1.8-RC3968
luckperms 5.0.49

We're hosting Omnifactory 1.2.1 which has effortlessbuilding-1.12.2-2.12 . We're also using Prism for block history and lookups.

We have a large admin claim around our spawn, but today were alerted to people being able to build on top of the land protected by GD admin claim if they swap to placing blocks via effortless building (left alt by default, normal+ works)

They're also able to swap protected blocks that can be broken by hand normally with whatever block is in hand by using the quick replace mode if in survival. If the player is in creative but does not have claim permissions, they can still quick replace any block. (all of this paragraph is default and intended behavior of effortless building outside of claim bypassing that it's doing at the same time)

Effortless gives you a bit more range on block placements, at its edges in survival I get no error at all on block placement. If you're close enough to whatever you're placing, GD can detect you attempting to use the block in hand on the block in world, tells you you don't have permission, but still places the block. Whether or not GD detects the block you're placing with effortless building, Prism makes no note of a block being placed. Assuming Effortless not linking the blocks placed to the player placing them is the problem,

I've added to the bitbucket issues page that already existed about placing in claimed chunks, though that specific thread mentioned ftb claimed chunks. Can confirm it happens in GD too.

Let me know if I'm supposed to link or say anything else.

**Comment by kencinder** [comment]
You are reporting an issue with a Griefdefender build that is months old, a Spongeforge build that is nearly a year old, and Luckperms that is over 50 builds behind.

Update them all to latest(Or at least Spongeforge recommended).

**Comment by Vercci** [comment]
Updated to
 
GriefDefender 1.2.6
SpongeForge 1.12.2-2838-7.2.0
luckperms 5.0.130

And pretty sure I've re-tested every scenario I talked about in the post, no difference same bypassing happens with me using /cfd, at range or not, creative or not.


And just because I don't think I explained it well, I've added to the existing thread on Effortless Building's bitbucket issues tracker, though the OP in that thread mentions it bypassing FTB claim's instead. Not sure if I should make a new thread for them, and I don't know github enough to poke others if they're supposed to be poked. Will be editing that thread with the updated versions I've now tested it with

**Comment by kencinder** [comment]
Please provide a debug of these things following https://github.com/bloodmc/GriefDefender/wiki/Debugging

**Comment by Vercci** [comment]
https://griefdefender.github.io/debug/?J9L6BUFBZj

That was me starting debug recording on me, turning on /cfd, turning on effortless building's normal+ block placing mode.
Placing a log on stone at close range
Placing a log on stone at the edge just outside of hand range
Turning on quick replace mode in effortless
Replacing Oak planks with an Oak log at close range
Replacing Oak planks with an Oak just outside of hand range
Then pasting the recording.

Here's a screenshot of the aftermath of placing the 4 blocks, also put in the chat feedback of everything if that's useful. It's also showing what I mean by placing out of hand range.
https://i.imgur.com/inJXzVc.png

And here's the rest of the setup I got ready for the test, should show you what the first row looked like beforehand. I was gonna repeat in creative mode, then repeat both of them with /cfd off in case that had some useful but thought it might pollute the recording with useless info. Let me know if you need those done too.

https://i.imgur.com/g8e14Gx.png

**Comment by kencinder** [comment]
Ok so no `block-place` or `block-break` is showing up in the debug, which I would expect to see normally.

Given what I can see watching the Youtube video for how the mod works, I'm willing to bet it doesn't fire events in a proper/standard way like a player would. It would be akin to trying to block Worldedit copy+paste, which isn't fired directly by the player.

Probably why it also has problems with FTBUtils claiming.

**Comment by Vercci** [comment]
You snuck in while I was making an edit, thought I could block it for the spawn claim at least by blocking the interact-item-secondary in the claim, but that didn't work either. There's a debug log there if you want it.

**Comment by kencinder** [comment]
Saw your edit while I was typing my response, even that one is missing events.

bloodshot will have to speak on the matter, but I've seen it before and I'll bet on this being an issue on the mods end for not firing events correctly(At least in terms of breaking/placing blocks that can be tracked).

**Comment by bloodmc** [comment]
It completely ignores cancelled events. Log a ticket with the mod dev as this is not GD's issue.

https://bitbucket.org/Requios/effortless-building/src/3e5eb4cb30cd6736fddd26a28e6f557c498c6031/src/main/java/nl/requios/effortlessbuilding/EventHandler.java#lines-88:133

https://bitbucket.org/Requios/effortless-building/src/master/src/main/java/nl/requios/effortlessbuilding/buildmodifier/BuildModifiers.java
