### ISSUE TITLE
[Suggestion] Add claim UUID support to /trust and /untrust  

### ISSUE THREAD

**Issue by 02Miki** [bloodmc/GriefDefender#175]
Would it be possible for /trust, /untrust, /gd cleantrust, etc to support claim UUIDs? Like /trust (ign) (UUID), or even some sort of secondary command, /admintrust? /atrust? 
And allow console to run that aswell, cause atm, you can trust people to other claims by using LP, but you can't untrust them if they got trusted with /trust, or any sort of command.
Thank you!

**Comment by bloodmc** [comment]
This was implemented in GD 2.x. Just pass the claim identifier at end of command. To set a claim id for a claim, stand in claim and use `/claimid <identifier>`
