### ISSUE TITLE
Is it Possible to disallow flight and god mode in claimed area?

### ISSUE THREAD

**Issue by SuBZoiD** [bloodmc/GriefDefender#177]
I know its possible to disallow the command execution for /fly and /god, but I also want the players whom have flight and god enabled, to **automatically have them disabled by the claim**. is this at all possible or should i just move on to command blocks?

**In the picture** is my attempt to deny flight and god mod using _**/claimoption**_, but for some reason its not working :(

**PS**. we are also running luck perms on the server. and command blocks are disabled on server for safety reasons.
**mc version:** 1.12.2

![Capture](https://user-images.githubusercontent.com/53588373/79569875-2372f000-80c1-11ea-8798-60a8ac253f20.PNG)

**Comment by DrWurzeli** [comment]
GD/LP version?
As a fix for now you could also use the griefdefender.player-command-enter option to run a fly/god disable command on everyone entering.

**Comment by SuBZoiD** [comment]
thank you for your reply @DrWurzeli 

versions:
GD 1.2.6
SpongeForge 1.12.2-2838-7.2.1-RC4011
Lp 5.0.63

I tried the below cmds but they're not working :/
```
/claimoption player-command-enter "/god %player% false" [run_for=member, run_as=console]
/claimoption player-command-enter [run_for=public, run_as=console] "/god %player% false"
/claimoption player-command-enter "/god %player% false" [run_as=console]

```
![Capture](https://user-images.githubusercontent.com/53588373/79588629-df8de400-80dc-11ea-9d9e-a8ea6fdc07ac.PNG)
