### ISSUE TITLE
Attempting to create a claim that overlaps another one will hide the glowstone block showing the first claim corner

### ISSUE THREAD

**Issue by aljaxus** [bloodmc/GriefDefender#18]
// The title speaks by itself

Server version: 1.12.2
Plugin version: 1.0.2-RC2

Issue:
when I try to create a new claim, which overlaps another claim, the initial glowstone block is hidden and the claim that is in the way is shown.

This is an issue, because now I don't see where I started my claim.
I'd suggest that you show some other blocks when you're showing claims that are in the way and keep the glowstone block visible. (as an example, griefprevention uses some nether blocks [don't remember which ones tho])

**Comment by bloodmc** [comment]
This has been fixed in 1.1.0 Release
