### ISSUE TITLE
ASM issues between Spark and GD (7.1 vs 5.2)

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#180]
Latest Spark dev builds have started using ASM 7.1, whereas it appears GD is using 5.2 debug lib.

Spark builds previous to the use of ASM work fine, see change - https://github.com/lucko/spark/commit/4eff32f040d023e225937c1a59583f1e89b2cac2#diff-8d7fdd338d06ab58388387b78f561cd1

Error - https://gist.github.com/kencinder/6eb2b10e99941bd0feedf2b81d4b6642

Older working dev builds are unavailable on Luck's build server.
I have provided users at least with a working Spark JAR for now on Discord.

**Comment by bloodmc** [comment]
Unable to reproduce using latest spark builds on Sponge/Paper.
