### ISSUE TITLE
How to disallow players to return to a claim after leaving it

### ISSUE THREAD

**Issue by SuBZoiD** [bloodmc/GriefDefender#184]
### Description:
A great solution to this matter simply would be:
 `/cf entity-teleport-to player false`

But when thats done, **I lose my abilty (as an admin) to force tp players inside** that claim using /tphere or /tppos.

is there any _context_ or any other solution that might be able to solve this?

### More info:
**Plugins:**
GD 1.2.6
SpongeForge 1.12.2-2838-7.2.1-RC4011
Lp 5.0.63

**Why do i need this:**
I'm building a pvp arena, and i've managed to disable all commands that will allow anyone to leave the arena alive, except for the winner 🤕. **I'm just concerned about players running /back after their death.** this will definetily cause chaos.

PS. I would rather not disable /back 👯‍♂️

**Comment by kencinder** [comment]
Use a 1 block subdivision inside it where you can teleport them to. Then turn off teleport for the parent claim, and turn off inheritance in the subdivision.

**Comment by Brycey92** [comment]
Maybe a command could be added like /forcetphere if none of those solutions work out

**Comment by SuBZoiD** [comment]
so basically i just set spawn to an area where they cant do /back in just for the period of the event :D
