### ISSUE TITLE
Prevent explosions above sea level

### ISSUE THREAD

**Issue by cryoten** [bloodmc/GriefDefender#185]
This plugin is meant to be a replacement for GriefPrevention due to it no longer being supported, or at least that's my understanding of it.

Is it possible to prevent explosions above sea level like in GriefPrevention?

**Comment by bloodmc** [comment]
I'll add a context to support this soon.

**Comment by bloodmc** [comment]
A new blacklist has been added to config to prevent explosions above surface based on source. Check latest developmental builds on discord.
