### ISSUE TITLE
custom claim

### ISSUE THREAD

**Issue by lela-null** [bloodmc/GriefDefender#188]
I had a plugin once that have a unique claim where you claim it like a 2D claim and it would take the lowest claim corner + down a variable amount of blocks (set in config) and claim up to the sky limit.

Can this be a feature?

**Comment by Myth-1300** [comment]
That is a part of grief defender already.

**Comment by DrWurzeli** [comment]
@Myth-1300 can you share where one would configure it? cant recall it ever being a think in GD.

**Comment by bloodmc** [comment]
You simply adjust the `griefdefender.min-level` in options. See https://github.com/bloodmc/GriefDefender/wiki/Advanced-Options
