### ISSUE TITLE
[Suggestion] A Command To Delete All The Claims (And Flags) In A World

### ISSUE THREAD

**Issue by WhatsTheBadNews** [bloodmc/GriefDefender#189]
With Minecraft 1.16 (Nether Update), I am sure many servers are going to want to delete just their Nether so they can get the new terrain.

Of course you can just delete /plugins/GriefDefender/worlds/nether/world_nether but, that won't get rid of all the flags that have been adjusted for those claims in your LP data (I think).

I feel like something, like 

> /gd delete allworld world_nether

 or something like that would be an elegant solution.

**Comment by bloodmc** [comment]
This has been resolved with GD 1.4.4. You can do the following

```
/abandonall <world>
/deleteall <player> <world>
/deletealladmin <world>
/abandonworld <world>
```
