### ISSUE TITLE
Divine RPG bypass bug

### ISSUE THREAD

**Issue by bigenergy** [bloodmc/GriefDefender#190]
I found a bug, portals from the Divine RPG mod can be created on someone else’s claim player
This does not work with nether portals, but works with divine RPG portals

**Comment by kencinder** [comment]
GD build in original post(Assume 1.2.6 as per authors other post around same time) is very old at this point, if this is still an issue on 1.5.10+ please make a new ticket with relevant information and steps to reproduce.
