### ISSUE TITLE
Pistons are not working on claims 

### ISSUE THREAD

**Issue by AuroriumWorlds** [bloodmc/GriefDefender#192]
Pistons and redstone isn't working with default values on player claims, not sure where to get this changed! Tried setting pistons:true but that doesn't work!

**Comment by AuroriumWorlds** [comment]
Okay this is fixed, leaving this here for anyone who needs help. Add this entry to the custom "pistons" flag in the config.

"flag=block-break, target=minecraft:air, source=minecraft:piston"

Thank you.

**Comment by bloodmc** [comment]
@AuroriumWorlds Thanks for the report. Did this happen with Sponge or Spigot/Paper? Can you please provide the versions?

Thanks!

**Comment by bloodmc** [comment]
No issues with latest development builds.
