### ISSUE TITLE
GD Claim Restore returns incompatibility

### ISSUE THREAD

**Issue by AngellitoX** [bloodmc/GriefDefender#193]
Hello!

Using: PaperSpigot build 217
GD Version: GriefDefender 1.2.6 DEV1

When using /gd claim restore I get this message that I understand it's not precisely a bug.

https://pastebin.com/2sD7hsmv

Thank you!

**Comment by bloodmc** [comment]
Spigot doesn't support restoring chunks yet. Once they do it will work.

**Comment by Fabrimat** [comment]
I know that WorldEdit found a way to implement the regen feature, is something releated to create a virtual world with the same seed and copying blocks from it. 
I'm not sure about it, but it works (is very laggy, but it works)

**Comment by bloodmc** [comment]
This is already implemented in the latest development builds. Use `/claimrestore` to regen or `/claimschematic` to restore from a schematic.
