### ISSUE TITLE
Set block-grow to false in claim. Vines are still growing

### ISSUE THREAD

**Issue by blackeyedgamer** [bloodmc/GriefDefender#194]
I even used the command /gd flag claim block-grow vine false context[source=vine,override=claim]
to make the vines at spawn not grow and they still grow.

**Comment by bloodmc** [comment]
This was fixed in latest dev build.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/c3b6e3b6fb25aa0e06c447af97946075972b3d60
