### ISSUE TITLE
WECUI drag visuals do not show.

### ISSUE THREAD

**Issue by caffeineggs** [bloodmc/GriefDefender#197]
WECUI drag visuals on 1.12 sponge-forge 7.2 / 7.2.2
hide-wecui-drag-visuals-2d=false
Only shows the border upon creating claim, no dragging visual.
WECUI is liteloader version, works fine with gp.
Tried both world edit versions for forge and sponge.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
