### ISSUE TITLE
Inefficient copying of chunksToClaimMap

### ISSUE THREAD

**Issue by makkarpov** [bloodmc/GriefDefender#199]
Currently public API of GP/GD exposes ability to retrieve set of claims for chunk via `getChunksToClaimMap`. However, it returns immutable **copy** of that map instead of **view**. 

https://github.com/bloodmc/GriefDefender/blob/master/sponge/src/main/java/com/griefdefender/claim/GDClaimManager.java#L463

This is very inefficient when you need to query that many times. I suggest using either `Collections.unmodifiableMap` or some other similar wrapper to provide view without copying.

I don't think that concurrent modifications that can appear in that view would be an issue, but other solution is to add separate method to public API that will return view.

**Comment by bloodmc** [comment]
Fixed in 1.4.4
