### ISSUE TITLE
Bug with NPC

### ISSUE THREAD

**Issue by WhiteBite** [bloodmc/GriefDefender#200]
When i`m trying to use npcwand(or another method to spawnNPC this happened

![image](https://user-images.githubusercontent.com/19576772/80985683-36fbb600-8e38-11ea-93f3-8841bc7f7d54.png)

Help plz. I have admin permission.

**Comment by DrWurzeli** [comment]
whats the problem?
the "You may claim up to 999090 more blocks." message?
Use another tool for inspecting claims than sticks (configurable in global.conf) or - if enabled - turn of /claim mode :)

if you think GD is blocking the spawn of your NPC do the following:
/gd debug record
try to spawn the NPC
/gd debug paste
paste the link to the debug here :)

**Comment by bloodmc** [comment]
https://github.com/bloodmc/GriefDefender/wiki/Debugging
