### ISSUE TITLE
Town tag not working in Town Chat

### ISSUE THREAD

**Issue by Peydunn** [bloodmc/GriefDefender#201]
[![Screenshot from Gyazo](https://gyazo.com/6fc086fb35b8c34e7637151e356f97c1/raw)](https://gyazo.com/6fc086fb35b8c34e7637151e356f97c1)

On Latest LP, Nucles, GD, and SF.

**Comment by Peydunn** [comment]
https://pastebin.com/5jhSBS59 latest.log

**Comment by DrWurzeli** [comment]
On Latest LP, Nucles, GD, and SF.
doesnt look like it in the log.
v5.0.39 LP while latest is v5.0.147...
provide actual version numbers please and a reason why this would be caused by GD.
