### ISSUE TITLE
Flags IC2 don't work

### ISSUE THREAD

**Issue by TheKlimoT** [bloodmc/GriefDefender#204]
After a while, the flag just stops working, I put the trading device, at first it works, later it can't be opened.

/cf interact-block-secondary ic2:te true context[state=type:trade_o_mat]

/cf interact-block-primary ic2:te true context[state=type:trade_o_mat]

**Comment by DrWurzeli** [comment]
provide setup with versions and gddebug please.

**Comment by TheKlimoT** [comment]
[18:21:56] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [GD] Event: InteractBlockEvent.Secondary.MainHand\n[GD] Target: ic2:te\n[GD] Permission: griefdefender.flag.interact-block-secondary\n[GD] Location: (-497, 64, 1173) User: theklimot\n

**Comment by TheKlimoT** [comment]
/cf interact-block-secondary ic2:te true context[state=type:trade_o_mat, override=basic]

**Comment by bloodmc** [comment]
You need to provide a proper debug using `/gddebug record` and `/gddebug paste`. Also make sure you are using the latest version of LP/GD/SF.

**Comment by TheKlimoT** [comment]
https://griefdefender.github.io/debug/?I7uLs88Ywd

**Comment by TheKlimoT** [comment]
Why false?
![изображение](https://user-images.githubusercontent.com/26817853/81197958-963d0000-8fc9-11ea-9707-bac8aa017d2d.png)

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/81198053-b66cbf00-8fc9-11ea-9800-3f66f3474417.png)

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/81198324-0481c280-8fca-11ea-9136-c0f66cd35c76.png)

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/81202687-a0fa9380-8fcf-11ea-855a-df129998a128.png)
At first it opens, but after a while it can't be opened.

**Comment by bloodmc** [comment]
Unable to reproduce

https://griefdefender.github.io/debug/?kN7CLXyiKZ

Setup a test server with latest SF/GD/LP/IC2 only then provide exact steps to reproduce.

**Comment by TheKlimoT** [comment]
There are no exact steps, it randomly appears, you put a block at first it can be opened to other players, then it just does not open. If I put this block as an admin, then you can always open it.
