### ISSUE TITLE
Gwmcrates with defender

### ISSUE THREAD

**Issue by GoddessArtemis89** [bloodmc/GriefDefender#207]
I have griefdefender and I'm using gwmcrates, we reclaimed our spawn and now it won't let anyone use the key that we chose for the chest. It keeps giving them an error saying they don't have permission to use a tripwire hook on a chest. I've tried every flag I thought might be the one but just tells me that there is no valid command. 

Nvm fixed it!

**Comment by Brycey92** [comment]
@GoddessArtemis89 if this is fixed, please close the issue.
