### ISSUE TITLE
Banning an item should ban pickup

### ISSUE THREAD

**Issue by Brycey92** [bloodmc/GriefDefender#210]
Currently, banning an item will ban most interactions with it. but users can still pick it up. This results in the item being stuck in their inventory until an admin can edit it out.

**Comment by DrWurzeli** [comment]
cant reproduce with latest dev18 GD build, paper280 and LP 5.1.9.
item-pick-up get denied as well as everything else.
using /gd ban hand while holding the oak sign as an admin, testing with user account as shown here:
![javaw_vPV4deu703](https://user-images.githubusercontent.com/54333442/81805086-8ae25b00-951a-11ea-90ab-c2ce7a7dc268.png)

if you ban items after someone picked it up, you will need to clear them.

are you using modded items?

**Comment by Brycey92** [comment]
Yes, I banned a Botania Mana Bottle with Botania r1.10-363, SpongeForge 1.12.2-7.2.1, LP 5.0.152, and GD 1.2.7-DEV10. We don't see that message or pickup blocking, though I haven't tested on vanilla items.

**Comment by bloodmc** [comment]
If this is still an issue with GD 1.4.4, provide a gddebug and lp verbose link.

**Comment by Brycey92** [comment]
Will test when I have time! (Hopefully this week)
