### ISSUE TITLE
[Suggestion] New town claim trust level

### ISSUE THREAD

**Issue by Hypermoron** [bloodmc/GriefDefender#211]
Town claims in their current state are mostly useless. The only way a player can create their own claim within a town is by giving them manager trust, which means that they also have access to all other claims within the town.

My proposal is a new trust level for town claims only, something like "resident". It would be used much like other trust levels (/trust <player> resident, griefdefender.user.claim.trust.resident), and would enable players to create claims within the specified town. It would not inherit any other trust levels, so access/build/container trust would be defined separately and manager trust would override it.

**Comment by bloodmc** [comment]
Forgot to close this. I added `resident` trust a few versions back to solve this issue. Resident trust allows a player to create claims in a town or admin claim and nothing else.
