### ISSUE TITLE
/giveblocks assigns blocks to bonusblocks rather than claimblocks.

### ISSUE THREAD

**Issue by RobinWhitfield** [bloodmc/GriefDefender#212]
The command /giveblocks assigns given blocks as bonus blocks rather than accrued blocks, ignoring max accrued blocks.

This enables users to get infinite blocks over time by either working together, or alternatively using the command on themselves (which presumably shouldn't be possible).

It appears that this command also does not check that the user has enough blocks to give (at least with admin permissions).

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
