### ISSUE TITLE
Setting player-teleport-delay option breaks teleporting

### ISSUE THREAD

**Issue by danparson** [bloodmc/GriefDefender#213]
**Versions**
- GriefDefender 1.2.6 (also tested on 1.2.7-DEV22)
- SpongeForge 7.2.1 (also tested on 7.2.2-RC4027)
- LuckPerms 5.1.28

**Reproduction Steps** (after initial setup)
1. In options.conf, set the default user option `player-teleport-delay` to 5 and restart the server.
2. Give self `griefdefender.user.*` permission.
3. Create a basic claim.
4. Use `/gd claim list` and click on "[TP]" next to the claim listing.

**Expected Results**
I am shown the [teleport delay notice](https://github.com/bloodmc/GriefDefender/blob/1813bd06f4868ccd08c6fc5ef4479693ef9d70e2/common/src/main/resources/assets/lang/en_US.conf#L618), then after 5 seconds, I am teleported to the claim.

**Actual Results**
I am not shown the teleport delay notice and I am not teleported after the configured delay. However, if I move, I _am_ shown the teleport canceled message.

**Comment by AngellitoX** [comment]
Hello. Can you please update version? 
Latest build is 1.4.0-DEV6 and there has been a LOT of improvements for everything, so your issue may be fixed along the way.

**Comment by danparson** [comment]
**Versions**

GriefDefender 1.4.0-DEV6
SpongeForge 7.2.2
LuckPerms 5.1.62

Looks like the functionality's there! The only minor issue I see is that the "teleport cancelled" message is always displayed when I am teleported, but the actual teleport is still successful.

**Comment by kencinder** [comment]
This issue has been fixed, and I'm pretty sure so was the message issue. If the message issue is still present, please open a new issue for it.
