### ISSUE TITLE
RemoveClaimEvent.Delete isnt trigger 

### ISSUE THREAD

**Issue by Flashback083** [bloodmc/GriefDefender#214]
Using spigot version griefdefender-1.2.6-DEV1.jar (1.12.2)

GDRemoveClaimEvent.Delete event = new GDRemoveClaimEvent.Delete(claim);
GriefDefender.getEventManager().post(event);

Seems missing here
https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/java/com/griefdefender/command/CommandClaimDelete.java#L101

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
