### ISSUE TITLE
Sell / buy blocks disabled

### ISSUE THREAD

**Issue by imartinezgregori** [bloodmc/GriefDefender#218]
I want enable Buy/sell CB's and I have all config all right but when I execute the command says it is disabled, I have the Total Economy plugin and is on sponge

**Comment by kencinder** [comment]
Enabling economy mode disables buying blocks (As per the comments in the config)

If you're not using economy mode, but want to allow buying/selling of blocks with an economy plugin, the costs must be set in order for it to work.

```
            economy-block-cost="0.0"
            economy-block-sell-return="0.0"

These options default to 0 in the config, they must be set, and the server restarted for buying and selling to function.
