### ISSUE TITLE
'/gddebug paste' error, followed by spam + low TPS

### ISSUE THREAD

**Issue by Pulz-TCP** [bloodmc/GriefDefender#221]
I used /gddebug record playername, /gddebug paste (got an error), /gddebug off
This appears in console when I run the paste command: https://gist.github.com/Pulz-TCP/b630024deafcfd439611c6bc96da4733

20 minutes later I start getting spammed about max debug limit reached, with the TPS absolutely tanking too: https://gist.github.com/Pulz-TCP/36919c7c8e377a3f0a9af5dff090208a

I've run tiquality and GD together for a while, don't believe I've encountered the issue before.

SpongeForge: 1.12.2-2838-7.2.2
Minecraft Forge: 14.23.5.2854
GriefDefender: griefdefender-sponge-1.3.0-DEV8 (I see I'm behind a version now, I can update in the morning and post back after further testing)

**Comment by bloodmc** [comment]
Fixed in 1.3.4
