### ISSUE TITLE
Better claim greeting/farewell prefix

### ISSUE THREAD

**Issue by SnowBlitzz** [bloodmc/GriefDefender#222]
Currently, there's an option to enable or disable claim greeting/farewell prefixes and the prefix that shows when enabled is just [GD]. I think this can be improved. Something as simple as [%player%'s claim] will give more information to the players going in and out of the claim and will also prevent some players from putting troll messages to fool new or inexperienced players.

**Comment by Brycey92** [comment]
I've also had players setting troll messages on entry and exit.
