### ISSUE TITLE
Spawn-limit

### ISSUE THREAD

**Issue by AngellitoX** [bloodmc/GriefDefender#223]
![image](https://user-images.githubusercontent.com/1666907/83851410-f1046d00-a6d7-11ea-914f-1bfbb1e74085.png)

I was using `/claimoption spawn-limit 12 context[target=#monster]` which would limit all the monsters in the claim, but instead it just allowed me to have 12 skeletons, 12 zombies, 12 spiders, etc at the same time, in the same claim. 

Perhaps the  spawn-limit isn't detecting all of them as one.

**Comment by bloodmc** [comment]
As discussed, this is how it currently works. If GD allowed grouping, whoever spawned first would win and you would have many types that would never spawn.

1.3.2 fixes some issues with it though =)
