### ISSUE TITLE
User Claims Going to Wilderness

### ISSUE THREAD

**Issue by godslam** [bloodmc/GriefDefender#224]
I have a user who created three subdivisions within his claim and then gave two to two other users and kept one for himself. He deleted them all and afterward one of the users had a blank claim and the owner had a blank claim, but the third user did not.

Their blank claims were under worlds>wilderness>basic for some reason.

**Comment by bloodmc** [comment]
Reproduce on clean server and provide exact steps.

**Comment by bloodmc** [comment]
Unable to reproduce.
