### ISSUE TITLE
[LAG] Grief Defender blowing up my server

### ISSUE THREAD

**Issue by GTBelo** [bloodmc/GriefDefender#225]
Grief defender is lagging a lot on my server, see the error:

https://pastebin.com/N2LLi0E0

07.06 18:11:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
07.06 18:11:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1616) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1030) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:172) [Citizens.jar:?]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:863) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:846) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1339) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:611) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:482) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:579) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:92) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.06 18:11:31 [Server] INFO org.bukkit.event.EventException: null
07.06 18:11:31 [Server] ERROR Could not pass event EntityDamageByEntityEvent to GriefDefender v1.2.5

**Comment by bloodmc** [comment]
Using completely outdated version.
