### ISSUE TITLE
Chest-Access flag not preventing players from opening chests

### ISSUE THREAD

**Issue by andrewmlawrence** [bloodmc/GriefDefender#227]
When I set up a claim, only trusted players can build on it, but everyone can open chests within the claim. When I check the claim flags it says Chest-Access is False and that it is overridden by an administrator and cannot be changed. 

Using GriefDefender version 1.3.5 on a Spigot Paper 1.15.2 server with LuckPerms 5.1.26.

List of Plugins:
-BetterRTP
-ChestShop
-CommandSigns
-Essentials
-EssentialsAntiBuild
-EssentialsChat
-EssentialsGeoIP
-EssentialsProtect
-EssentialsSpawn
-EssentialsXMPP
-GriefDefender
-HolographicDisplays
-Jobs
-LuckPerms
-mcMMO
-pvpstats
-Vault
-Votifier
-VotingPlugin
-WorldEdit

**Comment by bloodmc** [comment]
GitHub Issue tracker is not used for `support`. If you want support, ask in the discord support channel.
