### ISSUE TITLE
Saving claims data to database?

### ISSUE THREAD

**Issue by loperd** [bloodmc/GriefDefender#228]
What do you think about saving claims data to database like SQLite, MySQL or PostgreSQL?
Should I wait for the addition of dbs support?

**Comment by AngellitoX** [comment]
Hello loperd, this is already on the table. If you don't have the plugin yet, feel free to purchase it and use it without hesitation, as importing support will be added.

Stay tuned!

**Comment by bloodmc** [comment]
Yes it is planned so I can move all claim data to a DB. As for other data such as flags/playerdata and options(meta), this is all stored with LuckPerms so if you use a DB for LP then its already in a database.

**Comment by TheFlash787** [comment]
Not to add any useful information to this, but it’d like to contribute by suggesting that MongoDB is added to the pool of data stores too since it wasn’t initially mentioned. 

I hope this is still planned however!
Thanks.
