### ISSUE TITLE
GriefDefender's .dat files ignore the specified world container [Bukkit]

### ISSUE THREAD

**Issue by granny** [bloodmc/GriefDefender#230]
There's a JVM argument that I added that makes all the worlds get placed in a directory that I choose.
```cs
>java -jar spigot.jar --help
-W, --universe, --world-container, --   World container (default: .)
  world-dir <File: Directory
  containing worlds>
```
I have it set as `-W worlds`, which means all worlds will be placed in the `worlds` folder. For whatever reason, GriefDefender doesn't listen and places it on the default, which is alongside the server jar.
```
├───world
│   └───data
│       └───griefdefender
│           └───r.0.0
└───worlds
    ├───world
    │   ├───advancements
    │   ├───data
    │   ├───datapacks
    │   ├───playerdata
    │   ├───poi
    │   ├───region
    │   └───stats
    ├───world_nether
    │   └───DIM-1
    │       ├───data
    │       ├───poi
    │       └───region
    └───world_the_end
        └───DIM1
            ├───data
            ├───poi
            └───region
```

Looking into the code I see this line [FileStorage.java#L86](https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/java/com/griefdefender/storage/FileStorage.java#L86) and tried updating it;

```diff
-        rootWorldSavePath = new File(".").toPath();
+        rootWorldSavePath = Bukkit.getWorldContainer().toPath();
```
but that didn't work, so I'm out of ideas.

**Comment by bloodmc** [comment]
Fixed in 1.4.7
