### ISSUE TITLE
Placeholder request

### ISSUE THREAD

**Issue by Kirrasio** [bloodmc/GriefDefender#235]
Looking for a basic placeholders to check if and one to check how many claims a user has.

%Griefdefender_has_claim%
%Griefdefender_claims% <- returns how many claims a user has. Thank you.

**Comment by bloodmc** [comment]
https://github.com/bloodmc/GriefDefender/wiki/PlaceholderAPI

This is already supported per type.

**Comment by Kirrasio** [comment]
Ok, I misunderstood, it says on the placeholders page 'you are standing in' but it appears to work everywhere.

**Comment by bloodmc** [comment]
Ah, I'll update wiki wording. Thanks!
