### ISSUE TITLE
enter-claim bypass using bikes from pixelmon

### ISSUE THREAD

**Issue by hutchy50** [bloodmc/GriefDefender#236]
If you have enter-claim blocked on any it is possible to skip the event entirely using any of the two bikes from pixelmon.

Basically for a while if you ride a pokemon into a claim that denies entry it can glitch tp to the other side of the claim.

Bikes on the other hand occasionally glitch straight into the claim, this can be easily reproduced by riding into the side of a claim and tapping forward. Lets you straight in.

Sponge Version: 7.2.3
GD Version: 1.4.4
LP Version: 5.1.75

**Comment by hutchy50** [comment]
Just a small update. This also works with boats and I'm assuming other similar land mounts

**Comment by bloodmc** [comment]
Thanks! I wrote a workaround in case this happens to bypass. GD will check current claim to validate you are able to enter and if not cancel it. The fix will be included with next release 1.4.8

**Comment by bloodmc** [comment]
Actually, looking at this some more, the proper fix would be to have sponge fire events for vehicles with no player. However, the pixelmon bike issue is odd. I get a bunch of `[15:09:56] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Mach Bike moved wrongly!` when cancelling the event. It seems it glitches through when you stop then try again. I'll have to play with this some more. My original workaround is fine but it would add more performance strain which wouldn't be good so I'll work on a better solution =)

**Comment by bloodmc** [comment]
Did this occur on older SF versions? This seems like a SF bug as cancelling the event outright still produces the same issue.

**Comment by hutchy50** [comment]
I've now tried going back as far as Sponge 7.1.6 and it was still happening

**Comment by bloodmc** [comment]
Fixed in Sponge.

https://github.com/SpongePowered/Sponge/commit/e9dde5ab4076eacad13f61c3028259774c5143d6
