### ISSUE TITLE
Incorrect ID for signs and odd .* behavior

### ISSUE THREAD

**Issue by TakoidGit** [bloodmc/GriefDefender#24]
https://griefprevention.github.io/debug/?pkMoBlf0Np

If you look at this debug here, you can see that ``minecraft.oak_wall_sign`` is being used for the ID rather than the correct ``oak_sign`` ID. This is true for all signs as far as I can tell.

The issue with .* flags can be replicated by giving setting ``interact-block-primary.*`` to false and adding specific context flags set to true for individual blocks. For example, setting ``interact-block-primary.minecraft.oak_wall_sign`` to true will not allow you to interact with only oak sign's as intended.

**Comment by bloodmc** [comment]
These are all normal id's as per mojang's official id list. See https://minecraft.gamepedia.com/Sign
