### ISSUE TITLE
Separate Claim Block Count Per World

### ISSUE THREAD

**Issue by ianmcvann** [bloodmc/GriefDefender#241]
Hello!

I was doing some testing with your plugin and while it functions excellently, I noticed that I couldn't seem to get it working with separate claim block counts for different worlds, not counting existing claims in other worlds towards that count. As the plugin seems to have a lot of functionality, I might have just missed this feature, so if that is the case I apologize. However, if I didn't I would love to see this feature added, for servers that have multiple worlds without bungee. If that's not possible, no worries but I thought I would put in the suggestion/see if I was just missing something.

Thanks!

**Comment by bloodmc** [comment]
Change playerdata `context-storage-type` to `world` in `global.conf`
