### ISSUE TITLE
GriefDefender cancels EntitySpawnEvent

### ISSUE THREAD

**Issue by mfnalex** [bloodmc/GriefDefender#242]
Hi, a user of my AngelChest plugin reported that holograms do not spawn. I hacked a bit into the EventHandler and found out that GriefDefender cancels the EntitySpawnEvent:

```
[18:50:05 INFO]: [EventLogger] ============== EVENT CANCELLED ==============
[18:50:05 INFO]: [EventLogger] Event: CreatureSpawnEvent
[18:50:05 INFO]: [EventLogger] Class: org.bukkit.event.entity.CreatureSpawnEvent
[18:50:05 INFO]: [EventLogger] has been cancelled by
[18:50:05 INFO]: [EventLogger] Plugin: GriefDefender
[18:50:05 INFO]: [EventLogger] Class: com.griefdefender.GDBootstrap
[18:50:05 INFO]: [EventLogger] =============================================
```

This is how AngelChest spawns the armor stand: https://github.com/JEFF-Media-GbR/Spigot-AngelChest/blob/master/src/main/java/de/jeff_media/AngelChest/Hologram.java#L36

Is there any way to prevent GriefDefender from cancelling the EntitySpawnEvent?

**Comment by bloodmc** [comment]
GD does not deny creature spawns by default. The user turned off spawning which is why GD is cancelling the event. The user just needs to run gddebug and allow the id that is spawning.

**Comment by mfnalex** [comment]
Thank you, I will forward that information and then reply again

**Comment by mfnalex** [comment]
https://griefdefender.github.io/debug/?vpR8d69PAj

Quoting the user:
```
This was generated by gddebug, once I got a grip on how to use it better, and according to the GD guys, GD isn't preventing the spawn
```

As you can see in the output above, the event is 100% cancelled by GriefDefender. I am using this detect what plugin has cancelled an event: https://gist.github.com/aadnk/5563794#file-cancellationdetector-java

**Comment by bloodmc** [comment]
The user used a filter with their username so it isn't going to show everything. As I stated before, GD does not turn off `entity-spawn` by default. The user set the flag to false and is now having issues. They need to report it in GD's discord.

**Comment by mfnalex** [comment]
Alright, thanks, I'm going to tell him

**Comment by mfnalex** [comment]
BTW I cannot find a link to your discord anywhere

**Comment by mfnalex** [comment]
Okay, removing either LevelledMobs or GriefDefender solved this. Must be something happening between those two plugins. We got it solved by adding ARMOR_STAND to the blacklisted items of LevelledMobs.
