### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Shiemy** [bloodmc/GriefDefender#243]
hey, just wanted to ask something, you wrote this: 

Note: GriefDefender is free to use but If you require support, purchase it on https://www.spigotmc.org/resources/griefdefender.68900/ to get access to the private discord. 

But i cant find the FREE to use download ^^ it always tell me to Buy it. And i would like to try it first before i buy something.

**Comment by bloodmc** [comment]
Build it on github, I do not offer support on how to build.

**Comment by Brycey92** [comment]
@Shiemy I can try to help you build it. Send me a friend request on Discord, my ID is Brycey92#9215.
