### ISSUE TITLE
dynmap support?

### ISSUE THREAD

**Issue by blueawp** [bloodmc/GriefDefender#247]
Hi I was looking into 3 claim plugin and one of them is GriefDefender and one of the features I would like is dynmap support and I didn't see on the spigot page that you did have dynmap support so I just want to make sure by asking you here and see you do have dynmap support with this plugin.

**Comment by bloodmc** [comment]
Yes support is built-in.

https://github.com/bloodmc/GriefDefender/wiki/Dynmap
