### ISSUE TITLE
[Enchancement] Support vanilla style's selector for commands like /acb

### ISSUE THREAD

**Issue by LemADEC** [bloodmc/GriefDefender#252]
As of GriefDefender 1.4.7 + SpongeForge 1.12.2-2838-7.2.4-RC4066 + luckperms 5.1.85, we can't use selectors with command like /acb. For example, after an event, I want to give 100 claimblocks to all online players, I would like to use `/acb @a 100` without having to cherry pick every players one by one.

**Comment by bloodmc** [comment]
Use `acball` command
