### ISSUE TITLE
Unsupported version MC 1.16.2

### ISSUE THREAD

**Issue by Florianpal1** [bloodmc/GriefDefender#256]
Actually, MC 1.16.2 has not supported by GriefDefender 1.4.7.

![image](https://user-images.githubusercontent.com/36370356/90302294-7a3cda80-dea5-11ea-93b5-d2e0b4f059c1.png)

It's possible to add support for MC 1.16.2 ?

**Comment by bloodmc** [comment]
GD 1.5.0 supports 1.16.2. Premium users get access first.
