### ISSUE TITLE
Error Loading on sponge

### ISSUE THREAD

**Issue by Tripwire117** [bloodmc/GriefDefender#262]
I come across this error while trying to use the sponge plugin. Any insight would be appreciated. 

Forge:1.12.2-14.23.5.2847
Sponge: v.1.12.2-2838-7.2.3
LuckPerms: v.5.1.17

Log: https://pastebin.com/wUr1e6S2

**Comment by Tripwire117** [comment]
Update, Found that another sponge plugin was interfering with this that was dependent on the old GP, this plugin however is only unzipping a library in the plugin/mods folder. No commands are currently active.

**Comment by kencinder** [comment]
Your Luckperms is well outdated and below the requirements for GD, of 5.1.55+

https://luckperms.net/

**Comment by Tripwire117** [comment]
Issue resolved, when I saw min version 5.0 for Luckperms I figured 5.x.xx not 5.1.55xx. Thanks!
