### ISSUE TITLE
Claimsell sign bug

### ISSUE THREAD

**Issue by SnowBlitzz** [bloodmc/GriefDefender#263]
Players are still able to right click the claim selling sign even after it is bought and it'll ask this 
![image](https://user-images.githubusercontent.com/7488382/90882738-063b8e80-e3df-11ea-81f9-3e462cd2daa0.png)
but the confirm button cannot be pressed. This can become confusing to some new players.
When I do /claimsell cancel on a claim that was mine BEFORE but was sold (so it's no longer mine), the message turns into this
![image](https://user-images.githubusercontent.com/7488382/90882816-2e2af200-e3df-11ea-8613-93ec2d23a782.png)

Might be a good idea to change the sign text after it is bought, or even remove the sign? Any other way to prevent this confusion/bug would be neat. 

On 7.2.3 sponge, GD 1.5.0, LP 5.1.93

**Comment by bloodmc** [comment]
This must be an old bug as I can not reproduce this on 1.5.4+
