### ISSUE TITLE
Toggling true/false in ADVANCED makes certain definitions PARTIAL and unable to be toggled.

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#266]
GD 1.5.0 bukkit
Paper 1.16.1 build 135

If you toggle a definition from the PRESET page, things work fine. But as soon as you toggle the value in the ADVANCED tab, other definitions using part of the same contexts no longer are able to be toggled. It appears that it's anything with no target, will affect definitions with the same source, but that have targets.

```
                    player-block-interact {
                        contexts=[
                            "gd_claim_default=user"
                        ]
                        default-value=false
                        description="Controls whether players can interact with blocks.\n&bNote&f: This does not include inventory blocks such as chests."
                        enabled=true
                        permissions=[
                            "flag=interact-block-secondary, source=minecraft:player"
                        ]
```
Change this PRESET to TRUE, go to ADVANCED under CLAIM and set it to FALSE

You will note that on the PRESET tab now, that the `sleep` definition can no longer be toggled.

Will affect any definition that exists that uses `interact-block-secondary, source=minecraft:player` as it also affects a definition viveleroi is using below that I initially tested this with, and only realized the problem was with touching the flag set by `player-block-interact` in ADVANCED.

```
                    barrel-access {
                        contexts=[
                            "gd_claim_default=user"
                        ]
                        default-value=false
                        description="Controls whether a player can access barrel inventories."
                        enabled=true
                        permissions=[
                            "flag=interact-block-secondary, target=minecraft:barrel, source=minecraft:player",
                            "flag=interact-inventory, target=minecraft:barrel, source=minecraft:player"
                        ]
                    }
```

I understand that PARTIAL when you change something in ADVANCED, but not when the contexts are different. There is no target in the `player-block-interact` flag that is set, where there is in the `sleep` and `barrel-access` ones.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/b5b61b8b7a436b14ebd551f495670c2ae8a68d50
