### ISSUE TITLE
/cpp and /cpg non-functional

### ISSUE THREAD

**Issue by reiyooki** [bloodmc/GriefDefender#267]
As of version 1.5.0 /cpg and /cpp do not function. The nodes appear to be set in the GUI when you check the user/group with them, but do not actually do anything.

Workaround: Currently, using command-execute flags does get around this, but is not ideal

**Comment by bloodmc** [comment]
Fixed '/cpp' but '/cpg' appears to work on Paper/Spigot for me. Are you using Sponge?

**Comment by reiyooki** [comment]
Yes sir, SpongeForge 1.12.2-2838-7.2.3

**Comment by reiyooki** [comment]
Updating with notes from discord so they don't get lost:
Original message 1: [Link](https://discordapp.com/channels/594941472621723716/621440759626858501/774191416305909810)
Original message 2: [Link](https://discordapp.com/channels/594941472621723716/621440759626858501/775394589577052170)
> Still having issues with /cpp and /cpg not actually functioning.
> ```
> [GD] Running GriefDefender 1.5.3
> [GD] Running SpongeForge 1.12.2-2838-7.3.0
> [GD] Running luckperms 5.2.26
> ```
> Tested by setting the claim to grant both default group and my specific username a permission which I do not normally have, then removing the permission from myself and leaving/re-entering the claim.
> 
> Permission used: nucleus.globalmute.voice.base
> Result with permission applied to self & not via /cpg or /cpp: Able to use command
> Result without permission applied to self directly: Unable to use command
> 
> The permissions do show up in LP when checked, both on the user and group. I'm guessing the context just isn't being read.
> 
> Screenshot with context visible: https://i.imgur.com/p6TEwKE.png
