### ISSUE TITLE
Feature Request: permission area's

### ISSUE THREAD

**Issue by arkD** [bloodmc/GriefDefender#275]
maybe this is already possible, but I have not been able to figure it out.

I would like a flag that gives users permissions in any claim with that flag.

examples:
limited shop areas (only have permission to create shops in flagged areas)
pvp areas where you can throw fireballs if you have a golden hoe with skript enabled by permission

essentially the context for the permission would be the flag itself.

**Comment by kencinder** [comment]
This is covered by https://github.com/bloodmc/GriefDefender/wiki/Commands#gd-permission-group or the player version below it.

**Comment by arkD** [comment]
This is exactly what I wanted! Sorry, I thought I looked through the documentation pretty well but I guess I missed this.
Apologies!
