### ISSUE TITLE
Wrong permission required for creating 2D subclaims

### ISSUE THREAD

**Issue by Fabrimat** [bloodmc/GriefDefender#277]
![immagine](https://user-images.githubusercontent.com/13642582/92334844-def8e880-f091-11ea-8aad-dcea2c1efff7.png)

**Comment by kencinder** [comment]
The above is an issue, I tested it as well only denying the cuboid permission, and while in 2D mode you get denied. Luckperms verbose shows the cuboid check coming back false, while in 2D mode.

![image](https://user-images.githubusercontent.com/3614897/92437495-725b1800-f17d-11ea-83a3-7a30b38ec018.png)

**Comment by Terran31** [comment]
Players also can't rename basic claims
