### ISSUE TITLE
Subdivision creation not working

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#278]
Paper 1.16.1 b138
GD 1.5.1 DEV1
LP 5.1.106

Only .user.* + .admin.* permissions in use on clean test server.

Can't create subdivisions in admin claims or basic claims, get the following permission error along with a message about claiming mode that doesn't even belong(I didn't switch 2d/3d mode...says claiming sub in 3d, but am in 2d).

![image](https://user-images.githubusercontent.com/3614897/92432896-e55e9180-f171-11ea-85b6-b98ef66fe08e.png)

I think this might also be the reason behind #277 as they're just not working at all...

**Comment by bloodmc** [comment]
What does LP verbose show? I'll fix this issue this week.

**Comment by kencinder** [comment]
Sorry this is the same as #277 small derp on my part thinking it was different, closing.
