### ISSUE TITLE
[Bypass] Industrial Foregoing, Block Breaker

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#28]
Version: griefdefender-1.1.0-TEST13-DEBUG3
Placing the blockbreaker at the edge of a claim and powering it with RF will bypass and break the claimed block.

**Comment by kencinder** [comment]
Cannot reproduce either on 1.2.2 TEST4 using spongeforge-1.12.2-2838-7.1.8-RC3961
