### ISSUE TITLE
Flowing water causes immense GD lag

### ISSUE THREAD

**Issue by 02Miki** [bloodmc/GriefDefender#281]
A player of mine, decided to create a sort of waterfall:
https://i.imgur.com/uCPVTkI.png
The server started to lag like crazy, just look at this timings report:
https://timings.aikar.co/?id=ac5fe943fe80446a9ef36eb5f8d82236
And GDDebug gets spammed a lot by:
https://i.imgur.com/SB8unOP.png

The server ended up with 0.4 TPS, and got fixed only after removing that falling water. Please lmk if you need more info

**Comment by bloodmc** [comment]
This is a sponge issue as every block change is being processed. Update to latest Sponge to see if it resolves.
