### ISSUE TITLE
[Suggestion] Option to stack griefdefender.bonus-blocks from inherited groups

### ISSUE THREAD

**Issue by Sir-Will** [bloodmc/GriefDefender#282]
Would be great to have an option to allow the stacking of `griefdefender.bonus-blocks` from all inherited groups instead of the highest value being used.

**Comment by kencinder** [comment]
I'd have to imagine this is a limitation of Luckperms, but the wiki also clearly states that option is not to be set on a group, it's a playerdata option.

**Comment by Sir-Will** [comment]
If the luckperms api is being used, which the plugin already does, then there is no limitation.

If initial-blocks stacks then that's fine too.

**Comment by bloodmc** [comment]
As @kencinder already mentioned, you are not supposed to be using `griefdefender.bonus-blocks` for groups as the value is dynamic and changes based on player usage. The `griefdefender.initial-blocks` is a static amount which GD does not update. As for stacking, this could be done.
