### ISSUE TITLE
user default-claim-flags block-spread always true

### ISSUE THREAD

**Issue by WR8187** [bloodmc/GriefDefender#283]
when I set block-spread=false in default-claim-flags{ user { block-spread is still true

if I setup a custom flag definition with default false it is also true.. if I toggle it true then false then it is false. other flags (block-break) in same definition take the default as it should

**Comment by WR8187** [comment]
also If I use override I can force it but then it can't be toggled off

**Comment by WR8187** [comment]
`https://github.com/bloodmc/GriefDefender/wiki/Flag-Definitions-GUI`

`fire-spread {
    contexts=[
        "gd_claim_override=claim",
        "gd_claim_default=global"
    ]
    default-value=false
    description="Controls whether fire can spread."
    enabled=true
    permissions=[
        "flag=block-spread, source=minecraft:fire"
    ]
}`

it works if you toggle it on and then off again just doesn't apply the default setting..

**Comment by bloodmc** [comment]
This is working as intended. The `gd_claim_override=claim` is designed for owners to toggle on/off flags that should affect them. If you want to force fire-spread off for all users including owners then you should use `gd_claim_override=user`. 
Read the contexts wiki page for more information here https://github.com/bloodmc/GriefDefender/wiki/Contexts which explains how it works in detail.
