### ISSUE TITLE
[Suggestion] Confirmation for purchase of townclaim

### ISSUE THREAD

**Issue by Baktus79** [bloodmc/GriefDefender#287]
It is possible to set a cost for creating a town claim, and it works very well. But what I miss is a way to be able to activate confirmation. There are several players who make a town claim by accident, and notice that they lack money.

Is it possible to add an option so that we can activate confirmation before the town claim is created? If the player writes for example `/townaccept`, or possibly click on a text in the chat to confirm.

---

**An example that could be used in the configuration file**
```yaml
town {
    auto-nature-restore=false
    cleanup-task-interval=5
    creation-cost=80000.0
    confirmation=true
}
```

**Comment by bloodmc** [comment]
Sounds reasonable to just get this added by default. I'll make sure to do it for next release.

**Comment by bloodmc** [comment]
So I just got around to looking at this again and this is already supported for economy mode servers. If you are not using economy mode then that is your issue. However, if you are planning on converting to economy mode then make sure you clone your production server to test and use `/gdblocktransfer` to transfer ALL player accrued/bonus claimblocks into currency for economy mode use.
