### ISSUE TITLE
Spawn Admin Claim

### ISSUE THREAD

**Issue by FraserTheNerd** [bloodmc/GriefDefender#288]
I started a new world in StoneBlock 2. GD made a admin claim at spawn, I have opped myself and gave myself griefdefender.admin.* and griefdefender.user.* but I cant edit the spawn claim, cant break blocks or do anything even with perms.

Then I deleted all admin claims and it made spawn wilderness, same thing I cant break any blocks or anything.

**Comment by kencinder** [comment]
GD doesn't make a claim at spawn, all unclaimed area is wilderness, which yes is a claim type and EVERYTHING is allowed by default even without any permissions.
You have changed flags/flag defaults or set your permissions up incorrectly.
