### ISSUE TITLE
[Bypass] OpenBlocks, Block Breaker

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#29]
Version: griefdefender-1.1.0-TEST13-DEBUG3
Placing a OpenBlocks Block Breaker on the edge of a claim and powering it with redstone will allow blocks in the claim to be broken
Also errors when this is performed
https://gist.github.com/clienthax/04e1836d64b2d6295c0f1a62a92938e4

**Comment by bloodmc** [comment]
Create new ticket if this issue persists with latest SpongeForge and is caused by GD
