### ISSUE TITLE
[Question] Is Worldguard needed to protect the "wilderness" from harm to fire etc

### ISSUE THREAD

**Issue by Scorpionvssub** [bloodmc/GriefDefender#292]
Title says it basically

Can i use GD only  to have it protect the global world while allowing a player next to full control over their own piece of land as otherwise wg may override their attempt too

if so, which flag sections should be altered because its very confusing

**Comment by DrWurzeli** [comment]
GDs wilderness is a fully fledged claim where you can enable and disable whatever you want. there is no need for WG if you have GD installed, unless you want poly regions.

not sure what you mean by "can I use GD only to have it protect global" how would peopel claim their own land then?

**Comment by Scorpionvssub** [comment]
well you basically answered that, i'd still use wg for spawn etc, but i dont need to tell it to stop fire spread etc thanks
