### ISSUE TITLE
Using issue

### ISSUE THREAD

**Issue by AngelRed** [bloodmc/GriefDefender#293]
I just can't use it on my server, i mean, it load in the server, config files etc.. But when i'm trying to use any of his feature, and error come and i can't use any of its feature
My server run on SpongeForge, 7.3.0 and forge 14.23.5.2838 on minecraft 1.12.2
It produce the error when i'm entering a command or when i'm right clicking with the golden shovel / stick

Here the logs : https://pastebin.com/KKYDsWZi

Regards, Polstrong

**Comment by bloodmc** [comment]
griefdefender-sponge-1.2.4-B15.jar

Completely outdated build.
