### ISSUE TITLE
All "Clickable" Chat Messages do not function at all when McMMo is installed

### ISSUE THREAD

**Issue by adamromulus** [bloodmc/GriefDefender#294]
I installed McMMo last night, and got lots of complaints from my players today. 

I learned all "Clickable" Chat Messages do not function at all when McMMo is installed
Nobody could abandon their claims or set flags, because they're all clickable. 

I removed McMMo and everything all went back to normal. 

Why McMmo does this, I'm really not sure.
Maybe the issue is on their end?

**Comment by adamromulus** [comment]
^ running latest griefdefender and mcmmo 2.1.149

**Comment by bloodmc** [comment]
Strange...You can use the `/gdconfirm` command for the time being.

**Comment by PiggiesGoSqueal** [comment]
Has this been fixed? I'd like to know before I buy the plugin. Thanks.

**Comment by adamromulus** [comment]
> Has this been fixed? I'd like to know before I buy the plugin. Thanks.

A new update for mcmmo came out after I posted this, it resolved it for me!
