### ISSUE TITLE
Issue with Nucleus on Sponge

### ISSUE THREAD

**Issue by trushoff** [bloodmc/GriefDefender#296]
Latest Sponge, Nucleus and GD
https://hasteb.in/ubeperul.css

**Comment by color-space** [comment]
The Hastebin possibly expired?
It's not available

**Comment by kencinder** [comment]
This is due to something with Nucleus v2, I don't recall what the compat stuff was in Nucleus v1, but likely it's API has changed and GD only has support for Nucleus v1 at the moment.
