### ISSUE TITLE
[Bypass] Botania, Shard of Laputa

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#30]
Version: griefdefender-1.1.0-TEST13-DEBUG3
Using the Shard of Laputa inside/outside of a claim will effect blocks on the inside.

![image](https://user-images.githubusercontent.com/1056270/62558033-1cc48580-b870-11e9-8982-46941f1f3394.png)

https://github.com/Vazkii/Botania/blob/483a816616d86f5ff36e1fc150afa1527042efce/src/main/java/vazkii/botania/common/item/ItemLaputaShard.java

**Comment by clienthax** [comment]
Fixed on griefdefender-1.2.2-TEST1
Yet the effect will carry on forever.. (Likely botania side issue)

**Comment by Brycey92** [comment]
Does "forever" persist across server restarts in this case?
