### ISSUE TITLE
[Request] Bluemap support for claims

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#302]
We have dynmap support, Bluemap support would be nice to have.

I'm no longer using dynmap, and Bluemap use is growing quickly(At least judging by the number of users amassing in Blue's discord), plus it also supports Spongevanilla...something dynmap does not.

https://github.com/BlueMap-Minecraft/BlueMapAPI

**Comment by austin4195** [comment]
Would love to see support for this as well!

**Comment by bloodmc** [comment]
Bluemap integration is now available in latest GriefDefender development build on discord.

**Comment by bloodmc** [comment]
Added to GDHooks
https://github.com/bloodmc/GDHooks
