### ISSUE TITLE
Failing on startup

### ISSUE THREAD

**Issue by SlimeCody** [bloodmc/GriefDefender#305]
![image](https://user-images.githubusercontent.com/49579480/98843444-9b638780-2410-11eb-97ea-d102cff78732.png)

**Comment by kencinder** [comment]
Did you update GD from a considerably older version? If so you'll likely need to update libraries. Delete `plugins/GriefDefender/lib` and let it download libs again.

**Comment by bloodmc** [comment]
Unable to reproduce.
