### ISSUE TITLE
Players unable to retrieve their grave on others claims

### ISSUE THREAD

**Issue by Zoneman1972** [bloodmc/GriefDefender#307]
Hi there,
I'm running a Sevtech Ages server and was previously using GriefPrevention and upgraded to GriefDefender after learning about it.

I've run into an issue where players can no longer collect their grave (Tombstone-4.0.0-1.12.2) if they happen to die on another players claim.

GriefPrevention used to allow this to happen if the player just crouched over their grave but GriefDefender wont allow it at all.

Is there something you can add to the config to allow a "bypass" so that players can access their graves without an Admin having to give them temporary claim trust?

Thanks for your time.

**Comment by bloodmc** [comment]
There is no need for a config to bypass this as you have full control of your protection. Unlike GP, GD hooks into contexts completely. Use https://github.com/bloodmc/GriefDefender/wiki/Debugging and add the source/target as an override globally.  Read https://github.com/bloodmc/GriefDefender/wiki/Contexts if you are unsure how contexts work.
