### ISSUE TITLE
[Bypass] Twilight Forest, Cube of Annihilation

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#31]
Version: griefdefender-1.1.0-TEST13-DEBUG3
Throwing a cube of annihilation into a claim (use it facing the claim) will carve blocks out of the claim

![image](https://user-images.githubusercontent.com/1056270/62558433-efc4a280-b870-11e9-9344-7e1db7e4589e.png)

https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/item/ItemTFCubeOfAnnihilation.java

**Comment by kencinder** [comment]
Just noting that I tested this on 1.2.2 TEST4, could not reproduce.
