### ISSUE TITLE
Enderman block-place

### ISSUE THREAD

**Issue by WR8187** [bloodmc/GriefDefender#310]
enderman can place blocks inside of claims
used gddebug and no event flags listed for them placing blocks

tested on spigot and paper

**Comment by bloodmc** [comment]
Provide exact versions and link to gddebug with no filter.

**Comment by WR8187** [comment]
git-Paper-282 (MC: 1.16.4)
GD 1.5.4-DEV4
[gddebug](https://griefdefender.github.io/debug/?86U9PdOf32)

the enderman can place a block inside of the claim that it picked up from outside the claim
block-break for grass_block its it picking up the block doesn't show any block-place when it puts it down
