### ISSUE TITLE
claim bypass/block interaction on 1.12.2

### ISSUE THREAD

**Issue by LUEshi42** [bloodmc/GriefDefender#314]
GD : 1.5.3 DEV
LuckPerms : 5.2.39

Not sure if this might be related to the particular mod of this block

in a claim of my own:
1.enable cfdebug
2. right click extra utils 2 screen, no gui access, works as intented.
https://i.imgur.com/wo5EqO8.png

Now the bypass.
1. with cfdebug still on, enable claim mode
2. right click block to interact.

I tried it in someone's elses claim without cfdebug and was able to interact with a block. you can interact with the block while in claim mode.

https://i.imgur.com/IpPjI9p.png

Excellent plugin, just wanted to report this.

**Comment by LUEshi42** [comment]
Mods.BlockIdsRequiringAccessTrust: [1, 2, 3]

Any block IDs you list here will require /accesstrust from the owner before a player can interact with them (usually right click). I've heard several mods introduce some kind of "machines" which you can activate by right clicking them. Those would be good candidates for adding here.

(from the gd wiki)

apparently this isn't an issue. Thank you for the hard work.

**Comment by bloodmc** [comment]
Unable to reproduce. Make sure you read https://github.com/bloodmc/GriefDefender/wiki/Permissions carefully
