### ISSUE TITLE
hello how can i enable config for each worlds ?

### ISSUE THREAD

**Issue by RastaJax** [bloodmc/GriefDefender#315]
https://gyazo.com/8e41c0392585b662258e8b3fff3713a4

but i dont know where to past it ?? 

everytime i edit world.conf for my world it just disappear 
https://gyazo.com/e3811d536727fb83f3c9db32e486bd69

**Comment by RastaJax** [comment]
even when i edit it when my server is OFF, when i restart then everything dissapear

**Comment by bloodmc** [comment]
Ancient builds are not supported. If you need support, buy the plugin.
