### ISSUE TITLE
Massive TPS loss over oceans (timings report says GD is partly at fault)

### ISSUE THREAD

**Issue by wolftheninja** [bloodmc/GriefDefender#316]
https://timings.aikar.co/?id=cce087784ef64762b2a5af336e240614#timings

GD is showing up at 35% of all the ticks on creaturespawnevent I really dont know whats happening but it seems fish arent spawning. I really need help on this one.

**Comment by wolftheninja** [comment]
here is the timings not over ocean 

https://timings.aikar.co/?id=3ddb643f2622479ab6e85f2e6e704582

**Comment by wolftheninja** [comment]
tested removing plugings one at a time to find the problem and removing GD solves my issue with tps loss and fish start spawning again. I can't get an error to come up so the only lead I have is the timing reports

**Comment by bloodmc** [comment]
You are using outdated build 1.5.2, latest 1.5.4 build does not have any performance issues on Paper. Servers are running with 100+ players with no issues.
