### ISSUE TITLE
[Dupe] Botania, Mana Lens Force

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#32]
Version: griefdefender-1.1.0-TEST13-DEBUG3

The following setup on the edge of a claim will duplicate the block the pulse hits, instead of pushing it / nothing.

![image](https://user-images.githubusercontent.com/1056270/62565724-5650bd00-b87f-11e9-9601-aa67c1c13a46.png)

![image](https://user-images.githubusercontent.com/1056270/62565730-5c469e00-b87f-11e9-9a10-e6eaf462678b.png)

https://github.com/Vazkii/Botania/blob/fb8ebd8ca7e4dd24a1c93bf2a92ea4f93fee98fe/src/main/java/vazkii/botania/common/item/lens/LensPiston.java#L26

**Comment by bloodmc** [comment]
Create new ticket if this issue persists with latest SpongeForge and is caused by GD
