### ISSUE TITLE
[Question] Does the plugin allow admin & player shop plugin usage?

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [bloodmc/GriefDefender#322]
I remember reading a review about the plugin not supporting shops but the review wasn't very clear as to what they were referring to.

To confirm, does this plugin allow using admin & player shops? For example, EssentialsX admin [Buy], [Sell], [Repair], etc signs. Or ChestShop signs within a GriefDefender claim. Etc. Do those all work without GriefDefender sending messages like "You cannot interact here" or preventing the action?

Thanks!

**Comment by bloodmc** [comment]
Any interaction blocked by GriefDefender can be altered by an admin.

Please refrain from creating tickets on github about questions. Github issues are reserved for actual issues. It is open source so you can test yourself and figure out if it fits your needs. Just build the jar and test.
