### ISSUE TITLE
[BUG] Chunk error

### ISSUE THREAD

**Issue by GTBelo** [bloodmc/GriefDefender#323]
- **Versions**
Spigot/Paper/Sponge:  1.12.2
GriefDefender:  Most actual
LuckPerms:  Most actual

- **Describe the bug**

Chunk error

- **Steps to reproduce the behavior**

Start Grief Defender and wait 

- **Expected behavior**

This error has flood my console

- **GDDEBUG**

https://griefdefender.github.io/debug/?I4RPO6grpn

- **Screenshots**

PasteeBin: 

https://pastebin.com/KSUUqn68

**Comment by bloodmc** [comment]
Dupe #319 

This was already fixed. If you want the fix then you need to build GD from github or wait for another release.

**Comment by GTBelo** [comment]
Hello, I paid for this plugin. For the love of God! I want a bug fix without having to compile a Jar ...
