### ISSUE TITLE
[BUG] Can't create claim from WE selection using `/gd claim we` on SpongeForge

### ISSUE THREAD

**Issue by WGOS** [bloodmc/GriefDefender#324]
- **Versions**
Sponge: SpongeForge 1.12.2-2838-7.3.0 (latest recommended)
GriefDefender: 1.5.5-DEV
LuckPerms: 5.2.45
WorldEdit: Forge 6.1.10 as well as Sponge 6.1.10-SNAPSHOT

- **Describe the bug**
Can't create claim from WorldEdit selection using `/gd claim we` command. It can't be done whether in 2D or 3D mode.  
Admin claims, user claims are not working as well. Executing the command just outputs list of available commands to chat.
**Claiming using `/claimwe` works fine**

- **Steps to reproduce the behavior**
 1. Make a selection via WorldEdit
 2. Execute `/gd claim we`

- **Expected behavior**
Executing `/gd claim we` should claim selected region

- **GDDEBUG**
https://griefdefender.github.io/debug/?956CmLD6X0

**Comment by kencinder** [comment]
That's because the command you are using is not correct, it is `/gd claim worldedit we` which I'm thinking was intended to be use of `worldedit` OR `we` as an alias, but nonetheless the actual function does work correctly, just tested on my server.

**Comment by kencinder** [comment]
Actually I'm going to reopen this, as that is exactly what should be happening as per the source, but is not. For some reason it's not using either/or but requiring both.

https://github.com/bloodmc/GriefDefender/blob/557f09a4dece921e7bf54f83c06e12fb785bc393/sponge/src/main/java/com/griefdefender/command/CommandClaimWorldEdit.java#L43
