### ISSUE TITLE
flag permissions issues

### ISSUE THREAD

**Issue by pyscho974** [bloodmc/GriefDefender#327]
Nucleus-1.14.7-S7.1-MC1.12.2-plugin /  LuckPerms-Sponge-5.2.53 /  griefdefender-sponge-1.2.4-B15 /  spongeforge-1.12.2-2838-7.3.0

MC eternal mod pack 1.3.7.1 .. updated minecolonies mod to its last version for mc 1.12 (minecolonies-1.12.2-0.11.841-ALPHA-universal)

i seem to be unable to use flags either by in game commands or the gui from clicking claim with a stick
thought i had altered the config file some how.. so deleted it and generated a new one with no change

its giving me the response of "you do not have permission to use this command"

i used verbose with luckperms and keeps showing the flag syntax check as failed or unidentified.

so i am wondering if maybe i got the permission node entered wrong or if its actually broke

seems permissions in wiki seems might be missing one or something.. griefdefender.user.* allows the flags to work but to set each node without the * seems broken

**Comment by bloodmc** [comment]
griefdefender-sponge-1.2.4-B15 is a very old build and not supported.

**Comment by pyscho974** [comment]
been looking for updates to it.. but the discord link that was the last one posted. oddly not seen a link in this github for latest version .. im probably over looking it tho

**Comment by pyscho974** [comment]
seems im on old discord not the private one.. guessing im unable to get update from what im sifting threw so far.
