### ISSUE TITLE
[BUG] IC2 Mining Laser ingore Protection.

### ISSUE THREAD

**Issue by KevinChang0916** [bloodmc/GriefDefender#329]
- **Versions**
Spigot/Paper/Sponge: Magma-50f320e-server
GriefDefender: GriefDefender-bukkit-1.5.4
LuckPerms: LuckPerms-Bukkit-5.2.44
Industrial Craft 2: 2.8.221-ex112
Forge: 14.23.5.2854

- **Describe the bug**
Mining laser's explosive mode, can bypass GriefDefender Protection.

- **Steps to reproduce the behavior**
Editing Mining laser's mode to explosive mode, right-click by the Mining laser.
can destory claimed territory.

- **Expected behavior**
Please fix this bug
I also submitted it to Isuse for industrial craft 2

- **GDDEBUG**
Can't log to debug

**Comment by DrWurzeli** [comment]
We need a valid debug log to see what the mod is actually doing or if it doesnt show up at all.
Also: Try reproducing that on SpongeForge with only Sponge, GD, LP and the mod installed as hybrid bukkit/forge servers are really hard to fix since they will almost never work correctly.

**Comment by KevinChang0916** [comment]
https://griefdefender.github.io/debug/?YsElR8th2Q
**In the wildness**
toward claimed area use mining laser's explosive mode, can break any player's claimed area.
(Sorry, My english so bad)

**Comment by bloodmc** [comment]
Mohist/Magma's problem. SpongeForge works since there is a built-in tracker to capture any block changes in a world.

**Comment by bloodmc** [comment]
Reopening as I see explosions are only the issue. Normal mode of laser works fine.

**Comment by bloodmc** [comment]
OK, confirmed IC2 fires a custom explosion event. So its up to Mohist/Magma or you to patch IC2 to fire a proper event.
