### ISSUE TITLE
[Bug]The plugin failed to load properly.

### ISSUE THREAD

**Issue by CJYKK** [bloodmc/GriefDefender#332]
- **Versions**
Spigot/Paper/Sponge: Sponge
Sponge version: Spongevanilla-1.12.2-7.3.0
GriefDefender: griefprevention-1.12.2-4.3.0.692
LuckPerms: LuckPerms-Sponge-5.2.54

- **Describe the bug**

This plugin cannot be loaded and used properly.

- **Steps to reproduce the behavior**

1.Put the plug-in in the mods folder.
2.Start the server.
3.The plugin reported an error.

- **Expected behavior**

The plugin is loaded normally and can be used.

- **GDDEBUG**

- **Screenshots**

![屏幕截图(1888)](https://user-images.githubusercontent.com/59359590/102076812-48cc1f80-3e43-11eb-9b43-1d6942bba28c.png)
![屏幕截图(1889)](https://user-images.githubusercontent.com/59359590/102076819-4b2e7980-3e43-11eb-8bd6-140656bcde48.png)

**Comment by DrWurzeli** [comment]
This is not a GriefPrevention GitHub.
