### ISSUE TITLE
[BUG] Player block dig

### ISSUE THREAD

**Issue by GTBelo** [bloodmc/GriefDefender#333]
- **Versions**
Spigot/Paper/Sponge:  1.12.2
GriefDefender: 
LuckPerms: 

- **Describe the bug**

Lag!

- **Steps to reproduce the behavior**

Start a server and mining with 40 players

- **Expected behavior**

My server is lagging absurdly and apparently the biggest cause is Grief Defender. Look:

https://timings.aikar.co/?id=5cf2689cdcc34bcca5827b88e8d72df8

GriefDefender :: Event: c.g.l.PlayerEventHandler (PlayerInteractEvent) count (216288) total (2.70% 41.673s, 4.06% of tick) avg (0.19ms per - 2.03ms / 10.54 per tick

- **GDDEBUG**

https://griefdefender.github.io/debug/?JexzOAnwWn

- **Screenshots**
Console error:

https://pastebin.com/n5jZrmdt

**Comment by GTBelo** [comment]
Luckyperms version: most recent
GriefDefender version: griefdefender-1.5.5-DEV.jar (Submitted by the plugin developer via discord)

**Comment by DrWurzeli** [comment]
Did you try with DEV1a bloodshot send you?

**Comment by GTBelo** [comment]
Yes, Now this error floods my console:

https://pastebin.com/zhXEHt7u
