### ISSUE TITLE
[BUG]Type is invalid

### ISSUE THREAD

**Issue by martin1194** [bloodmc/GriefDefender#337]
Plugin: GriefDefender 1.5.4
Server: Magma-9e0b1b1 / mohist-1.12.2-148
MC: 1.12.2
MOD: industrialcraft-2-2.8.221-ex112.jar

Type is invalid
But it should be "batch_crafter"

https://griefdefender.github.io/debug/?1Tb25kLWb2

![image](https://user-images.githubusercontent.com/18354205/102668695-e1f68f80-41cf-11eb-8279-db8d40a8bba5.png)

**Comment by bloodmc** [comment]
Dupe #335
