### ISSUE TITLE
[REQUEST] No protections while claim owners are online

### ISSUE THREAD

**Issue by SekiAlpha** [bloodmc/GriefDefender#338]
- **Feature information**

I'd like to be able to have a system in place that allows other players to raid claims if the owners of that claim are online, but only if they're online. I don't know if this plugin has this feature and I don't really know where I could find it, I'm also looking to implement this on the sponge version of this plugin. However, I don't know if the sponge version is on parity with the spigot version. Essentially the protection only works if the players of a certain claim are offline.

Maybe there could be an option for two different types of protections in place? Offline protection and online protection.

- **Other plugins or mods related to the request**

- **Additional context**

**Comment by bloodmc** [comment]
Create a flag definition for online/offline protection and use https://github.com/bloodmc/GriefDefenderAPI/blob/master/src/main/java/com/griefdefender/api/permission/PermissionManager.java#L250

If the owner goes offline, set your offline flag definition and if the owner comes online set your online flag definition on the claim(s).

**Comment by SekiAlpha** [comment]
So to implement this I would have to code a plugin that hooks into the API?
