### ISSUE TITLE
[Bypass] Sticky piston + Slime block

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#34]
Version: griefdefender-1.1.0-TEST13-DEBUG3

Have piston extended like so
Place slime block between extended piston and diamond block, retract piston,
Note: If you put the slime block on the unextended piston, it will not allow you to extend it into the claim.
![image](https://user-images.githubusercontent.com/1056270/62567184-96fe0580-b882-11e9-82d6-54950639cf2e.png)

Also, if you place the slimeblocks like this, it will not prevent you from pushing them into the claim, like it does for a single block.
![image](https://user-images.githubusercontent.com/1056270/62568459-1db3e200-b885-11e9-9664-82df4fb1ce93.png)

**Comment by kencinder** [comment]
Cannot reproduce either on 1.2.2 TEST4 using spongeforge-1.12.2-2838-7.1.8-RC3961
