### ISSUE TITLE
[REQUEST] Reference a region by name (and id)

### ISSUE THREAD

**Issue by AgentSanchez** [bloodmc/GriefDefender#340]
Good afternoon. I'd like to request a features similar to that of WorldGuard. Where you can select a region by a command and it is automatically set as a WE/WG selection. In this fashion things in a claim can be modified via WE. Currently the selection system `/gd claim we`  but this requires standing in the region. I'd like this command to be able to be used without having to stand in a region and for it to be able to select by referencing a claim's given name, or a claim's id (possibly /gdselect <name|id> <name or id>. The purpose is so that this command could be run from console, or with automated tools that use the console, such as CommandUtils, or CommandSigns or any spigot/sponge variants. If I have time I will look into making a PR, but I wanted to offer this suggestion as a seemingly helpful tool that could improve the use-case for GD. 

https://dev.bukkit.org/projects/worldguard

**Comment by bloodmc** [comment]
So the `/gd claim we` command on its own is designed to simply create a claim with your WE selection.

Would you be able to list a few specific scenarios of how you would make use of a `/gdselect` command. I assume you want the ability to select a claim via command then use other claim commands to modify your select such as `/claimexpand` and `/claimcontract`

**Comment by bloodmc** [comment]
OK as discussed on discord, the requirement is to turn a claim's area/volume into a WE selection. This can definitely be done.

**Comment by bloodmc** [comment]
This has been implemented and will be released with GD 1.6.0

**Comment by AgentSanchez** [comment]
Awesome sauce! Above and beyond.

**Comment by bloodmc** [comment]
GD 1.6.0 is still not released so I'll keep this opened until it is.

**Comment by bloodmc** [comment]
This is now part of GD 2.0 via `/claimid <identifier>`. You can also access this identifier via GD's API.
