### ISSUE TITLE
[REQUEST] Request the function to stop accessor using "interact-item-secondary"

### ISSUE THREAD

**Issue by martin1194** [bloodmc/GriefDefender#341]
version: griefdefender-bukkit-1.5.4
flag: interact-item-secondary

accessor can use an item in a claim.
I can't stop it in any flag.

In this case, he using "ic2:treetap"
https://griefdefender.github.io/debug/?ytAUEbDQGy

**Comment by bloodmc** [comment]
Accessor trust is designed for block usage not items. You cannot stop it with flag since you are using trust which overrides flag. Stop using trust and start using Flag Definitions if you want more granular permissions.

https://github.com/bloodmc/GriefDefender/wiki/Flag-Definitions-GUI
