### ISSUE TITLE
[BUG]ERROR java.lang.reflect.InvocationTargetException in1.5.5-DEV6

### ISSUE THREAD

**Issue by martin1194** [bloodmc/GriefDefender#342]
griefdefender-bukkit-1.5.5-DEV6

When I try to open advanced flags. It show error in cmd.
![image](https://user-images.githubusercontent.com/18354205/103137767-5b7e0880-470f-11eb-8dd7-eb00e95cd924.png)
![image](https://user-images.githubusercontent.com/18354205/103137796-9aac5980-470f-11eb-8916-0214e82c3ba7.png)

**Comment by bloodmc** [comment]
Upload the server log to pastebin or another paste site.

**Comment by martin1194** [comment]
I know what wrong. I try to translate inside en_US.conf. But it seems can't work. This is my own problem. So I will close this issue
