### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MAtrixoDemos** [bloodmc/GriefDefender#343]
- **Versions**
Spigot/Paper/Sponge: spongeforge-1.12.2-2838-7.3.0.
GriefDefender: griefdefender-sponge-1.5.4.
LuckPerms: LuckPerms-Sponge-5.1.17.

- **Describe the bug**
Lo puse en la carpeta de mods y cuando inicié mi servidor, me indica error con luckperms, el servidor no me detectó el plugin.

- **Expected behavior**
I had already worked with a plugin very similar to this one that is free, I expected something similar

- **GDDEBUG**
 com.griefdefender.provider.LuckPermsProvider.<clinit>(LuckPermsProvider.java:111)                                     com.griefdefender.GriefDefenderPlugin.onPreInit(GriefDefenderPlugin.java:577)

- **Screenshots**
![image](https://user-images.githubusercontent.com/76597163/103140891-d7496800-46b1-11eb-86f0-2fbc3db104ca.png)

**Comment by bloodmc** [comment]
You are using ancient LuckPerms build. Update to latest on https://luckperms.net
