### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by koyere** [bloodmc/GriefDefender#345]
- **Versions**
Spigot/Paper/Sponge: Paper 1.16.1 #133
GriefDefender: 1.5.4
LuckPerms: v5.2.45

- **Describe the bug**

I have simply put it in the folder I have activated the server and it has given me the attached errors, I have not touched anything or configured and when I use a command it tells me that it does not exist.

- **Steps to reproduce the behavior**

- **Expected behavior**

That will work well

- **GDDEBUG**

- **Screenshots**

https://pastebin.com/fq14PXyp

**Comment by bloodmc** [comment]
Another plugin is probably interfering. Test with only GD/LP/Paper.

**Comment by koyere** [comment]
> 
> 
> Another plugin is probably interfering. Test with only GD/LP/Paper.

I have done it again, only with those plugins and I get the same, the same error. I did it on a local machine.

https://pastebin.com/1hLNX0Eh

**Comment by bloodmc** [comment]
Upload the complete server log.
