### ISSUE TITLE
Claim Borders not appearing

### ISSUE THREAD

**Issue by 1stdrsilver** [bloodmc/GriefDefender#350]
When establishing or attempting to resize a border of an existing claims, border blocks that establish the boundaries of a user's claims are not appearing at all. Regardless of whether Admin, User, Subdivision or Border claims are being used, no blocks appears.

**Comment by bloodmc** [comment]
No one on discord is having this issue with any version so definitely something on your end. Make sure you are using latest.

**Comment by 1stdrsilver** [comment]
I am using the latest, I have installed the latest GriefDefender on my end and just reinstalled it, no config files have been altered and no plug-ins conflict, I am using the latest Sponge and Nucleus that are supported by Pixelmon.
