### ISSUE TITLE
Claim Borders still not appearing with newest version.

### ISSUE THREAD

**Issue by 1stdrsilver** [bloodmc/GriefDefender#351]
Newest version of GriefDefender and up to date versions of Sponge and Nucleus, and latest version of Pixelmon Generations.

Claim Borders will not visually appear no matter what action is taken, whether its investigating with the stick or shovel, creating the claim or attempting to resize the claim.

**Comment by bloodmc** [comment]
No pixelmon servers are experiencing this issue on GD discord. As this is an `issue tracker` , if you require support then buy the plugin.
