### ISSUE TITLE
[BUG]zh_HK /claimflag does not display true/false toggle 

### ISSUE THREAD

**Issue by hkkongou** [bloodmc/GriefDefender#353]
yes, 1.5.5

- **Versions**
Spigot/Paper/Sponge: tuinity 1.16.3 576e2cc / paper 1.16.3 #253
GriefDefender: 1.5.5
LuckPerms: 5.2.3.2

- **Describe the bug**

zh_HK does not display the true/false setting in /claimflag
![image](https://user-images.githubusercontent.com/61608872/103357422-1cc0c780-4aee-11eb-8c7f-dc04a8ac0451.png)

- **Steps to reproduce the behavior**

use /claimflag

- **Expected behavior**

show up claimflag true false setting so that players/users can toggle the setting by clicking

- **GDDEBUG**

- **Screenshots**

**Comment by bloodmc** [comment]
You need to delete Lang folder so it regenerates.
