### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Thornbush42** [bloodmc/GriefDefender#354]
Using latest LuckPerms and GriefDefender as of writing this post.
Paper: #352
GriefDefender: 1.5.5
LuckPerms: 5.2.67

- **Describe the bug**
Console error spam, possibly related to the fact people can damage entities not in their own claim / in claims they do not have perms to do so (e.g. destroying item frames)

- **Steps to reproduce the behavior**
Go to a claim you have no perms to do anything in, then fire an arrow at the item frame, and watch as it destroys the item frame despite not having perms.

- **Expected behavior**
Item frame should remain intact

- **GDDEBUG**
Exact error posted (no error is shown above this line so screenshot wouldn't show any more info):
TIMING_STACK_CORRUPTION - Report this to the plugin GriefDefender (Look for errors above this in the logs) (TimingIdentifier{id=GriefDefender:onEntityDamage} did not stopTiming)

**Comment by bloodmc** [comment]
This was already fixed. If you have 1.5.4 then you should have access to discord .
