### ISSUE TITLE
[REQUEST] Record debug log a whole time and save as .log

### ISSUE THREAD

**Issue by martin1194** [bloodmc/GriefDefender#355]
Is there any improvement to record the debug log and autosave it as a .log document the whole time?

There are only Core Protect can work with 1.12.2 and make a record. But it very sucks in forge.

If you make this function as a new plugin and need to buy. I will buy it too. Cuz there is no logging plugin that can be working with forge+bukkit in 1.12.2

**Comment by bloodmc** [comment]
No, GriefDefender is not an audit plugin.
