### ISSUE TITLE
[BUG] Placing LittleTiles is ignoring protected area

### ISSUE THREAD

**Issue by CreativeMD** [bloodmc/GriefDefender#358]
Hey,

It's still possible to place new tiles in a protected area. (Breaking or changing the tiles is protected properly). 

Somebody has reported this issue to me and I have no idea why this isn't working. Some plugins work perfectly fine others don't. I fire a MultiPlaceEvent before placing ([source](https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/util/place/Placement.java#L151)), that should be forwarded by SpongeForge (if I'm not mistaken). Maybe you have an idea?

Spigot/Paper/Sponge: 1.12.2-2838-7.3.1-RC4079
GriefDefender: 1.5.8
LuckPerms: 5.2.20

In Regards CreativeMD

**Comment by color-space** [comment]
More on this in the discord #issues channel

**Comment by CreativeMD** [comment]
@color-space on which discord server?

**Comment by bloodmc** [comment]
I've provided a fix on discord but there still seems to be an issue with client not getting updated properly. Relogging fixes the issue of course. Have you tested the client packets on Forge server and verified it works as expected?

**Comment by CreativeMD** [comment]
Yeah, that might be an issue of LT. Because the client always places it, so the server has to sync the blocks again. Should be an easy fix on my end.

**Comment by CreativeMD** [comment]
New version is out ... so many everything works properly, still needs to be tested.

**Comment by CreativeMD** [comment]
I guess I will close this issue as this has been already fixed and should work.

**Comment by color-space** [comment]
Testing confirms it.
