### ISSUE TITLE
[REQUEST] Support for claim enter / exit for respawn after death.

### ISSUE THREAD

**Issue by AgentSanchez** [bloodmc/GriefDefender#359]
- **Feature information**
Currently if a player dies in claim, once they respawn claim-exit events do not get triggered does not triggered. This includes both claimfarewell and option player-exit-command do not trigger. I think that a respawn after death event should be considered a move that triggers claim exit.

**Comment by bloodmc** [comment]
This has been implemented in latest development builds.
