### ISSUE TITLE
[BUG] All of the console spam

### ISSUE THREAD

**Issue by blacksythe** [bloodmc/GriefDefender#360]
- **Versions**
Spigot/Paper/Sponge: Sponge
GriefDefender: 1.5.9
LuckPerms: 5.2.78

- **Describe the bug**

- **Steps to reproduce the behavior**
NPE Playerticktask

- **Expected behavior**
No NPE
Also noticed a luckperms error just before the console spam also mentioning grief dfender row 39786

- **GDDEBUG**

- **Screenshots**
[latest.log](https://github.com/bloodmc/GriefDefender/files/5792096/latest.log)
[debug.log](https://github.com/bloodmc/GriefDefender/files/5792097/debug.log)

**Comment by bloodmc** [comment]
GD did not start properly due to a conflict with the PlaceHolderAPI you are using.
