### ISSUE TITLE
[BUG] Issue with claimcreate

### ISSUE THREAD

**Issue by kasdo** [bloodmc/GriefDefender#361]
My server was crashed because of this /claimcreate command
![image](https://user-images.githubusercontent.com/7419546/104494823-a76df000-55df-11eb-8f1f-ac9b1b591708.png)

![image](https://user-images.githubusercontent.com/7419546/104494879-b8b6fc80-55df-11eb-9091-6e2e44d12c4e.png)

**Comment by bloodmc** [comment]
Not running latest version. Provide stack traces when you are up to date.
