### ISSUE TITLE
Spanish Traslate[REQUEST]

### ISSUE THREAD

**Issue by koyere** [bloodmc/GriefDefender#364]
- **Feature information**

- **Other plugins or mods related to the request**

- **Additional context**

En algún lugar leí que estaba en español el lang. Podrían indicarme adonde?

**Comment by DrWurzeli** [comment]
https://github.com/bloodmc/GriefDefender/tree/master/common/src/main/resources/assets/lang

you can change it in
global.conf

**Comment by kencinder** [comment]
As per the above `es_ES` is available, if you require a different locale for Spanish, pull requests are welcome, translations are user contributed.
