### ISSUE TITLE
LP permission formatting issue

### ISSUE THREAD

**Issue by TakoidGit** [bloodmc/GriefDefender#37]
Entering the command:

`/lp group admin meta set griefdefender.player-fly 1`

Seems to _work_, but in LuckPerms the permission node is saved as:

`meta.griefdefender\.player\-fly.1`

instead of

`meta.griefdefender.player-fly.1`

I assume the latter is the intended format.

**Comment by bloodmc** [comment]
This is how LuckPerms stores it, it's not a GD issue. You can ask Luck here what his reasons are
https://github.com/lucko/LuckPerms/issues
