### ISSUE TITLE
[BUG] Displays 3D visuals in 2D claim with cuboid-level-visuals-2d=false

### ISSUE THREAD

**Issue by kccricket** [bloodmc/GriefDefender#370]
- **Versions**
[GD] Running GriefDefender 1.5.10
[GD] Running git-Paper-463 (MC: 1.16.5)
[GD] Running LuckPerms v5.2.96

- **Describe the bug**

With cuboid-level-visuals-2d set to false and owner min claim level set to 16, GD paints 3D/cuboid visuals when using the investigation tool (stick) on a 2D claim.

- **Steps to reproduce the behavior**

Set in options.conf
```
default-user-options {
min-level="16"
}
```

Set in global.conf
``` 
GriefDefender {
  visual {
    cuboid-level-visuals-2d=false
  }
}
```

Create a 2D admin, basic, or subdivision claim.
Inspect the claim with the investigation tool (stick).

- **Expected behavior**

Display 2D claim visuals.

- **Screenshots**

![Screenshot 2021-02-06 225831](https://user-images.githubusercontent.com/2245729/107136400-c30fa200-68d0-11eb-86a1-160e923a2bc2.png)

**Comment by bloodmc** [comment]
Thanks for the report! Will take a look.

**Comment by bloodmc** [comment]
This should have been fixed in earlier releases. Re-open if it is still an issue.
