### ISSUE TITLE
[BUG] Issue with claim create 3x

### ISSUE THREAD

**Issue by kasdo** [bloodmc/GriefDefender#373]
Hey! I've updated GD to the latest version but the issue wasn't fixed
https://github.com/bloodmc/GriefDefender/issues/365

![image](https://user-images.githubusercontent.com/7419546/107876586-8dba1400-6ecf-11eb-89c4-4e3683f6b2f6.png)

**Comment by bloodmc** [comment]
You are not running GD 1.5.10. If you want support then buy the plugin and join discord.

**Comment by kasdo** [comment]
Yeah, you are right. Is GD 1.5.10 for sponge for purchasing only?
