### ISSUE TITLE
[BUG] Cause of TPS Lag in the Server with 23+ players.

### ISSUE THREAD

**Issue by MikasaPixelmon** [bloodmc/GriefDefender#374]
- **Versions**
Sponge: spongeforge-1.12.2-2838-7.3.0 (1).jar
GriefDefender:  griefdefender-sponge-1.5.10.jar
LuckPerms:  LuckPerms-Sponge-5.2.90.jar

- **Describe the bug**
GriefDefender is one cause of TPS Lag on my server.

- **Steps to reproduce the behavior**
Having more than 23+ people online

- **Expected behavior**
TPS Drop

- **Screenshots**
![unknown](https://user-images.githubusercontent.com/69644328/109052985-84555680-76dc-11eb-99e5-49f13f56fbc3.png)

**Comment by bloodmc** [comment]
This is not a GD problem. Your entire server is lagging which of course will delay everything else.
