### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FrecciaTricolore** [bloodmc/GriefDefender#375]
- **Versions**
Spigot/Paper/Sponge: 1.16.4
GriefDefender: 1.5.10
LuckPerms: 5.2.35

- Hi,
I'd like to point out a vulnerability in the giveblock's mechanism.

In the giveblock file, we have:
availableBlocks = playerData.getAccruedClaimBlocks() + playerData.getBonusClaimBlocks();

So, that means that a player can give away all of the claim blocks he accumulated throughout time: the ones that are yet to be used to claim land and the ones already used to do so.

You previously said to me this is by design.
However, one of my staffers pointed out an issue that could be used to claim infinite land:

-Let a malevolent player X have multiple accounts, which we'll call A, B, C...
-Let each player be given out 500 blocks when joining the first time (or just wait for each player to develop 500 blocks) 

-A enters, and is given 500 blocks.
-A claims 500 blocks of land
TOTAL CLAIMED BLOCK: 500
-B enters, and is given 500 blocks.
-A gives 500 blocks to player B, going to -500.
That doesn't matter: A has served his purpose.
-B can now claim his 500 + the 500 A has given him = 1000 blocks.
TOTAL CLAIMED BLOCK: 500+1000= 1500
-C enters.
-B gives his 1000 to C, going to -1000
-C claims 500+1000 and goes to -1500
TOTAL CLAIMED BLOCK: 500+1000+1500= 3000

This continues. This is a series, and it's characterized this way:
a(n)= sum [n from 1 to infinity] M+a(n-1)
Where M is the blocks given to each player at the first joining

We've represented this using C code:

int main(){
  int sum = 0;
  for(int i=1; i<30; i++){
    //new player enters

    //player is given 500 and claims them
        sum += 500;
            
    //claimed blocks by all players:
    printf("With player %d: %d \n", i, sum);
    
    //player gives his blocks to the next player
    sum += sum;
    
  }
  return 0;
}

This is the result:
With player 1: 500 
With player 2: 1500 
With player 3: 3500 
With player 4: 7500 
With player 5: 15500 
With player 6: 31500 
With player 7: 63500 
With player 8: 127500 
With player 9: 255500 
With player 10: 511500 
With player 11: 1023500 

In a night, a malevolent player can claim a world.
The fix is easy: a player should only be able to give away the remaining blocks, the total minus the block claimed. The proposed change is
availableBlocks = getRemainingClaimBlocks()
(a method apparently existing)
Sorry if we didn't make a push request, but we're not good at all with github...
Thank you for your time

**Comment by DrWurzeli** [comment]
will forward this on the discord in case it gets seen faster there.

**Comment by bloodmc** [comment]
This has been fixed in GD 1.5.11
