### ISSUE TITLE
[REQUEST] Pl3xMap support for claims

### ISSUE THREAD

**Issue by mmolitor87** [bloodmc/GriefDefender#376]
- **Feature information**

Claim support in Pl3xMap, a lightweight flat-only map: https://github.com/pl3xgaming/Pl3xMap

- **Other plugins or mods related to the request**

https://github.com/pl3xgaming/Pl3xMap
https://github.com/pl3xgaming/Pl3xMap/tree/master/api/src/main/java/net/pl3x/map/api
https://github.com/pl3xgaming/Pl3xMap/wiki/Integration
https://github.com/pl3xgaming/Pl3xMap/wiki/Basic-API

- **Additional context**

A plugin exists for GriefPrevention: https://github.com/pl3xgaming/Pl3xMap-GriefPrevention
Here the dev is asking for people to potentially take ownership of add-ons: https://github.com/pl3xgaming/Pl3xMap/issues/18

**Comment by ahdg6** [comment]
It seems that the bloodmc has no time to add this function.
So I modified one from Pl3xMap-GriefPrevention,you can get it [here](https://github.com/Tartaros-Gamer/Pl3xMap-GriefDefender/releases/tag/1.0.0).

That works for me
![图片](https://user-images.githubusercontent.com/36436808/112717692-4b9ddc80-8f29-11eb-9605-7ff510913b8a.png)

**Comment by bloodmc** [comment]
Added to GDHooks
https://github.com/bloodmc/GDHooks
