### ISSUE TITLE
[BUG] exit-claim not triggering

### ISSUE THREAD

**Issue by zThana** [bloodmc/GriefDefender#379]
- **Versions**
Spigot/Paper/Sponge: Sponge 1.12.2-7.2.2
GriefDefender: 1.5.10
LuckPerms: 5.3.0

- **Describe the bug**
exit-claim doesn't trigger

- **Steps to reproduce the behavior**
I've tried using `/cf exit-claim player false` while standing in the claim but it doesn't prevent players from exiting the claim. While debugging, it didn't fire.

- **Expected behavior**
Should show up in gddebug and result in the player becoming unable to exit the claim.

- **GDDEBUG**
I would've if it showed anything, N/A

- **Screenshots**
N/A

**Comment by bloodmc** [comment]
The is not a bug as the flag works fine. This is a permission issue. Follow the permissions page on wiki or you will run into issues.
