### ISSUE TITLE
Player-fly option forces fly

### ISSUE THREAD

**Issue by TakoidGit** [bloodmc/GriefDefender#38]
My admins have the `meta.griefdefender.player-fly.1` permission node and are able to fly anywhere in the world as intended. However, they are unable to untoggle fly and can fly by double tapping space even after setting their fly mode to false via CMI.

I think the `player-fly` should only allow flight if flight is enabled via some other plugin or command other than GriefDefender. It should only permit the ability of flight if it's possible for a player in my opinion.

**Comment by bloodmc** [comment]
Fixed in 1.2.0 release.
