### ISSUE TITLE
Unable to claim block as it is above your maximum claim level limit

### ISSUE THREAD

**Issue by kkh44555** [bloodmc/GriefDefender#383]
`Unable to claim block as it is above your maximum claim level limit of`

I god this issue when I claim a block, I can't find the way to fix it.
Can any one help me please!

**Comment by muriplz** [comment]
i had the same issue and i solved it
Go to Lucky perms and add on default group the griefdefender_ groups as parents.

**Comment by kencinder** [comment]
> i had the same issue and i solved it
> Go to Lucky perms and add on default group the griefdefender_ groups as parents.
> It's not an issue with the plugin though.

Yep this is a result of removing the GD groups from default or if another group, it not inheriting default.
