### ISSUE TITLE
[BUG] Door protection does not work on door when using two side-by-side doors

### ISSUE THREAD

**Issue by timebomb0** [bloodmc/GriefDefender#384]
###  **Versions**
Spigot/Paper/Sponge: SpongeForge 1.12.2-2838-7.3.0
GriefDefender: Latest compiled as of March 9, 2020
LuckPerms: 5.2.106

### **Describe the bug**
When a building with two doors that open together is claimed, it is consistently possible for users that do not have access to the doors can enter the building by using the opposite door that they click on.

### **Steps to reproduce the behavior**
- Given a building with two side by side doors, example: 
![image](https://user-images.githubusercontent.com/22551992/110704057-59253980-81a9-11eb-8b91-220550fc4c22.png)

1. User A claims the building and prevents doors from being opened

2. User B attempts to open the door. They consistently get a warning that they can't use `item in their hand` on the door. Sometimes when User B opens the door, the doors open then close by themselves. Sometimes they both stay open but the user can't enter either. Sometimes when user B opens the door, after both doors close by themselves, the the door opposite of the one they clicked opens back up. e.g. Click left door, both doors open, then close, then right door opens. Screenshot:
![image](https://user-images.githubusercontent.com/22551992/110704298-a0132f00-81a9-11eb-8c16-bde433714113.png)

3. User B can now walk through the door that appears open on their screen.

This also can lead to the user potentially getting stuck in the building they are inappropriately able to enter, as the door protection forces them to not pass the door, i.e. not leave the building.

### **Expected behavior**
- When a user attempts to open doors they do not have access to, the doors should stay close 100% of the time. Sometimes they close after being opened, sometimes they stay open.
- When a user opens a building that has two doors like in the above problem scenario, they should never be able to enter through either door. Both doors should stay closed. The opposite door they click on should never open up.

**Comment by bloodmc** [comment]
This is a sponge bug with not updating the client when calling `event.setUseBlockResult(Tristate.FALSE)`. The server should still prevent the player from entering as only the client would see the door open. In any case, please move this ticket to SpongeForge as it is not a GD bug.

**Comment by timebomb0** [comment]
Thanks, will do. To clarify one point, I can consistently reproduce this wherein the user can still enter through the open door, so it seems like more than a visual bug. The door doesn't try teleporting me out like it may if it was just a visual bug.
