### ISSUE TITLE
[BUG] Build failed

### ISSUE THREAD

**Issue by stellariumm** [bloodmc/GriefDefender#386]
Hi!

I decided to try and compile GriefDefender from sourcecode from this repo using ./gradlew build.

I am running a modded spongeforge server and I really need this plugin. Now to the issue.

After I run command ./gradlew build I get error at Task :bukkit:compileJava. I will provide a more detailed screenshot of output.

SS: [Imgur](https://imgur.com/a/WArpVXJ)

JDK: 1.8.0_282 (adoptopenjdk8)
Gradlew: Project's 5.6.4

Thanks for any help!

**Comment by muriplz** [comment]
I think that you might need the libraries

**Comment by stellariumm** [comment]
Slimefun?

**Comment by stellariumm** [comment]
I also did a [Gradle scan](https://scans.gradle.com/s/criypmycskbi2)

**Comment by muriplz** [comment]
I have no idea how the sponge versión works, but I got the libraries out of spigot in my case

**Comment by stellariumm** [comment]
Thank you, but I still seem to struggle on spongeforge and this is the only plugin that I find it's really good with LuckPerms out of the box 😄 

Thank you anyways!

**Comment by Squad3tm** [comment]
Same issue, nobody has a clue on what the issue might be?

**Comment by stellariumm** [comment]
Issue still there... Maybe an alternative to GriefDefender since this is one of the main issues that is postponing the server opening.

**Comment by stellariumm** [comment]
Closed the issue due to developer not responding and not providing free support. Thanks to everybody that wanted to help!

**Comment by Vidhin05** [comment]
I have the same issue too

**Comment by catronomix** [comment]
Me too, seems like it doesn't find some files online, so I guess we can download them from somewhere else, but where to put them in the directory?
