### ISSUE TITLE
[BUG] Issue with doors

### ISSUE THREAD

**Issue by kasdo** [bloodmc/GriefDefender#388]
https://www.youtube.com/watch?v=xudokmYjF7k&feature=youtu.be

My server has 1.5.10 version of GriefDefender
There is no issue on GriefPrevention, hope you will fix it
![image](https://user-images.githubusercontent.com/7419546/112885130-091b0200-90d9-11eb-9617-4cc4458678bc.png)

**Comment by kencinder** [comment]
GD cannot and does not cause any dupes, all it does is cancel events. This would be something to take to the Sponge team.

**Comment by kasdo** [comment]
> GD cannot and does not cause any dupes, all it does is cancel events. This would be something to take to the Sponge team.

I have the same server but with GriefPrevention and there this issue doesn't work. So it's GriefDefender, I'm sure.
