### ISSUE TITLE
[BUG] Dispenser water sometimes wont flow in claims.

### ISSUE THREAD

**Issue by CrispyDairy** [bloodmc/GriefDefender#390]
- **Versions**
Spigot/Paper/Sponge: 1.16.5
GriefDefender: Latest
LuckPerms: 

- **Describe the bug**
In some instances water wont flow when dispensed by a dispenser inside the claim. This issue only happens inside claims.

- **Steps to reproduce the behavior**
This was found in a regular creeperfarm. Some of the layer's dispensers are firing the water but it's not spreading unless updated. Some of the layer's water does flow

- **Expected behavior**
The water should be flowing over the dispenser as normal.

- **GDDEBUG**

- **Screenshots**

![2021-04-14_21 28 15](https://user-images.githubusercontent.com/81482501/114760831-6f09b980-9d68-11eb-861c-06cd2c110136.png)

**Comment by kencinder** [comment]
Fill out the requested information correctly please, and provide a debug. `1.16.5` tells us nothing of the platform used, and `latest` is not a GD version.
