### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by Greazi-Times** [bloodmc/GriefDefender#391]
So I am using Ultra Permissions instaid of Luckperms I see that the plugin doesn't work when I haven't installed Luckperms but how can I use Uperms and not Luckperms?

**Comment by bloodmc** [comment]
GriefDefender requires LuckPerms.

Use LuckPerm's migrator

https://luckperms.net/wiki/Migration

**Comment by Greazi-Times** [comment]
Well so I need luckperms and I can't use Ultra Permissions??
And may I ask why I only can use luckperms?
