### ISSUE TITLE
Pixelmon PC's not working

### ISSUE THREAD

**Issue by ItsMeloww** [bloodmc/GriefDefender#393]
Heeyy, so I've just started using GriefDefender and I really like it. The only problem I have is that when I claim my spawn people can't interact with the PC's. Every other pixelmon item like trading machines works perfectly fine so I don't know if I'm doing something wrong or there is a mistake in the flag code for pixelmon.

Can anyone help me out?

Thank you!

~ Meloww

**Comment by DrWurzeli** [comment]
hey. are you using the pixelmon flags? https://github.com/bloodmc/GriefDefender/wiki/Pixelmon
there is a preset for pcs you can just toggle. otherwise use debug to find out why and just make the flag yourself/use a command.

**Comment by kencinder** [comment]
Use the linked Pixelmon definitions and the wiki, issues are not for usage support.

**Comment by ItsMeloww** [comment]
can you read? I said that I'm using the pixelmon flags but the only thing
not working is are the pcs although in the command it's set on true.

Op za 1 mei 2021 om 04:41 schreef kencinder ***@***.***>:
