### ISSUE TITLE
Admin Claims no longer protected?

### ISSUE THREAD

**Issue by R3KT3M** [bloodmc/GriefDefender#395]
My friends and I are setting up a Pixelmon Generations server using Sponge, we had the Admin Claim set around spawn and anyone with the LuckyPerms rank of Default could not break anything in spawn. Fast forward to adding in roughly 5 plugins or so and we noticed that the spawn region is no longer protected despite still being an Admin Claim. Normal players as well as Admins can break blocks. We cannot seem to figure out why; we've made sure any flags involving block breaking was disabled or set to false, any plugins that may have messed with the claims were removed with no results, we have tried countless plugin/mod reloads and server restarts and yet we just cant seem to figure out why players can still break within the claim. 
I was hoping someone would have input on what could be causing the issue or where we may be going wrong. We would prefer any results that don't include wiping claims as we have had other players begin to join and make their own claims, and we would hate for them to need to redo it all. I will provide a list of Mods and Plugins we have running currently on the server, as well as anything else that may be requested to figure this out. Haven't felt this stumped in a while.

![ModsAndPlugins](https://user-images.githubusercontent.com/83125876/115961437-2326e500-a4cb-11eb-9eb8-0fd7e932ae58.png)

(The one plugin we assumed was the culprit, Auto Mines, was in the plugin list before the claim broke, and didn't resolve anything when disabled or removed.)

**Comment by kencinder** [comment]
Use debug and check your permissions https://github.com/bloodmc/GriefDefender/wiki/Debugging

Claim flags don't just change, someone has changed something.
