### ISSUE TITLE
Problem with engaging with pokemon in pixelmon 1.8.2

### ISSUE THREAD

**Issue by Flybat777** [bloodmc/GriefDefender#396]
Currently, on our server, we're having an issue where our players cannot battle random spawning pokemon in people's claims. for example bosses and whatnot. The players can battle npcs and stuff however with pokemon whether it be a legendary or a boss or just a random spawn, they cannot engage. 

I can't find the fix for it.

**Comment by kencinder** [comment]
Use the Pixelmon definitions, they work out of the box https://github.com/bloodmc/GriefDefender/wiki/Pixelmon

https://github.com/bloodmc/GriefDefender/wiki/Debugging is also helpful for anything not already provided in a definition, and is useful for making your own.

Closing, issues are not for usage of the plugin, that's what the wiki is for.
