### ISSUE TITLE
[BUG] Error delete admin claim

### ISSUE THREAD

**Issue by HeberonYT** [bloodmc/GriefDefender#398]
- **Versions**
Spigot/Paper/Sponge: Paper 645
GriefDefender: griefdefender-sponge-1.5.11-DEV.jar
LuckPerms: LuckPerms-Bukkit-5.3.34.jar

- **Describe the bug**
I have created an Admin claim, now I decided to delete it and I receive the error message in the console, there is no more information, only that error when I confirm that I want to delete.

- **Steps to reproduce the behavior**
Stand on the admin claim, enter / deleteclaim, confirm in chat, you will get the error.

- **GDDEBUG**
https://pastebin.com/raw/zk99YLd6

- **Screenshots**
https://i.imgur.com/zzSV6JC.png

**Comment by kencinder** [comment]
Working fine on 1.5.11 release here, there would be errors in the log, provide a log as per the issue template in the future
