### ISSUE TITLE
[BUG] Entities can trigger PLAYER-COMMAND-ENTER which results in the commands being executed for every player regardless of their relation to the claim.

### ISSUE THREAD

**Issue by pokewillpower** [bloodmc/GriefDefender#399]
![image](https://user-images.githubusercontent.com/83932354/117743612-185f9600-b1d5-11eb-8d4a-303a624e27b4.png)

Entities are capable of executing the claimoption flag for PLAYER-COMMAND-ENTER, which will execute the command for every player on the server. Mobs that are spawned within the region do not exhibit this behavior unless they leave the region and re-enter or cross the boundary of another claim. If you were to have PLAYER-COMMAND-ENTER issue the command '/kill %player%' it would kill each and every player online, even though it was a MOB that entered the region and not a player (This effectively softlocks a server that has scheduled entities entering that region).

**_TO RECREATE:_**

Create a claim and apply the following to best illustrate the issue:

>  /claimoption player-command-enter "/title %player% title {"text":"Claim","bold":true,"color":"dark_aqua"}" context[run_for=public, run_as=console]
> 
> /claimoption player-command-enter "/title %player% subtitle {"text":"Subtitle","italic":true}" context[run_for=public, run_as=console]
> 
> /claimoption player-command-enter "
> /playsound minecraft:record.cat master %player% ~ ~ ~ 1000" context[run_for=public, run_as=console]
> 
> /claimoption player-command-exit "/stopsound %player% master minecraft:record.cat" context[run_for=public, run_as=console] 

From here, spawn a mob OUTSIDE of the claim and wait for it to enter the claim. You will notice that even though no player entered the claim, the commands for the titles and record are played for everyone, even those completely uninvolved with the process. To better illustrate this, reproduce this issue with a second player hundreds or even thousands of chunks away-- although the 2nd player is nowhere near the claim, they are still affected by the execution of the commands. Curiously, entities are NOT capable of triggering "player-command-exit" in the same manner. This leads me to believe the above is unintended behavior.

**_WHAT SHOULD HAPPEN:_**

As the flag suggests, "player-command-enter" should only be triggered by a PLAYER. Even if we were to entertain the idea that this sort of behavior is intended, the relevant commands should only be executed for the mob, rather than every single player online.

Included is an instance of gddebug where the issue was replicated. The player "KurohaDaze" does not move throughout the entire recording. The mob "Bulbasaur" is sent out, outside of the claim, and executes the title and playsound commands for every player on the server (in this case, just KurohaDaze).
https://griefdefender.github.io/debug/?JFWuY5Ju3C

![image](https://user-images.githubusercontent.com/83932354/117746319-3ed40000-b1da-11eb-84ca-646e6dce81ec.png)
![image](https://user-images.githubusercontent.com/83932354/117746324-41cef080-b1da-11eb-92ec-7e8fa4f7a1de.png)

**Comment by bloodmc** [comment]
Fixed in GD 1.5.11 release.
