### ISSUE TITLE
New Language System

### ISSUE THREAD

**Issue by darbyjack** [bloodmc/GriefDefender#4]
This is basically a rundown of how to handle the new language system.

Example of all the languages in a language folder
https://github.com/guilds-plugin/Guilds/tree/master/src/main/resources/languages

Language files being saved to language folder
https://github.com/guilds-plugin/Guilds/blob/master/src/main/java/me/glaremasters/guilds/Guilds.java#L152

Language files being loaded using ACF
https://github.com/guilds-plugin/Guilds/blob/master/src/main/java/me/glaremasters/guilds/acf/ACFHandler.java#L63

In-game commands ran to update the languages
https://github.com/guilds-plugin/Guilds/blob/master/src/main/java/me/glaremasters/guilds/commands/admin/CommandAdminUpdateLanguages.java

Download the zip files of the languages
https://github.com/guilds-plugin/Guilds/blob/master/src/main/java/me/glaremasters/guilds/utils/LanguageUpdateUtils.java#L50

Pom modification I use to put the languages in their own ZIP file
https://github.com/guilds-plugin/Guilds/blob/master/pom.xml#L157

The MessageKey enum used to get messages from the language file.
https://github.com/guilds-plugin/Guilds/blob/master/src/main/java/me/glaremasters/guilds/messages/Messages.java

zip.xml file
https://github.com/guilds-plugin/Guilds/blob/master/src/main/assembly/zip.xml

**Comment by bloodmc** [comment]
Messages have been done in commit https://github.com/bloodmc/GriefDefender/commit/ba39de90ab6e9b060f54ed6682abed9f7a93d721

Command description support will be next
