### ISSUE TITLE
[BUG] Issue with region creating

### ISSUE THREAD

**Issue by kasdo** [bloodmc/GriefDefender#401]
![image](https://user-images.githubusercontent.com/7419546/119385537-ecf9a280-bcce-11eb-9c0d-07930ac81c6a.png)
Plugins and mods

GD 1.5.10 version.
Players can their regions over another regions:
- ppos1
- ppos2 
- claimwe

**Comment by bloodmc** [comment]
Unable to reproduce in latest GD version.
