### ISSUE TITLE
Command/permission update

### ISSUE THREAD

**Issue by ItsMeloww** [bloodmc/GriefDefender#402]
Heeyy,

I saw in the updated 1.5.11 that they added new commands like /trapped and /unlockdrops and really want to use them. sadly I can't find the permissions or just the command in general on the wiki.

am I just stupid or isn't it updated yet?

**Comment by bloodmc** [comment]
Updated wiki. Remember you can always use https://github.com/lucko/LuckPerms/wiki/Verbose to check permissions used.
