### ISSUE TITLE
[BUG] -1 Claim level limit

### ISSUE THREAD

**Issue by WTProductions** [bloodmc/GriefDefender#403]
- **Versions**
Spigot/Paper/Sponge: Latest
GriefDefender: Latest
LuckPerms: Latest

Myself, the owner of the server, and all other users, are experiencing the following error when trying to set a claim.
"Unable to claim block as it above your maximum claim level limit of -1"
Not sure how to reproduce this.

I expected to be able to claim as normal

If it helps, we're a pixelmon server.

**Comment by bloodmc** [comment]
Your permissions are not setup properly. Follow the permissions page on wiki.

https://github.com/bloodmc/GriefDefender/wiki/Permissions
