### ISSUE TITLE
[BUG] Create Mod, Deployer 

### ISSUE THREAD

**Issue by ghost** [bloodmc/GriefDefender#404]
- **Versions**
Spigot/Paper/Sponge: Mohist 1.16.5 Build 621
GriefDefender: 1.5.11
LuckPerms: 5.3.3
Create Mod: 1.16.5_v0.3.1c

- **Describe the bug**
Deployer from Create mod doesnt put saplings in claim areas.

- **Steps to reproduce the behavior**
Creating a deployer machine to place saplings on grass, it doesn't place
- **Expected behavior**
The deployer has to place saplings on grass.

- **GDDEBUG**
https://griefdefender.github.io/debug/?eAEbjtYGpM

- **Screenshots**
![image](https://user-images.githubusercontent.com/23585012/121075097-250ee400-c7ab-11eb-99a2-6de22e7d943c.png)
![image](https://user-images.githubusercontent.com/23585012/121075139-35bf5a00-c7ab-11eb-879e-98f207821961.png)

**Comment by kencinder** [comment]
Hybrids like Mohist are not officially supported, and have numerous issues that are the result of using a Hybrid. This isn't an issue with GD, it's an issue with how Hybrids work(in that bukkit knows nothing of a Forge mods presence).
Patreon supporters are provided with support for hybrids on an "if possible" basis in the official Discord.
