### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Emerg2711** [bloodmc/GriefDefender#405]
Looking for some help when trying to load up GriefDefender on Sponge, I am not sure where I am supposed to post something like this so I apologise in advance if it's not meant to be here.

These are the errors that show up when I attempt to load GriefDefender, not sure what to do.

https://pastebin.com/usQNfTsc
https://pastebin.com/VB7BZ915

**Comment by kencinder** [comment]
This is not a bug, nor are the libraries shown in that log versions that are in use in the current version(1.5.11). Usage support is provided in the Discord for paid users, bugs are fine here...but a bug this is not.
