### ISSUE TITLE
[BUG] Build fail (solution)

### ISSUE THREAD

**Issue by catronomix** [bloodmc/GriefDefender#407]
- **Versions**
Spigot/Paper/Sponge:  paper 1.16.5
GriefDefender: 1.5.10
LuckPerms: 5.3.48

So I spent all day going from one build error to the next, clearing my .gradle folder and trying again and again.
Finally managed to build the latest version on windows.
So I'd thought to post my solution here for anyone who needs it (probably myself in the future)

Here we go:
- DIdn't want to work with OpenJDK 11 (contrary to a forum post I read) - use JDK-8 instead
- Build errors regarding not finding things or not downloading things:

search all the build.gradle files for lines starting with //compileOnly, and remove the // for all except:
`//compileOnly "com.github.thebusybiscuit:cs-corelib:master-SNAPSHOT"`

clear c:/users/<yourusername>/.gradle
run `gradlew.bat build`

Question to developer: Why were these lines commented out if they are needed to build the project?

**Comment by bloodmc** [comment]
Because it uses jitpack which is not always reliable. You can simply add the jar for gradle to use.
