### ISSUE TITLE
[BUG] DivingRPG & GD Causing Lag

### ISSUE THREAD

**Issue by RupticMC** [bloodmc/GriefDefender#409]
- **Versions**
Spigot/Paper/Sponge: Mohist 1.12.2-230
GriefDefender: 1.5.11 (also happened in previous versions)
LuckPerms: 5.3.51

- **Describe the bug**

When having DivineRPG Mod (v1.7.1 and older) and GriefDefender on the server, it will spam errors in the console and whatever error it is running into is causing the server to lag and/or DivineRPG worlds to generate very slowly.

Couple errors in console: 
https://paste.helpch.at/tojunufebe.rb
https://paste.helpch.at/wamijiquxe.sql

- **Steps to reproduce the behavior**

Start Mohist (or other Hybrid like Magma) with the mod DivineRPG and GriefDefender.

- **Expected behavior**

I expected the server to not have the current error out and for the server to not lag.

- **GDDEBUG**

Short debug before server started lagging.

- **Screenshots**

**Comment by bloodmc** [comment]
The stack trace isn't complete. Please provide a complete stack trace from actual server log.

**Comment by bloodmc** [comment]
Performance was greatly improved in latest 2.X versions.
