### ISSUE TITLE
Duplication Bug - Grief Defender 1.5.9-DEV

### ISSUE THREAD

**Issue by Neovitalism** [bloodmc/GriefDefender#410]
To put it simply, any block that can be broken by water is prone to duplication. 

To recreate this bug: Claim an area with one player, and have that player place a torch inside the claim. (This bug was found with a pixelmon berry tree, but this gets the idea across) Have another player that isn't trusted in the claim place a water bucket on the block the torch is sitting on, so the water and the torch occupy the same block. A torch will pop off, and the original torch will still be there, at the expense of your water bucket.

**Comment by kccricket** [comment]
I'm unable to reproduce this with Paper 1.17.1 build 138 and GriefDefender 2.0.0.

**Comment by Neovitalism** [comment]
Apologies, we're using 1.5.9-DEV on Sponge.

**Comment by DrWurzeli** [comment]
GD cancels events, it doesnt dupe items.
did you test with SF/LP/GD only?

**Comment by kencinder** [comment]
1.5.9 is not supported and has long since been superseded by 1.5.10 and 1.5.11, and latest version is 2.0.

GD only cancels events and would not be the cause of a dupe.
