### ISSUE TITLE
[BUG] Anyone can quit paintings from a claimed region

### ISSUE THREAD

**Issue by pelusoide** [bloodmc/GriefDefender#413]
- **Versions**
Spigot/Paper/Sponge: Purpur-1296
GriefDefender: GriefDefender 2.0.0
LuckPerms: LuckPerms v5.3.51

- **Describe the bug**
Players can break a painting from a protected region.

- **Steps to reproduce the behavior**
Make a claim with an user and put a painting in a wall, then with other user without perms try to break the paint.

- **Expected behavior**
The user without perms shouldn't have the possibility to break a paint.

**Comment by kccricket** [comment]
I can reproduce, but this isn't a bug. Unless my config isn't up to date, there's simply no default flag denying player damage to a painting entity.

**Comment by pelusoide** [comment]
> I can reproduce, but this isn't a bug. Unless my config isn't up to date, there's simply no default flag denying player damage to a painting entity.

I have been reading the wiki and i saw that its possible to make custom behaviours for a flag, but i don't know how the system works, so it's possible to made custom behaviour for the painting entity?

**Comment by GuusLieben** [comment]
Take a look at https://github.com/bloodmc/GriefDefenderDefinitions/blob/master/1.16.5/presets/minecraft.conf or https://github.com/bloodmc/GriefDefenderDefinitions/blob/master/1.12.2/presets/minecraft.conf
You'll probably need something like this:
```yaml
painting-damage {
    contexts=[
        "gd_claim_default=user"
    ]
    default-value=false
    enabled=true
    permissions=[
        "flag=entity-damage, target=minecraft:painting, source=minecraft:player"
    ]
}
```
Note that I haven't tested the above, so there may be some additional permissions that need to be added

**Comment by bloodmc** [comment]
Added `painting-damage` definition for upcoming 2.0.5 release.
