### ISSUE TITLE
[BUG] 50% of the plugin GUI's - does not work

### ISSUE THREAD

**Issue by tlgnkl** [bloodmc/GriefDefender#414]
- **Versions**
Spigot/Paper/Sponge: Purpur-1331
GriefDefender: 2.0.0b
LuckPerms: 5.3.58

- **Describe the bug**
There are a lot of buttons in the plugin GUI-they absolutely do not work. I tried deleting the plugin folder and the plugin itself, but it didn't help

- **Steps to reproduce the behavior**
https://youtu.be/RYUBCALdTEY

- **GDDEBUG**
https://griefdefender.github.io/debug/?WpYZhHcsHK

- **Screenshots**
https://youtu.be/RYUBCALdTEY

**Comment by minenexuslive** [comment]
I have the same problem, the buttons don't work for me

**Comment by DrWurzeli** [comment]
what is that error message in chat that appears when you try to click a button? @OstriySous-dev

**Comment by minenexuslive** [comment]
No error appears, it just doesn't work for me: https://youtu.be/KO1I1KAVMRQ

**Comment by DrWurzeli** [comment]
it does in  OstriySous-devs video.
what server version are you using?
Also make sure to test with GD/LP only to prevent conflics from chat plugins or other things.

**Comment by minenexuslive** [comment]
I'm on version mohist-1.16.5-756-server.jar, I will test only with GP and LP

**Comment by DrWurzeli** [comment]
no need. Mohist doesnt work with the new Kyori so clicking anything in chat wont work.

**Comment by DrWurzeli** [comment]
you can find the issue thread here https://github.com/MohistMC/Mohist/issues/1626

**Comment by minenexuslive** [comment]
Any suggestions on how to proceed?

**Comment by DrWurzeli** [comment]
some people tried Arclight for 1.16+ or switched to pure SpongeForge/Paper. for Mohist itself, no. sadly not.

**Comment by kencinder** [comment]
As mentioned Mohist doesn't work, as for the GUI not working it works 100% on Paper and Sponge, the only time I've seen issues has been a lack of following the readme and deleting the libs folder etc

If you've purchased GD you should have access to the Discord server where latest dev builds are located.

**Comment by bloodmc** [comment]
Mohist/Magma fix available on Discord.
