### ISSUE TITLE
Console Error Server Crash

### ISSUE THREAD

**Issue by LucidAPs** [bloodmc/GriefDefender#416]
https://nekobin.com/visosinade
Purpur 1.17.1-R0.1-SNAPSHOT
GriefDefender 2.0.0

To be fair I am pretty sure its caused by the voting plugin because I have set it to use grief defender commands as rewards, that is the reason I believe GriefDefender is appearing on this log. But just in case I am wrong, I thought I should post this.

**Comment by LucidAPs** [comment]
I've talked to the author of the voting plugin and he says it caused by grief defender, triggered by a console command that is assigned as a reward from a voting site.

**Comment by LucidAPs** [comment]
Yeap server crashed again.....
https://nekobin.com/sesurigaze

**Comment by bloodmc** [comment]
This issue is not caused by GD as the command runs in console fine without the voting plugin. No issues with votifier plugin.

**Comment by LucidAPs** [comment]
> This issue is not caused by GD as the command runs in console fine without the voting plugin. No issues with votifier plugin.

So it's caused by the votingplugin then? Which author should I believe?

**Comment by LucidAPs** [comment]
Also I am not sure how you test what is happening because it's not like the server will crash immediately after someone votes and triggers the console command,
