### ISSUE TITLE
[BUG] Incompatible with ExecutableItems's Keep on Death, option.

### ISSUE THREAD

**Issue by angelo-pokecraft** [bloodmc/GriefDefender#418]
- **Versions**
PaperMC: git-Paper-249; Git: 6fa1983
GriefDefender: 2.0.1 DEV 14
LuckPerms: 5.3.58

- **The bug:**
In a combination of the plugin Griefdefender and ExecutableItems (Free version), the keep inventory stops working.
item setting: "Keep item on death" set to TRUE.
basically this causes an invisible error to go off as the inventories will be wiped, without the item made in ExecutableItems, the inventory will stay the same. With it it will be cleared out upon dying.

- **Expected behavior:**
Not to clash with one another, possibly an idea to add a workaround in GDHooks of some sort, as this took way to long to find out due to 0 errors happening in the console and the logs.

also a typo on the bug report form, Sentence with the typo:
A clear and concise set of steps to reproduce the **behaviour**

**Comment by bloodmc** [comment]
I just tested ExecutableItems-3.5.8.3 with GriefDefender 2.0.4 and could not reproduce the issue. I created a custom sword and set 'Keep item on death' to TRUE. Upon respawning, it was added back to my inventory.
