### ISSUE TITLE
[BUG] Language FR

### ISSUE THREAD

**Issue by Twister1one** [bloodmc/GriefDefender#420]
- **Versions**
Spigot/Paper/Sponge:  Airplane 1.17.1-R0.1
GriefDefender: 2.0.1
LuckPerms: 5.3.64

- **Describe the bug**
hello :) I set language french and `label-blocks=Blocs` not work
it displays "blocks" (look screen)
Same for BASIC

- **Screenshots**
![image](https://user-images.githubusercontent.com/25822504/133409099-0d4ad455-a7ca-4be2-b257-1633ec43a475.png)

**Comment by bloodmc** [comment]
Fixed for upcoming 2.0.5 release.
