### ISSUE TITLE
[BUG] MISSING LANGUAGE

### ISSUE THREAD

**Issue by Twister1one** [bloodmc/GriefDefender#421]
- **Versions**
Spigot/Paper/Sponge: Airplane 1.17.1-R0.1
GriefDefender: 2.0.1
LuckPerms: 5.3.64

- **Describe the bug**
Hello, the "ID" label is missing in the <lang>.conf files
I can not find it.
For the label-raid, it doesn't work when we modify it

- **Screenshots**
![image](https://user-images.githubusercontent.com/25822504/133414947-75fbb8c3-c77c-4522-b281-177027f8beba.png)
![image](https://user-images.githubusercontent.com/25822504/133415320-1fc4acfa-b06a-45fb-8865-338770811d1c.png)

**Comment by bloodmc** [comment]
Fixed for upcoming 2.0.5 release.
