### ISSUE TITLE
[BUG] Language error

### ISSUE THREAD

**Issue by Twister1one** [bloodmc/GriefDefender#422]
- **Versions**
Spigot/Paper/Sponge: Airplane 1.17.1-R0.1
GriefDefender: 2.0.1
LuckPerms: 5.3.64

- **Describe the bug**
Mhh, i have language french but `ui-click-add="&7Clique ici pour ajouter"` don't work ^^
And second screen, missing line for traduction :/

- **Screenshots**
![image](https://user-images.githubusercontent.com/25822504/133419986-8059ede2-dc89-4282-a07c-8ce810394557.png)
![image](https://user-images.githubusercontent.com/25822504/133420151-03d941dd-a6ba-4f4b-91c0-645a8e5dc8c3.png)

**Comment by bloodmc** [comment]
Fixed for upcoming 2.0.5 release.
