### ISSUE TITLE
[BUG] blocked-cmds not migrating

### ISSUE THREAD

**Issue by DanielGroeneweg** [bloodmc/GriefDefender#423]
- **Versions**
Spigot/Paper/Sponge: git-Paper-774 (MC: 1.16.5)
GriefDefender: 2.0.1
LuckPerms: v5.3.47

- **Describe the bug**
I wanted to disable the usage of World Edit in the wildernis, thus I used WorldGuard to block the usage of the command "//set" in the region "__global__". This worked fine and it didn't allow non-OP players to use the //use command in 'the wilderniss'. When I migrated the WorldGuard flags to GriefDefender I could still use the //set command as a non-OP player though. The files were succesfully migrated since placing and breaking blocks got denied which I also did in WorldGuard.

- **Steps to reproduce the behavior**
1. Use the command "/rg flag __global__ blocked-cmds //set" to deny the usage of the //set command.
2. Delete the WorldGuard jar and turn WorldGuard migration on in the global.conf file.
3. Restart the server, checking the migration in the console.
4. Be able to usage the //use command in the wilderniss while it should have been disabled.

- **Expected behavior**
At step 4 the usage of the //set command should have been disabled for Non-OP players.

**Comment by kencinder** [comment]
Worldguard regions are migrated, not worldguard flags

**Comment by DanielGroeneweg** [comment]
In that case I have 2 questions:
1. Why would you say on the wiki the flag blocked-cmds is supported for migration when it is not?
2. Is there any way to deny the usage of world edit in wilderniss with your plugin?

**Comment by kencinder** [comment]
Sorry jumped the gun a bit, it's custom flags with WG that aren't supported. May have something to do with double slash used by WE.

In any case setting it like this example should work
https://github.com/bloodmc/GriefDefender/wiki/Flags#example-5
