### ISSUE TITLE
[BUG] Wilderness's permission to build bug

### ISSUE THREAD

**Issue by TheGamersBrew** [bloodmc/GriefDefender#428]
- **Versions**
Spigot/Paper/Sponge: Sponge
GriefDefender: 2.0.0 (as the 2.0.1 file didn't have a Spongeforge file with it on spigot)
LuckPerms: 5.3.69

- **Describe the bug**
When a default user is building in a unclaimed area at a distance of 20,000 blocks out they ran into a bug where the wilderness itself had claimed blocks (a few at random without any apparent pattern to them or depth as some only being one dirt block) leaving them to not dig in the area. They could claim it themselves and then be able to dig that area up and place blocks down within. after abandoning the claim it went back to it saying you don't have wilderness's permission to build. upon heading to the area using /claiminfo in the area it showed nothing but normal wilderness info for the area within and with admin ability could brake and place without message showing up.

- **Steps to reproduce the behavior**
Found at random in area exceeding 20,000 near a village and above a mineshaft. (other then that have yet to find it anywhere else in the server)

- **Expected behavior**
not have wilderness have a claimed area

- **GDDEBUG**
Not sure what this would be (sorry)

- **Screenshots**
(I asked for a screen shot of the message and this is what they sent me) 
![image](https://user-images.githubusercontent.com/77638191/137672932-e17890b7-89fe-40e5-bdbc-c9675fbe40f9.png)

**Comment by bloodmc** [comment]
This is a bug in 2.0.0 which was resolved in 2.0.1. Access discord for the latest build.
