### ISSUE TITLE
discord link

### ISSUE THREAD

**Issue by vaniron** [bloodmc/GriefDefender#429]
Hi, whats the discord link? Nowhere for me to find it to get sponge jar and support.

**Comment by bloodmc** [comment]
Discord is private. Buy the plugin on spigot if you want a discord link.

**Comment by shawn3308** [comment]
i want to buy

**Comment by shawn3308** [comment]
so can i get the discord link

**Comment by Possemaster** [comment]
I need GDHooks, but there is no Discord link anywhere. This must be the wordt documented plugin ever.
