### ISSUE TITLE
[REQUEST] Support SpongeAPI 8.0.0

### ISSUE THREAD

**Issue by lurr** [bloodmc/GriefDefender#430]
- **Feature information**
Update the current Sponge implementation to support API8 for newer versions of Minecraft.

- **Other plugins or mods related to the request**
[Sponge](https://github.com/SpongePowered/Sponge)

**Comment by bloodmc** [comment]
When SpongeForge is stable on API 8, I will update. Currently, there is still a lot of work to be done for SF.

**Comment by bloodmc** [comment]
GriefDefender has been updated to support Sponge API 8. It is currently available to patreons.
