### ISSUE TITLE
[BUG] i can't /ignoreclaims

### ISSUE THREAD

**Issue by TaharX** [bloodmc/GriefDefender#433]
- **Versions**
Spigot/Paper/Sponge: 
GriefDefender: 2.0.7
LuckPerms: 5.3.89

- **Describe the bug**
i can't /ignoreclaims , while im op, and it says i don't have permission

- **Steps to reproduce the behavior**
go to claim, then type /ignoreclaims

- **Expected behavior**
i will be able to open players chests and destroy,etc

- **GDDEBUG**
-

- **Screenshots**
-

**Comment by bloodmc** [comment]
OP doesn't matter. You need to assign the proper permissions as stated on wiki page
https://github.com/bloodmc/GriefDefender/wiki/Permissions
