### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FizzyBrandi** [bloodmc/GriefDefender#434]
- **Versions**
Spigot/Paper/Sponge: 
GriefDefender: 2.0.7
LuckPerms: 5.3.89

_**Describe the bug**
i can't /ignoreclaims , while I'm op, and it says i don't have permission. I am new to this and I am very lost, a link or step by step would be helpful. 

- **Steps to reproduce the behavior**
go to claim, then type /ignoreclaims

- **Expected behavior**
i will be able to open players chests and destroy,etc

**Comment by bloodmc** [comment]
OP means nothing in GD. Assign the proper permissions as stated on permission page.

https://github.com/bloodmc/GriefDefender/wiki/Permissions
