### ISSUE TITLE
FLAGS RESET AFTER RELOAD/RESTART

### ISSUE THREAD

**Issue by ST3RmY** [bloodmc/GriefDefender#435]
- **Versions**
Spigot/Paper/Sponge: SpongeForge 1.12.2-2838-7.3.0
GriefDefender: 1.5.10
LuckPerms: 5.3.89

- **Describe the bug**
- After 5 / 10m or after a / gd reload or / sponge plugins reload the flags do not update but go back to the previous change.

- **Steps to reproduce the behavior**

- **Expected behavior**

- **GDDEBUG**

- **Screenshots**

**Comment by bloodmc** [comment]
Never use `/sponge plugins reload`. It is NOT supported nor will it ever be.
