### ISSUE TITLE
[BUG] endcrystal-use doesn't allow placing end crystals

### ISSUE THREAD

**Issue by TraceLTRC** [bloodmc/GriefDefender#437]
- **Versions**
Spigot/Paper/Sponge: git-Paper-152 (MC: 1.18.1)
GriefDefender: 2.0.9
LuckPerms: 5.3.98

- **Describe the bug**
In the Wiki, the default flag definition for _endcrystal-use_ controls if players can place or break end crystals. This flag definition alone does not control the placement of end crystals. You need to allow both _endcrystal-use_ and _player-block-interact_ to allow the placing of end crystals.

- **Steps to reproduce the behavior**

1. Use the plugin on a clean server. It will generate the default config and presets.
2. Create a claim, and set _endcrystal-use_ to true
3. Turn on flag debug _/cfdebug_
4. Try and place an end crystal on any valid block.

- **Expected behavior**
End crystal is placed, and can be broken.

- **GDDEBUG**
https://griefdefender.github.io/debug/?bwDmnhZqa0

**Comment by bloodmc** [comment]
The definition contains `interact-item-secondary` which prevents placing the crystal. Wipe your presets folder and re-test. If it still occurs then you have a permission set granting you `interact-item-secondary` access. Also if testing as owner, you need to set the flag under the `OWNER` tab not `PUBLIC`.
