### ISSUE TITLE
[QUESTION] Why does this plugin need to pollute my LuckPerms groups?

### ISSUE THREAD

**Issue by Test-Account666** [bloodmc/GriefDefender#438]
Hey!
I tested out your plugin and instantly noticed my Prefix plugin breaking because your plugin creates new groups in luckperms.

I wondered why this is necessary?

All other very popular plugins work without doing something like this too, so I'd love to have an answer.

Best Regards

**Comment by bloodmc** [comment]
First, GD 2.X is far different than 1.5.X. No other plugin provides protection the way GD does with contexts. If you want to know why then read the wiki.
