### ISSUE TITLE
[REQUEST] Reduce the high barrier of entry into the discord channel

### ISSUE THREAD

**Issue by Crumb5** [bloodmc/GriefDefender#441]
- **Feature information**
A longer grace period on the discord invite email, or better yet, ability to join the discord server publicly and verify purchase before accessing the support channels.

- **Other plugins or mods related to the request**
Other plugins don't make the barrier of entry so high. So far reaching out for support has been the most frustrating experience of this plugin.

- **Additional context**
I've emailed a couple of times to request a renewed discord invite. (Please respond to your emails). At the very least make the discord invite validity period 7 days instead of 1.

**Comment by bloodmc** [comment]
You received another discord invite on Thursday @ 8:17PM EST which does NOT expire. This ticket also has nothing to do with GD's source code.
