### ISSUE TITLE
[Question] Why dose GD need custom Groups and Users in Luckperms?

### ISSUE THREAD

**Issue by Hutch79** [bloodmc/GriefDefender#444]
Hey

I have noticed that GD creates Groups and Users in Luckperms.

Now my Question, why?

I don't want to use the created groups, I have my own groups. And also why do you add permissions to users, I don't even know?

**Comment by kencinder** [comment]
GitHub issues are not for questions and support

**Comment by Hutch79** [comment]
That's why I wrote "Question" in the title.

I'm still interested in an answer.

Also, in my opinion, it is kind of a bug (even if it's intended) that you can't deactivate it. At least, I haven't found an option for this yet.

**Comment by kencinder** [comment]
Isn't a bug and it's how the plugin works, you have no reason to care that they exist or to touch them and it won't change either.

Again though, questions are for discord...not tickets on GitHub so validly closed
