### ISSUE TITLE
[REQUEST] Bad Language Filter the same way as GriefPrevention Has.

### ISSUE THREAD

**Issue by cybermancerr** [bloodmc/GriefDefender#446]
- **Feature information**

Please add the BAD  WORDS filter the same way GriefPrevention plugin currently has.

- **Other plugins or mods related to the request**

GriefPreventio

- **Additional context**

**Comment by bloodmc** [comment]
Chat filtering does not belong in a protection plugin and is just unneeded bloat. Use a proper chat plugin that supports what you want like ChatManager.

https://www.spigotmc.org/resources/chat-manager-1-7-1-18-30-features-and-40-commands.52245/
