### ISSUE TITLE
[REQUEST] Pixelmon Flag - Pokemon-riding

### ISSUE THREAD

**Issue by SimonMage** [bloodmc/GriefDefender#447]
- **Feature information**

Is it possible to add flag Pokemon-riding for flying pokemon and grounded pokemon

- **Other plugins or mods related to the request**

Pixelmon - reforged.gg

- **Additional context**

**Comment by bloodmc** [comment]
Add your own. Read the wiki

https://github.com/bloodmc/GriefDefender/wiki/Flag-Definitions-GUI
