### ISSUE TITLE
[BUG] Lang file.

### ISSUE THREAD

**Issue by pitruk** [bloodmc/GriefDefender#448]
lf i change "label-confirm=Confirm" to a different name, gui stops working. 
but.. 
If I change "label-cancel=Cancel" then i don't get this issue.

**Comment by pitruk** [comment]
eg. "label-confirm=Confirm" to "label-confirm=xxx"

**Comment by FITFC** [comment]
Don't translate this, "label-confirm" has special handling due to "griefdefender.login.inventory-gui".
That guarantees bedrock users support in having a GUI... whoever plays on a completely Java server has no problems with that.

**Comment by pitruk** [comment]
in the default language file it is translated;) 

Many other lines cause similar issue.

**Comment by bloodmc** [comment]
Fixed in latest GD 2.1.6 DEV.
