### ISSUE TITLE
[Suggestion] ForSale notify

### ISSUE THREAD

**Issue by DrWurzeli** [bloodmc/GriefDefender#45]
Add a notify-feature for claims, that are flagged as "for sell".
Users that walk over such a claim would get a notify message making it easy for them to spot available claims and buy them, not only on /claimbuy.

This could be enabled in the config or put in as a flag, that can be set for the specific claim.

Example config lines:
enable-forsell-notify: true (default, can be changed to false or undefinied (if used as flag))
forsell-notify-message: "This claim is up for sell. Buy it for <price> using /gd buy claim" (default string, can be changed of course)

permission: griefdefender.user.claim.command.notify
allows the user to toggle this feature on or off so they dont get the notifier if they are an advanced user or already got a claim.
(could potentially be used for other notifiers as well in the future)

**Comment by Shybella** [comment]
Duplicate https://github.com/bloodmc/GriefDefender/issues/19

**Comment by DrWurzeli** [comment]
thanks @Shybella, will close.
