### ISSUE TITLE
[Performance BUG]

### ISSUE THREAD

**Issue by JanDim** [bloodmc/GriefDefender#450]
- **Versions**
Spigot/Paper: 1.18.2
GriefDefender: 2.1.4
LuckPerms: [v5.4.16]

- **Describe the bug**
 Performance bug, check the timings report i have create and see the lag spike that created, GriefDefender::onWorldSave tick https://timings.aikar.co/?id=54bfd08a6d6a4d08bddae2f315332169
i dont know why and how to fix that

**Comment by bloodmc** [comment]
This is not a bug and requires more info as anything can cause 4 ticks to spike. Use discord for these types of questions.
