### ISSUE TITLE
Error when i get to start up my server

### ISSUE THREAD

**Issue by MrWhiteFlamesYT-dev** [bloodmc/GriefDefender#453]
Hello when i start my server up i get error that it could not read 
> java.lang.NullPointerException: Cannot read field "message" because the return value of "com.griefdefender.configuration.GriefDefenderConfig.getData()" is null
and
>java.lang.NullPointerException: Cannot invoke "com.griefdefender.configuration.StorageConfig.getData()" because the return value of "com.griefdefender.GriefDefenderPlugin.getStorageConfig()" is null

You can find the part of log here
> https://mcpaste.io/b35540c49ed12837
Full Latest.log
> https://mcpaste.io/20ac13f561f88e65

Here is my current config as well.
Global.conf
> https://mcpaste.io/95a87f4b19aba8ff

**Comment by bloodmc** [comment]
Support is only given on discord. You should have received a discord invite via paypal email. Email kanesoftware@outlook.com if you did not.
