### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by ShotunJC** [bloodmc/GriefDefender#456]
I recently payed for the plugin but require it for sponge and read that I need to download from discord. I have not received the discord invite link. 

Pease assist

**Comment by HighAdmiral** [comment]
The system for sending the discord link is not automatic. Bloodmc sends the link to people who have purchased the premium edition manually once per day, hence the "wait 24 hours" part of recieving the discord link. I'm currently waiting myself, but see Blood was last active 25 hours ago. Please try to be patient.

**Comment by HighAdmiral** [comment]
The email address containing the invite was sent to the email of the paypal account you used. You'll need to ask your parent to give it to you. If you have access but don't see the email, check your spam inbox.
