### ISSUE TITLE
[BUG] Sculk catalyst not obeying claims

### ISSUE THREAD

**Issue by ToastedEggplant** [bloodmc/GriefDefender#457]
- **Versions**
Spigot/Paper/Sponge: Paper 9b6fb2f 1.19
GriefDefender: 2.2.0
LuckPerms: 5.4.25

- **Describe the bug**

Killing things near a sculk catalyst outside a claimed area spreads sculk into the claim still.

- **Steps to reproduce the behavior**

Place a sculk catalyst outside of a claim and have someone else who isn't allowed in the claim to kill mobs near it spreading sculk into the claim.

- **Expected behavior**

Other players should not be able to spread sculk into my claim, I'd expect it to spread to only places that are unclaimed

- **GDDEBUG**

- **Screenshots**

![image](https://user-images.githubusercontent.com/9472512/173202111-7e62c542-6cda-4b8e-9dfa-2de15d93ad35.png)

**Comment by DrWurzeli** [comment]
sculk protection has been added and will be available in GD 2.2.3 which is currently in testing on the discord.
once it releases feel free to test and close this if everything works as expected
