### ISSUE TITLE
[BUG]The use permission missing pressure slab

### ISSUE THREAD

**Issue by yang91889** [bloodmc/GriefDefender#461]
- **Versions**
Spigot/Paper/Sponge: 1.19
GriefDefender: 2.2.1
LuckPerms: 5.4.30

- **Describe the bug**

I give player use permission in the claim, but they can't use pressure slab

- **Steps to reproduce the behavior**

Give player use permission in the claim

- **Expected behavior**

Give player use permission in the claim and they can use pressure slab

- **GDDEBUG**

- **Screenshots**

**Comment by DrWurzeli** [comment]
reproduce with 2.2.2 and provide a debug.
players with access trust can use pressure plates in claims unless you have overriden this.
