### ISSUE TITLE
Request: Allow frogspawns inside player claims by default

### ISSUE THREAD

**Issue by Tractorzysta** [bloodmc/GriefDefender#463]
- **Describe the bug**
Frogspawn can't grow up inside claims (in wild all is fine)

- **Steps to reproduce the behavior**
Frogspawn was placed in water inside claim. They can't transform to frogs since few days.

- **Expected behavior**
Frogspawn should transfort themselves to frogs since a while

- **GDDEBUG**
none

- **Screenshots**
none

**Comment by Tractorzysta** [comment]
griefdefender.flag.entity-damage true gd_claim_default=global source=transformreason:metamorphosis target=minecraft:tadpole

**Comment by alpoi-old** [comment]
Can be fixed by typing `/cf entity-damage any true source=transformreason:metamorphosis default=user` in-game

**Comment by bloodmc** [comment]
Also `/cf block-break frogspawn true source=frogspawn override=global`
