### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by ColUndie** [bloodmc/GriefDefender#464]
I have a request and I hope it gets implemented and i don't know if it's already available but give the ability to giveall claims so everyone on the server can get claims and so it's possible to sell the claims on the webstore without it becoming p2w since giving everyone claims isn't giving anyone advantage over the other since everyone gets it :)

**Comment by DrWurzeli** [comment]
you can already give blocks to everyone online. does that work for you?

**Comment by DrWurzeli** [comment]
https://docs.griefdefender.com/wiki/Commands.html#gd-player-adjustbonusblocksall
for anyone else stumbling upon this.
