### ISSUE TITLE
Pre-Purchase Question

### ISSUE THREAD

**Issue by TDev-Inquire** [bloodmc/GriefDefender#468]
Can I make claims inside of claims, for instance in a y0 - y max claim to protect builds, and then inside of it an x10 y10 z10 cuboid claim region where it's allowed to break blocks? 

I havent found any other plugins that can do this with sponge and would love it if yours could. 

ive tried to reach out in multiple ways but just cant get to the developer. 

AndIf you could also message me on discord it would be greatly appreciated! TDev#9964

**Comment by DrWurzeli** [comment]
that is possible, yes.
GD has a feature called 3D/Volume claims and claims can have subdivisions or hold other claims depending on their type.
