### ISSUE TITLE
[REQUEST]  Prevents players from being able to put water and item into the claims through the Dispenser

### ISSUE THREAD

**Issue by ShuoYu1026** [bloodmc/GriefDefender#469]
My English is not very good, so I have to use pictures to express my meaning
![2022-08-26_22 50 35](https://user-images.githubusercontent.com/109022855/186932384-3cabb3e7-efd3-4ec3-ab3f-c05a9d230190.png)
![2022-08-26_23 05 29](https://user-images.githubusercontent.com/109022855/186935622-6e725194-f5bf-46cc-891f-f01c23ad0da5.png)

Contains Subdivision Claim
can refer to griefprevention

**Comment by ShuoYu1026** [comment]
![2022-08-26_23 08 53](https://user-images.githubusercontent.com/109022855/186936178-32a1d775-9147-4035-b9bb-f188d1db4af5.png)
Added: Pistons too

**Comment by bloodmc** [comment]
Please provide server info, GD version, etc..
