### ISSUE TITLE
[BUG] Tadpoles not growing

### ISSUE THREAD

**Issue by Tant33** [bloodmc/GriefDefender#471]
- **Versions**
Spigot/Paper/Sponge: git-Paper-81 (MC:1.19)
GriefDefender:  2.2.1
LuckPerms:  5.4.36

- **Describe the bug**
Tadpoles aren't growing up in claims, while they do outside

- **Steps to reproduce the behavior**
By breeding frogs & using tadpole buckets to get them.

**Comment by bloodmc** [comment]
Use command `/cf block-break frogspawn true source=frogspawn override=global` to fix

**Comment by ReiaTheGeia** [comment]
> Use command `/cf block-break frogspawn true source=frogspawn override=global` to fix

That's not what the issue is, it's that tadpoles do not become frogs in claims, not that frogspawn won't break.
