### ISSUE TITLE
[REQUEST] Any Alternative to /siege (Grief Prevention) or raid add-on

### ISSUE THREAD

**Issue by conttdj** [bloodmc/GriefDefender#475]
Hello!
I have been looking for a add-on for attacks or war raids, looking at the plugin it is about safety and protection from grief, but a raid add-on would be nice since the java servers lack raid plugins

So my suggestion is straight, having a raid-system would be great and giving a reason to migrate to SiegeDefender.

**Comment by TomLewis** [comment]
I requested this a few years ago Cont, will require it to be an additonal plugin outside of GD as its out of scope was the answer I got.

**Comment by conttdj** [comment]
I understand it is out of scope, but even if they made a side plugin it would be great!

Sad to see it this way

**Comment by DrWurzeli** [comment]
[see ](https://github.com/bloodmc/GriefDefender/issues/47)
