### ISSUE TITLE
[BUG] Can't use the /cf command

### ISSUE THREAD

**Issue by IllusionCIS7** [bloodmc/GriefDefender#489]
- **Versions**
Paper: git-Paper-307 (MC: 1.19.2)
GriefDefender: 2.3.1
LuckPerms: v5.4.56

I can't use the /cf command. Everytime i try to use the command, the following error appears two times:
"Du hast keine Berechtigung diese Einstellung zu nutzen." or see the screenshot below

The command i tried is one from the documentation: 
`/cf entity-damage pig false used_item=diamond_sword override=basic`

The permissions i gave to myself:

`griefdefender.advanced.admin.flags.*
griefdefender.user.*
griefdefender.admin.*`

- **Steps to reproduce the behavior**
    - Install Griefdefedener on the server
    - Create a basic claim
    - Get the permissions from above
    - Type the command from above

- **Expected behavior**
I expected the flag to be set.

- **GDDEBUG**
[Link](https://griefdefender.github.io/debug/?Vl3ZwC104D)

- **Screenshots**
![image](https://user-images.githubusercontent.com/91783924/212469880-3f9dd1b7-c9fb-409e-ad19-1fa65b809e50.png)

**Comment by DrWurzeli** [comment]
if you want to use /cf with arguments, grant yourself griefdefender.advanced.*
