### ISSUE TITLE
The Getting Started referenced from the readme requires a precompiled binary locked behind a paywall

### ISSUE THREAD

**Issue by DarkIlluminatus** [bloodmc/GriefDefender#494]
I'm not sure how this can be qualified as an open source project if additional binaries that have a monetary requirement are required as part of the installation.  Please update the Getting Started with at least very basic compiling instructions so this project continues to belong on this site.

A good example is how mcMMO handles it.  Since this also requires a lot of additional configuration beyond simply downloading the .jar you can be sure we will be able to follow even the most basic instruction such as on mcMMO that simply states the simplest possible command required, in this example being simply:

"The typical command used to build mcMMO is: mvn clean package install"

It's not much, and it still obfuscates the process and drives users to the paywall and also allows itself to continue to be called open source and free.

**Comment by DrWurzeli** [comment]
I know this is an older issue, so just as an update for anyone interested: GD’s core is no longer open source since 2.0.
