### ISSUE TITLE
[BUG][Server] WARN Plugin 'GriefDefender' is creating timing - this is deprecated behavior, please report it to the authors: 

### ISSUE THREAD

**Issue by nyanstack** [bloodmc/GriefDefender#502]
I'm using Grief Defender version 2.3.5

Please tell how to fix these lines in console that I see every time I start my server:

09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimflagdefinitiongroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimflagdefinitionplayer' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cfg' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cfp' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cfr' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgreeting' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroupadmin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroupadmin join' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroupadmin unjoin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroupadmin create' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroupadmin delete' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup admin claimgroup admin join' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup admin claimgroup admin unjoin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup admin claimgroup admin create' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup admin claimgroup admin delete' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroup join' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroup unjoin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroup create' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgroup delete' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup claimgroup player join' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup claimgroup player unjoin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup claimgroup player create' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd claimgroup claimgroup player delete' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimgui' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimid' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimignore' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claiminfo' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claiminherit' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claiminspect' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimlist' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claim' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimnotifications' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cod' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cog' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cop' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cpg' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: cpp' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimrent' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimreserve' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimschematic' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimsell' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: sellclaim' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimsetspawn' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimsnapshot' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimsnapshot create' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimsnapshot delete' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimsnapshot apply' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd snapshot' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd snapshot create' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd snapshot delete' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd snapshot apply' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimspawn' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: modesubdivide' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimtax' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimtitle' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimtool' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: modetown' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimtransfer' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: claimunban' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gdwe' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: ct' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gddebug' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gdblocktransfer' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gdconfirm' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gdreload' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gdversion' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: givepet' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd help' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gd:pagination' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: gdplayerinfo' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: restoreclaim' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: modenature' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: scb' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: townchat' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: towntag' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: transferblocks' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trapped' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trustgroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trust' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trustallgroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trustallgroupadmin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trustall' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: unlockdrops' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: untrustgroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: untrust' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: untrustallgroup' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: untrustallgroupadmin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: untrustall' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'Command: trustlist' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] INFO [GriefDefender] Loaded successfully.
09.05 04:10:31 [Server] WARN **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
09.05 04:10:31 [Server] WARN The server will make no attempt to authenticate usernames. Beware.
09.05 04:10:31 [Server] WARN While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
09.05 04:10:31 [Server] WARN To change this, set "online-mode" to "true" in the server.properties file.
09.05 04:10:31 [Server] INFO Preparing level "world"
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onBlockBreak' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onBlockCollide' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onBlockNotify' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onBlockPlace' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onBlockPost' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onBlockPre' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityExplosionPre' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityExplosionDetonate' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityAttack' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityCollide' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityDamage' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityDamageMonitor' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityDeath' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityDropDeathItem' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityMount' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityMove' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntitySpawnPre' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntitySpawn' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onEntityTeleport' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerChangeHeldItem' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerChat' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerCommand' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerDeath' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerDispenseItem' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerLogin' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerHandleShovelAction' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerInteractBlockPrimary' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerInteractBlockSecondary' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerInteractEntityPrimary' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerInteractEntitySecondary' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:31 [Server] WARN Plugin 'GriefDefender' is creating timing 'onPlayerInteractInventoryClick' - this is deprecated behavior, please report it to the authors: 
09.05 04:10:32 [Multicraft] Skipped 24 lines due to rate limit (160/s)

**Comment by DrWurzeli** [comment]
timings were removed from GriefDefender 2.3.7 onwards, when paper actually stopped using them.
