### ISSUE TITLE
[REQUEST] Oraxen Furniture Support Please

### ISSUE THREAD

**Issue by jahua50** [bloodmc/GriefDefender#504]
- **Feature information**
Please add support for Oraxen's furniture feature. Currently an untrusted player can place furniture in other people's claim, causing trouble for the claim owner.

- **Other plugins or mods related to the request**

Oraxen plugin
https://www.spigotmc.org/resources/%E2%98%84%EF%B8%8F-oraxen-add-items-blocks-armors-hats-food-furnitures-plants-and-gui-1-18-1-20-1.72448/
https://docs.oraxen.com/

**Comment by bloodmc** [comment]
This is already supported with GDHooks
