### ISSUE TITLE
Creepers will not explode inside claims with explosion-block set to false globally.

### ISSUE THREAD

**Issue by WhatsTheBadNews** [bloodmc/GriefDefender#51]
Using the latest version.

What I want to happen: Creepers to explode inside claims and do damage to the players, but not to blocks when I have /cf explosion-block any false context[source=creeper, override global]. This is how it worked in previous versions.

What happens: Creepers get fat and stuck in a state before explosion, as seen here:
https://cdn.discordapp.com/attachments/594944709387091998/615873711941091358/2019-08-27_06.40.52.png

I believe this is causing it:
explosion-block    none    creeper    elytra    (3339, 64, -1397)    WhatsTheBadNews    explosion-block    FALSE

https://griefdefender.github.io/debug/?tdNnKbtKHY

**Comment by Kazer67** [comment]
Can confirm, with explosion-entity at true for the creeper (tested as a source or a target) creeper will be stuck right before the explosion.

As soon as explosion-block for the creeper is set to true, the creeper will explode, but damage the block around in a claim.

The creeper should explode but not do any block damage when explosion-entity for creeper is true and explosion-block is false.

**Comment by bloodmc** [comment]
Does this occur with 1.2.1j?

**Comment by WhatsTheBadNews** [comment]
Yes. I recorded a video today on 1.2.1j to illustrate the issue.

https://www.youtube.com/watch?v=oAXFbU9aoKw&feature=youtu.be
