### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by triesharder** [bloodmc/GriefDefender#510]
i pay'd for GD many months ago and i can't remember if i received a discord invite, i do not have the confirmation email anymore, my username on spigot is "qoshi" can you message me the link?

i was searching and found another gh issue telling me that the discord is private.

i just wanted to ask if it's possible to prevent players from receiving claim blocks if they are afk

**Comment by bloodmc** [comment]
This is not a bug

Use setting claim-block-task-move-threshold in global.yml
