### ISSUE TITLE
[REQUEST] Limit rent system

### ISSUE THREAD

**Issue by ElTuna** [bloodmc/GriefDefender#512]
- **Feature information**
Adding a limit to get renting subclaims/claims

- **Other plugins or mods related to the request**
Adding a limit to the renting sub claims/claims
for instance... i want my users to be able to get just one rented sub claim

Could this be added soon?

**Comment by bloodmc** [comment]
This is not a bug. Use the option rental-limit. There is also a GD ReslEstate plugin on discord.
