### ISSUE TITLE
[BUG] Fabric mod crashes the client, not the server

### ISSUE THREAD

**Issue by alexzander700** [bloodmc/GriefDefender#514]
- **Versions**
Spigot/Paper/Sponge: Fabric 1.20.4
GriefDefender: griefdefender-fabric-1.20.4-2.5.3
LuckPerms: LuckPerms-Fabric-5.4.113

- **Describe the bug**

Whenever you /claim or hold a golden shovel, the client crashes but not the server with the following Disconnect prompt:
![image](https://github.com/bloodmc/GriefDefender/assets/51793351/8f72992a-17e1-4e09-94e0-d9d05bed0fdb)

- **Steps to reproduce the behavior**

Hold Golden Shovel or say /claim

- **Expected behavior**

Allows the player to claim.

- **GDDEBUG**

No clue what this means, but I have given my player the * tag in Luck Perms to allow me to use any command. As far as I know I can't get far enough to test 1 to 1 permissions

- **Screenshots**

Uhhh I already posted it above, however I'll repost it.
![image](https://github.com/bloodmc/GriefDefender/assets/51793351/f30e6af3-2216-425b-9f4b-e0f133b458ad)

**Comment by alexzander700** [comment]
Forgot the title

**Comment by bloodmc** [comment]
This is no longer an issue with later GD Fabric builds.
