### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by pepomann** [bloodmc/GriefDefender#515]
mi email is ciprianionutciuchina@gmail.com is the email where I made the purchase, and I m using moist for mi server I need the sponge powered plugin

i m looking in mi email and I don't have the access to the discord

**Comment by Dublin2274** [comment]
Did you by any chance get the link? I bought the plugin back in 2020, but lost access to my discord and decided to run another server. Emailed the Kane software email but haven’t gotten a reply.
