### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Donny-mcg** [bloodmc/GriefDefender#516]
- **Versions**
Spigot/Paper/Sponge: git-Paper-370 MC 1.20.4
GriefDefender: 2.5.5
LuckPerms: 5.4.120

- **Describe the bug**
When using /buyblocks, /buyclaimblocks, /sellclaimblocks I get the error
"Sorry, buying and selling claim blocks is disabled.
I have set the values for the price of claim blocks in options file.
I am using EssentialsX version 2.21.0 for my economy plugin.

- **Steps to reproduce the behavior**
Installed Plugin
Modified option file
used /buyclaimblocks command

- **Expected behavior**
The ability to buy claim blocks at the desired price.

- **GDDEBUG**
Cant find debug logs..will find if needed.

- **Screenshots**
Dont feel necessary but will provide if needed.

[options.txt](https://github.com/bloodmc/GriefDefender/files/14628705/options.txt)
[global.txt](https://github.com/bloodmc/GriefDefender/files/14628706/global.txt)

**Comment by bloodmc** [comment]
This is not a bug

Follow https://docs.griefdefender.com/wiki/#economy-mode

and make sure LP default group is inheriting GD groups properly as stated here 

https://docs.griefdefender.com/wiki/Permissions#important
