### ISSUE TITLE
Question: How do you update GDHooks with a better version of java?

### ISSUE THREAD

**Issue by Mrs-Feathers** [bloodmc/GriefDefender#518]
Asking here because others' questions have been unanswered for a year and my questions are going on a few weeks so im just gonna ask here in hopes its more active from the developer.

We have to use java v20 because more and more plugins require it. papermc i believe requires at least v18? 

anyway, GDHooks is from what i can tell built on java v8. how can i update that? will it be updated?

**Comment by bloodmc** [comment]
GDHooks supports 1.12.2+. Any plugin integration that requires higher Java uses an adapter that gets injected during runtime.
