### ISSUE TITLE
[REQUEST] Folia Support

### ISSUE THREAD

**Issue by ZepsiZola** [bloodmc/GriefDefender#520]
## **Feature information**
Support for Folia servers.

## **Additional context**

I was looking around for claim plugins that are compatible with Folia, but there are very few and the ones that are compatible with Folia turn out to have claim systems that are based around chunks only, which is not how I want it to work on my server. I would definitely buy this plugin if it was Folia compatible.

**Comment by bloodmc** [comment]
Folia 1.21+ is now supported in 3.0.0
