### ISSUE TITLE
[BUG] GD doesn't fully check for borders

### ISSUE THREAD

**Issue by Etanarvazac** [bloodmc/GriefDefender#521]
## **Versions**
Spigot/Paper/Sponge: 1.21.1 Paper
GriefDefender: 2.5.12
LuckPerms: 5.4.139

## **Describe the bug**
GD is not stopping at the world border. This bug was found on the XCraft Survival server owned by MasonX3. I am a moderator and caught wind of this issue from one of players (who discovered it and brought it to my attention immediately). This works in all dimensions.

## **Steps to reproduce the behavior**
1. Make a claim next to the world border.
2. Use the `/claimexpand <amount> <direction>` command to expand claim outside border
3. Notice error in chat, but claim was expanded successfully, and without taking from the player's balance
4. Use `/abandon` to sell claim
5. Notice sell amount is greater than purchase amount the more expanded outwards you go.

## **Expected behavior**
The claim cannot expand outside the world border.

## **Screenshots & Videos**
I have a video of the issue. The only way this video can be viewed, is with this link:
https://youtu.be/qBhxzMdyXJg

**Comment by MasonX3** [comment]
Licensed is assigned to myself for reference: https://www.spigotmc.org/members/masonx3.21501/

**Comment by bloodmc** [comment]
Fixed in 3.0.0
