### ISSUE TITLE
/claimexpand Not Working Properly

### ISSUE THREAD

**Issue by WhatsTheBadNews** [bloodmc/GriefDefender#54]
GD Version: 1.2.1h
Paper 183 (Minecraft 1.14.4)

Doing /claimexpand 1 north returns: "No valid command entered"
![Capture](https://user-images.githubusercontent.com/29821149/64234891-de48d780-cebc-11e9-9708-297b9aba9973.PNG)

Doing /claimexpand north 1 returns: "Error: 1 must be a number"
![Capture2](https://user-images.githubusercontent.com/29821149/64234965-fde00000-cebc-11e9-9e49-788271dd63f1.PNG)

NOTE: The claimexpand command works fine when you do not include a direction.

**Comment by bloodmc** [comment]
Bug is caused due to direction requiring uppercase. As a temporary workaround, just do the following

`/claimexpand 1 NORTH`
