### ISSUE TITLE
Players can enter a claim with enter-claim player false with ender pearls

### ISSUE THREAD

**Issue by WhatsTheBadNews** [bloodmc/GriefDefender#55]
GD Version: 1.2.1h
Paper 186 (Minecraft 1.14.4)

For this test, I created a claim and did /gd flag player Tobeka enter-claim player false

Tobeka can get inside the claim with ender pearls and move around inside with the ender pearls (as long as he doesn't walk).

**Comment by bloodmc** [comment]
Does this occur with 1.2.1j?
