### ISSUE TITLE
Certain players unable to build, but permission is set to TRUE

### ISSUE THREAD

**Issue by UoibiE** [bloodmc/GriefDefender#58]
https://griefdefender.github.io/debug/?PNEpqs87e7

Link to the debug. ShadowBran26 is what you want to look for.

Permission is set to true, but he can't build. Image here: https://cdn.discordapp.com/attachments/600418445015777292/623222718648680468/unknown.png

**Comment by bloodmc** [comment]
Unable to reproduce this with 1.2.2. Please reopen a ticket if it occurs again.
