### ISSUE TITLE
WECUI visuals when creating a claim do not match the resulting claim

### ISSUE THREAD

**Issue by BillyGalbreath** [bloodmc/GriefDefender#6]
This one is hard to explain, but I'll try and follow it up with a video.

Right click a block to start creating a claim. The WECUI visual comes up and outlines a nice visual of a bounding box. The corner seems to be show at the player's reach, which causes issues because when clicking the second time the visual is nowhere near the actual block clicked.

Video: https://youtu.be/k4ifzvUOqtQ

**Comment by bloodmc** [comment]
So to support this properly, we will need a change in WECUI
The current spec only supports following the player's eye when sending `~` for all 3 points as shown here
https://github.com/mikroskeem/WorldEditCUI/blob/master/src/main/java/com/mumfrey/worldeditcui/event/cui/CUIEventPoint3D.java#L42

I assume you would like it to follow the block the cursor is hitting up to a specified range. For the time being, I will disable the drag while in 2D mode.

**Comment by bloodmc** [comment]
I added a new visual setting to workaround this issue

https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/java/com/griefdefender/configuration/category/VisualCategory.java#L37

Does this work for you?
