### ISSUE TITLE
[SUGGESTION] RENT CLAIMS

### ISSUE THREAD

**Issue by vkaygaming** [bloodmc/GriefDefender#60]
Hi
i'd love to see a system for renting out claims, would be cool to set up a price similar to selling a claim but then players have to pay it and can then see how much time they have before the next payment. so essentially lets say i set a plot up for 100 Simoleons then it temporarily grants me either limited or full access (as predetermined by the seller) for shall we say a day and if i then pay that 100 again within that day it grants me another 24 hours and it almost stacks up like a timebank that way with a limit that could be set in config.

**Comment by thewickening** [comment]
I would love this feature, I would like it so you set it up for how much it will cost to rent per day, if the user does not have that much it automatically removes them and has the plot back up for rent again.

**Comment by lewisflude** [comment]
We are currently using WorldGuard for spawn and regions in a shopping area that we then rent out using AreaShop. I'm not sure how unique my setup is, but this functionality would allow me to replace WorldGuard and AreaShop. I feel like it's well within the scope of the plugin considering it already allows for selling plots.

**Comment by Brycey92** [comment]
I'd also love to see this feature, especially since I don't have access to WorldGuard on Sponge.

**Comment by bloodmc** [comment]
Implemented in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
