### ISSUE TITLE
GriefDefender stopping stone drops from multimine

### ISSUE THREAD

**Issue by Shybella** [bloodmc/GriefDefender#62]
Multimine is causing stone and other times with GriefDefender not to drop. 

Steps to reproduce

1. Install RLCraft
2. Install Sponge (3926 or latest)
3. Install GriefDefender (Sponge)
4. Take a flint pickaxe and mine stone

https://github.com/SpongePowered/SpongeForge/issues/2997

**Comment by kencinder** [comment]
Not a GD or GP issue, this is outlined in that linked issue.
