### ISSUE TITLE
Cannot click chat "buttons" on latest Beta build

### ISSUE THREAD

**Issue by robot7boy** [bloodmc/GriefDefender#74]
Hello,
I started testing the latest beta build, Version: griefdefender-1.2.2l, and it seems I cannot click any of the confirm buttons that are in chat along with any of the other similar buttons the plugin generates.

**Comment by bloodmc** [comment]
When using developer builds, you must wipe your library/conf folders so it can regenerate latest changes. I can confirm latest works fine in production.

**Comment by robot7boy** [comment]
I'm afraid that after doing this, it did not solve the issue. If there is anything else I can try please let me know
