### ISSUE TITLE
[Request] #crop Context Group Key

### ISSUE THREAD

**Issue by kencinder** [bloodmc/GriefDefender#77]
As per discussion in Discord, `#food` key does not cover block-place/break with food items, those are for use/consumption.

A new key `#crops` to handle this is needed.

**Comment by kencinder** [comment]
I'm closing this because because datapack support for tags is now a thing for 1.13+

**Comment by kencinder** [comment]
No, only what is already handled by GD will continue to work. MC tags can be customized via datapack in 1.14+

**Comment by Brycey92** [comment]
Ahhh gotcha, thanks for the info.
