### ISSUE TITLE
Players cannot break blocks with sticks or golden shovels.

### ISSUE THREAD

**Issue by lurr** [bloodmc/GriefDefender#80]
Running build from commit f2a13b953942232e53a81a63754645cbcc074bbd
Sponge 7.1.8-RC3963
LuckPerms v4.3.75

As explained in title, blocks cannot be broken with sticks or golden shovels, applying globally.

**Comment by i9hdkill** [comment]
Same here, built from here https://github.com/bloodmc/GriefDefender/commit/7aeb9f1333ccbf2a84c59bca10ddfb250d796796

**Comment by bloodmc** [comment]
Working as intended. If you do not want to use claiming tools such as stick and golden shovel then remove the id's from config and use `/claim` command instead.

**Comment by i9hdkill** [comment]
Why not block block-break when in claim-mode only?
