### ISSUE TITLE
GriefDefender does not work with newer versions of LuckPerms

### ISSUE THREAD

**Issue by lurr** [bloodmc/GriefDefender#81]
Tested with LuckPerms 5.0.23 on Bukkit and Sponge.
Caused by API refactoring in lucko/LuckPerms@b286faa1c58fb14f5a9019dcdb8cb6a7454639d3

Error log: https://pastebin.com/khrL4rwE

**Comment by bloodmc** [comment]
You need to use the legacy extension that LuckPerms provides.

https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api

I'll eventually update to v5 but for now you must use the extension.
