### ISSUE TITLE
[Enhancement] gametime context

### ISSUE THREAD

**Issue by DrWurzeli** [bloodmc/GriefDefender#82]
From Discord user: YoSuboDeToh
Additional information and implementation ideas: me.
Would be nice, if flags could be active only on certain ingame hours
(most likely used for "during night" and "during day".)

This could be done by adding a new context to flags like `context[gametime=x]`
possible values for x being:
day = 1000 to 6000 ticks
noon = 6000 to 12000 ticks
sunset = 12000 to 13000 ticks
night = 13000 to 18000 ticks
midnight = 18000 to 23000 ticks
sunrise = 23000 to 1000 ticks

maybe:
allnight =12900 to 22200 ticks
allday =  22200 to 12900 ticks

all ticks were respectfully ripped from [https://minecraft.gamepedia.com/Day-night_cycle]

some concerns:
this may interfer with other plugins using time/cooldowns/moonphases/etc.

Best regards
Max
edit: removedDiscordTag, fixed half sentences.

**Comment by DrWurzeli** [comment]
for the (almost) 1year birthday of this ticket, a little addition:

A user on the Discord just had a problem with another custom plugin handling this feature for mob-spawning on Sponge, which resulted in spawn events not being fired correctly. support in GD for gametime context would solve this problem as the plugin would no longer be neccessary to control spawns at different times - as GD could check  all flags with the given gametime context.

**Comment by bloodmc** [comment]
Today marks 2 year anniversary of this ticket...Time sure does go fast but this feature is now ready. Available in GD 2.0.8
