### ISSUE TITLE
Botania Mana Lens: Bore not working correctly

### ISSUE THREAD

**Issue by bigenergy** [bloodmc/GriefDefender#83]
Botania mana lens bore does not destroy blocks. 
To reproduce:

1. Take Manaburst (spreader) on redstone, take mana lens bore, take creative manapool
2. Assemble this construction
3. Place the lever next to mana spreader
4. After activation lever he must break the blocks, but does not do this

See a video: https://youtu.be/Rs8aE2S3kcY
Debug https://griefdefender.github.io/debug/?HJpSHNwi7L

I use /cf block-break any true context[source=botania:manaburst] - all worked, BUT!
if i allow everyone manaburst destroy blocks in the my claim - other players will just direct manaburst with Mana Lens: Bore and the blocks will breaks

- forge-1.12.2-14.23.5.2847
- spongeforge-1.12.2-2838-7.1.8-RC3963
- Botania+r1.10-362
- griefdefender-sponge-1.2.2-TEST11

**Comment by bloodmc** [comment]
SpongeForge bug
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/9fd6f90687fa71e3839a0bb921c80994a20e6a1d
