### ISSUE TITLE
admin claim overrides are applying for basic aswell

### ISSUE THREAD

**Issue by i9hdkill** [bloodmc/GriefDefender#85]
How to reproduce:

Create a basic claim with a normal user acc.
Try to use a pixelmon:super_rod

You get this message:
![image](https://user-images.githubusercontent.com/4679374/71329347-68788280-2524-11ea-9a37-43efec609aec.png)
What the message is saying: You need the permission from PlayerA (Which is the player that is currently using the rod!) to interact with pixelmon:super_rod

Found the issue:
This permission denies the usage of these rods
![image](https://user-images.githubusercontent.com/4679374/71329431-78dd2d00-2525-11ea-9509-ac7b10a1c1dc.png)

But it shouldn't as its a basic claim

**Comment by bloodmc** [comment]
I could not reproduce this on Spigot or Sponge. Please setup a clean server with LP/GD and list exact steps to reproduce.

**Comment by i9hdkill** [comment]
Wasn't able to reproduce either, but it's bugged on our main server. But guess thats another issue somwhere else
