### ISSUE TITLE
[Dupe] Thaumcraft 6 + Harvestcraft + GD (+ FAWE?): dupe in wilderness and in claim

### ISSUE THREAD

**Issue by PolyacovYury** [bloodmc/GriefDefender#92]
List of possibly affecting mods:
- Thaumcraft-1.12.2-6.1.BETA26
- spongeforge-1.12.2-2838-7.1.8
- Pam's HarvestCraft 1.12.2zb
- Nucleus-1.14.0-S7.1
- griefdefender-sponge-1.2.4-B15
- LuckPerms-Sponge-5.0.49
- FastAsyncWorldEdit-sponge112-18.03.19-18c7145-1053-19.4.16

Issue description:
Thaumcraft golem with Agile and Smart stats (or something along those lines, the tester plays on ru_RU) tries to harvest fully-grown carrots, marked by The Seal of Harvesting (again, ru_RU).
Results are as follows:
- in Wilderness and in a claim of Golem's owner: carrot items are spawned, but the crop block is not modified, so it just continuously dupes items. GDDebug: https://griefdefender.github.io/debug/?zcekANZx9v
- in an untrusted claim: items are not spawned, but console gets spammed with https://pastebin.com/nt0EQe07

**Comment by bloodmc** [comment]
Unable to reproduce with latest versions.

https://griefdefender.github.io/debug/?DqoH7sbegP

Update to HarvestCraft 1.12.2zf and FastAsyncWorldEdit-sponge112-19.11.13-5505943-1282-22.3.5

https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target

**Comment by bloodmc** [comment]
Retested with SF pre-fakeplayer fix and reproduced issue. Sponge commit https://github.com/SpongePowered/SpongeCommon/commit/2f8b976b2e8e618c4c3052869db42bfbddbb25ec solves the dupe issue.
