### ISSUE TITLE
[Issue] Ghost Claim

### ISSUE THREAD

**Issue by WhatsTheBadNews** [bloodmc/GriefDefender#96]
GD Version: 1.2.4-B1
Paper Version: git-Paper-33 (MC: 1.15.1)
LuckPerms Version: v5.0.50

https://www.youtube.com/watch?v=Q5ssT_Uhd7U

Console errors when trying to delete the claim shown in the video:

https://pastebin.com/pF9XLqYE

**Comment by bloodmc** [comment]
Thanks for info. Let me know if you can determine steps to reproduce issue.

**Comment by bigenergy** [comment]
It seems that I also encountered this problem, it was decided by rebooting the server, but I do not know how to reproduce it.

**Comment by bigenergy** [comment]
@bloodmc ok, i understood how to reproduce this error

When you create claims and try to delete them through the /abandonallclaims command, they are not deleted, but the player says that they are deleted and remain in the list of his claims, respectively, the blocks also do not return, and only the /deleteclaim command helps, then it is deleted normally and the blocks are returned . When using the /abandonclaim command, everything works as it should

To repeat, you need:
1. Create several or one claim
2. Note how many privates you have in /claimlist and how many privat blocks are left (preferably for clarity)
3. Enter command /abandonallclaims
4. Check /claimlist and see that the claims remained and the blocks did not return
5. Try to enter command /claiminfo in the place of the region and see that it remains
6. Try to remove it with the /abandonclaim command and see that it remains
Rebooting the plugin does not help

**Comment by bloodmc** [comment]
Can you reproduce this on a clean server with only GD/LP?

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae
