### ISSUE TITLE
just installed plugin with no config popping up

### ISSUE THREAD

**Issue by varnithian97** [bloodmc/GriefDefender#97]
Installed mod into plugins and was not given a config.

Tried doing some basic checks but my assumption is not having a propper jar for spongeforge

Server- RLCRAFT 1.12.2
Spongeforge- 1.12.2
LP-4.1.7
GD-1.2.4

Let me know if any other information is needed, checked system console was not considered installed plugin. Also just bought it so now im super worried

**Comment by bloodmc** [comment]
Did you read the wiki installation guide?

https://github.com/bloodmc/GriefDefender/wiki/Getting-Started

**Comment by varnithian97** [comment]
correct I did, and I beleive it says if using sponge to msg you for the propper jar file. Which is why i sent the message out after it not working
