### ISSUE TITLE
draconic evolution mod require permission to claims

### ISSUE THREAD

**Issue by runescapejon** [bloodmc/GriefDefender#98]
So, I'm not sure if this is a bug or not but I'll put more detail into the issue. Firstly i am running on Spongeforge version 1.12.2-2838-7.1.8 (recommended) and GriefDefender version 1.2.5-B1 I'd also tried compiling the [latest commit](https://github.com/bloodmc/GriefDefender/commit/a3bb1758a4c4ee0935eb582f3975170fc1f618fd) and attempt do this. Also, having draconic evolution version 1.12.2-2.3.24.349 and brendoncore version 1.12.2-2.4.17.208. Once i had them installed I then make a claim. Next I went into creative mode and grab the blocks named _"Energy Core Stabilizer"_ and _"Energy Core"_ I then put them together like this https://gyazo.com/ec22e860c011ec6228160c41ff750067 although know that it doesn't matter about the distance between Energy Core Stabilizer and energy core. Finally once you build them inside the claim, then you right click the energy core stabilizer and you should be able to click the "Activate" https://gyazo.com/05ca74fa823c36d6d18c54277ff2cd31  As you see nothing happens. That because it require permission that i've found here https://luckperms.net/verbose/#4hioThifsv Keep in mind that i do have ALL the permission to GD, it's just it seem that the mod require permission to the claim in some weird way. I know that indeed it's not a sponge matter because i had remove GD from the equation and this issue didn't occur.

**Comment by bloodmc** [comment]
This was actually a SpongeForge bug. Fixed in commit https://github.com/SpongePowered/SpongeForge/commit/7271795d58473940b9de755755bfd32ef655a6e0
