### ISSUE TITLE
[Bypass] Thaumcraft Golems interacting with inventories

### ISSUE THREAD

**Issue by PolyacovYury** [bloodmc/GriefDefender#99]
https://griefdefender.github.io/debug/?kIg63aOIkd

There's a golem running around, harvesting some things and putting them into a chest. Harvesting works fine, putting items into the chest works fine, except...
Golem interacting with the inventory does not show up in the debug. regardless if the chest is in claim or in wilderness. So, the golems ignore claims when it comes to chest interactions - both putting items in and taking them out.
Another debug: https://griefdefender.github.io/debug/?q7oNGuap17
Apparently, item-pickup is also not checked for them.

Separately - I can break my own golem with Golemancer's Bell, even if it is in another player's claim (probably intended).

P.S. Control Seal: Store makes Golems put things into the container it is placed onto; Control Seal: Empty makes them take items out of the container it is on.

**Comment by bloodmc** [comment]
Unfortunately this is due to how golems interact with inventory using direct methods that have no events. You have 2 options

1. Deny the golems from entering a claim.
2. Post a ticket on https://github.com/Azanor/thaumcraft-beta/issues requesting events.
